/** GENERATED by scripts/build-bills-54.mjs — tiny per-topic bill counts for the client /plan. */
export const BILLS_54_TOPIC_COUNTS: Record<string, { passed: number; active: number }> = {
  "economy": {
    "passed": 37,
    "active": 12
  },
  "housing": {
    "passed": 7,
    "active": 6
  },
  "health": {
    "passed": 8,
    "active": 13
  },
  "education": {
    "passed": 4,
    "active": 2
  },
  "climate": {
    "passed": 26,
    "active": 8
  },
  "crime-justice": {
    "passed": 14,
    "active": 12
  }
}
