/** GENERATED by scripts/build-bills-54.mjs — tiny per-topic bill counts for the client /plan. */
export const BILLS_54_TOPIC_COUNTS: Record<string, { passed: number; active: number }> = {
  "economy": {
    "passed": 41,
    "active": 12
  },
  "housing": {
    "passed": 9,
    "active": 6
  },
  "health": {
    "passed": 14,
    "active": 7
  },
  "education": {
    "passed": 5,
    "active": 1
  },
  "climate": {
    "passed": 33,
    "active": 6
  },
  "crime-justice": {
    "passed": 18,
    "active": 12
  }
}
