/** GENERATED by scripts/build-bills-54.mjs — tiny per-topic bill counts for the client /plan. */
export const BILLS_54_TOPIC_COUNTS: Record<string, { passed: number; active: number }> = {
  "economy": {
    "passed": 41,
    "active": 10
  },
  "housing": {
    "passed": 8,
    "active": 7
  },
  "health": {
    "passed": 12,
    "active": 9
  },
  "education": {
    "passed": 5,
    "active": 1
  },
  "climate": {
    "passed": 31,
    "active": 7
  },
  "crime-justice": {
    "passed": 16,
    "active": 13
  }
}
