// AUTO-GENERATED by scripts/fetch-economic-data.mjs on 2026-06-18. Do not edit by hand.
// Sources: CPI from OECD (NZ data sourced from Stats NZ); GDP/unemployment/debt
// from World Bank Open Data (compiling official IMF/ILO/national figures).
// Re-run:  node scripts/fetch-economic-data.mjs

export interface EconPoint { year: number; value: number }
export interface EconSeries {
  id: string; name: string; unit: string; measures: string
  feedLabel: string; feedUrl: string
  primaryLabel: string; primaryUrl: string
  wbLastUpdated: string | null
  points: EconPoint[]
}
export interface EconomicData { generatedAt: string; series: EconSeries[] }

export const ECONOMIC_DATA: EconomicData = {
  "generatedAt": "2026-06-18",
  "series": [
    {
      "id": "cpi",
      "name": "Inflation (CPI)",
      "unit": "%",
      "measures": "Annual change in consumer prices (year-on-year, from the all-items index).",
      "feedLabel": "OECD Data Explorer",
      "feedUrl": "https://data-explorer.oecd.org/",
      "primaryLabel": "Stats NZ — CPI",
      "primaryUrl": "https://www.stats.govt.nz/indicators/consumers-price-index-cpi/",
      "wbLastUpdated": null,
      "points": [
        {
          "year": 2019,
          "value": 1.6
        },
        {
          "year": 2020,
          "value": 1.7
        },
        {
          "year": 2021,
          "value": 3.9
        },
        {
          "year": 2022,
          "value": 7.2
        },
        {
          "year": 2023,
          "value": 5.7
        },
        {
          "year": 2024,
          "value": 2.9
        },
        {
          "year": 2025,
          "value": 2.8
        }
      ]
    },
    {
      "id": "gdp",
      "name": "GDP growth",
      "unit": "%",
      "measures": "Annual change in real GDP.",
      "feedLabel": "World Bank Open Data",
      "feedUrl": "https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG?locations=NZ",
      "primaryLabel": "Stats NZ — GDP",
      "primaryUrl": "https://www.stats.govt.nz/indicators/gross-domestic-product-gdp/",
      "wbLastUpdated": "2026-04-08",
      "points": [
        {
          "year": 2019,
          "value": 2.31747144034802
        },
        {
          "year": 2020,
          "value": -0.307246896026541
        },
        {
          "year": 2021,
          "value": 4.53540565716095
        },
        {
          "year": 2022,
          "value": 3.49638686458842
        },
        {
          "year": 2023,
          "value": 1.39425181563566
        },
        {
          "year": 2024,
          "value": 1.28862004711685
        }
      ]
    },
    {
      "id": "unemployment",
      "name": "Unemployment",
      "unit": "%",
      "measures": "Share of the labour force unemployed (ILO-modelled estimate).",
      "feedLabel": "World Bank Open Data",
      "feedUrl": "https://data.worldbank.org/indicator/SL.UEM.TOTL.ZS?locations=NZ",
      "primaryLabel": "Stats NZ — Labour market",
      "primaryUrl": "https://www.stats.govt.nz/topics/unemployment/",
      "wbLastUpdated": "2026-04-08",
      "points": [
        {
          "year": 2019,
          "value": 4.109
        },
        {
          "year": 2020,
          "value": 4.595
        },
        {
          "year": 2021,
          "value": 3.776
        },
        {
          "year": 2022,
          "value": 3.299
        },
        {
          "year": 2023,
          "value": 3.734
        },
        {
          "year": 2024,
          "value": 4.724
        },
        {
          "year": 2025,
          "value": 5.076
        }
      ]
    },
    {
      "id": "debt",
      "name": "Government debt",
      "unit": "% of GDP",
      "measures": "Central government debt as a share of GDP.",
      "feedLabel": "World Bank Open Data",
      "feedUrl": "https://data.worldbank.org/indicator/GC.DOD.TOTL.GD.ZS?locations=NZ",
      "primaryLabel": "Treasury — Financial statements",
      "primaryUrl": "https://www.treasury.govt.nz/",
      "wbLastUpdated": "2026-04-08",
      "points": [
        {
          "year": 2019,
          "value": 32.7713136024397
        },
        {
          "year": 2020,
          "value": 45.7367082288191
        },
        {
          "year": 2021,
          "value": 51.305380228031
        },
        {
          "year": 2022,
          "value": 53.9638193955627
        },
        {
          "year": 2023,
          "value": 50.1080559619605
        },
        {
          "year": 2024,
          "value": 52.2498447259151
        }
      ]
    }
  ]
}
