/**
 * AUTO-GENERATED — MP portrait photos sourced from Wikimedia Commons.
 * Every image is freely licensed (Commons hosts only free/PD media). Author and
 * licence are recorded per photo for attribution. Merged into MP_PROFILES in
 * mps-data.ts. MPs without a free Commons photo fall back to initials avatars.
 */

export interface MPPhoto { photo: string; credit: string; license: string; sourceUrl: string }

export const MP_PHOTOS: Record<string, MPPhoto> = {
  'ginny-andersen': { photo: '/mps/ginny-andersen.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--ginnyandersen-3-390x2-UNC.jpg' },
  'andrew-bayly': { photo: '/mps/andrew-bayly.jpg', credit: 'Open Data NZ', license: 'CC BY 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Andrew%20Bayly%20(crop).jpg' },
  'camilla-belich': { photo: '/mps/camilla-belich.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--camillabelich-4-390x2-UNC.jpg' },
  'glen-bennett': { photo: '/mps/glen-bennett.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--glenbennett-2-390-UNC.jpg' },
  'dan-bidois': { photo: '/mps/dan-bidois.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:BIDOIS%2C%20Dan%20-%20Northcote%20(cropped).png' },
  'chris-bishop': { photo: '/mps/chris-bishop.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:BISHOP%2C%20Chris%20-%20Hutt%20South%20(cropped).png' },
  'carlos-cheung': { photo: '/mps/carlos-cheung.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cheung,_Carlos_-_Mt_Roskill_(cropped).png' },
  'rachel-boyack': { photo: '/mps/rachel-boyack.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--rachelboyack-390x2-UNC.jpg' },
  'rachel-brooking': { photo: '/mps/rachel-brooking.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--rachelbrooking-2-390x2-UNC.jpg' },
  'simeon-brown': { photo: '/mps/simeon-brown.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:BROWN%2C%20Simeon%20-%20Pakuranga%20(cropped).png' },
  'gerry-brownlee': { photo: '/mps/gerry-brownlee.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:BROWNLEE%2C%20Gerry%20-%20List%20(cropped).png' },
  'karen-chhour': { photo: '/mps/karen-chhour.jpg', credit: 'Doug Mountain', license: 'CC0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Karen%20Chhour%20(crop).jpg' },
  'casey-costello': { photo: '/mps/casey-costello.jpg', credit: 'US Embassy NZ', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Casey%20Costello%20November%202024.jpg' },
  'simon-court': { photo: '/mps/simon-court.jpg', credit: 'US Embassy New Zealand', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Simon%20Court%2C%202025.jpg' },
  'marama-davidson': { photo: '/mps/marama-davidson.jpg', credit: 'Naomi Madeiros', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Marama%20Davidson%202%20(cropped).jpg' },
  'mariameno-kapa-kingi': { photo: '/mps/mariameno-kapa-kingi.jpg', credit: 'Parliamentary Service', license: 'CC BY 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mariameno_Kapa-Kingi_2025.jpg' },
  'matt-doocey': { photo: '/mps/matt-doocey.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:DOOCEY%2C%20Matt%20-%20Waimakariri%20(cropped).png' },
  'barbara-edmonds': { photo: '/mps/barbara-edmonds.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--barbaraedmonds-2-390x2-UNC.jpg' },
  'paulo-garcia': { photo: '/mps/paulo-garcia.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:GARCIA%2C%20Paulo%20-%20New%20Lynn%20(cropped).png' },
  'julie-anne-genter': { photo: '/mps/julie-anne-genter.jpg', credit: 'Naomi Madeiros', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Julie%20Anne%20Genter%203%20(cropped).jpg' },
  'paul-goldsmith': { photo: '/mps/paul-goldsmith.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:GOLDSMITH%2C%20Paul%20-%20Epsom%20(cropped).png' },
  'nicola-grigg': { photo: '/mps/nicola-grigg.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:GRIGG%2C%20Nicola%20-%20Selwyn%20(cropped).png' },
  'shanan-halbert': { photo: '/mps/shanan-halbert.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--shananhalbert-390x2-UNC.jpg' },
  'chris-hipkins': { photo: '/mps/chris-hipkins.jpg', credit: 'New Zealand Labour Party.', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chris%20Hipkins%20NZ%20Labour%20(cropped).jpg' },
  'willie-jackson': { photo: '/mps/willie-jackson.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--williejackson-354.jpg' },
  'shane-jones': { photo: '/mps/shane-jones.jpg', credit: 'Stuartyeates', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Shane%20Jones%202018%205.jpg' },
  'barbara-kuriger': { photo: '/mps/barbara-kuriger.jpg', credit: 'Jakobandrewnz', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bjk.portrait.jpg' },
  'ingrid-leary': { photo: '/mps/ingrid-leary.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--ingridleary-390x2-UNC.jpg' },
  'melissa-lee': { photo: '/mps/melissa-lee.jpg', credit: 'Unknown photographer', license: 'CC BY 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Melissa%20Lee.jpg' },
  'jo-luxton': { photo: '/mps/jo-luxton.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--joluxton-390x2-UNC.jpg' },
  'jenny-marcroft': { photo: '/mps/jenny-marcroft.jpg', credit: 'Office of the Clerk of the House of Representatives of New Zealand', license: 'CC BY 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Jenny%20Marcroft%20(cropped).jpg' },
  'kieran-mcanulty': { photo: '/mps/kieran-mcanulty.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--kieranmcanulty-2-390x2-UNC.jpg' },
  'todd-mcclay': { photo: '/mps/todd-mcclay.jpg', credit: 'USDAgov', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:2025%20Todd%20McClay%20(cropped).jpg' },
  'nicole-mckee': { photo: '/mps/nicole-mckee.jpg', credit: 'Office of the Clerk of the House of Representatives of New Zealand', license: 'CC BY 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nicole%20McKee%202025%20(cropped).jpg' },
  'tracey-mclellan': { photo: '/mps/tracey-mclellan.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--traceymclellan-390x2-UNC.jpg' },
  'ricardo-menendez-march': { photo: '/mps/ricardo-menendez-march.jpg', credit: 'Naomi Madeiros', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ricardo%20Men%C3%A9ndez%20March%204%20(cropped).jpg' },
  'mark-mitchell': { photo: '/mps/mark-mitchell.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:MITCHELL%2C%20Mark%20-%20Whangaparaoa%20(cropped).png' },
  'joseph-mooney': { photo: '/mps/joseph-mooney.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:MOONEY%2C%20Joseph%20-%20Southland%20(cropped).png' },
  'debbie-ngarewa-packer': { photo: '/mps/debbie-ngarewa-packer.jpg', credit: 'Ministry of Foreign Affairs of Japan', license: 'CC BY 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Debbie%20Ngarewa-Packer%20August%202025.jpg' },
  'parmjeet-parmar': { photo: '/mps/parmjeet-parmar.jpg', credit: 'Parmjeet Parmar MP', license: 'CC BY 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Parmjeet%20Parmar.jpg' },
  'mark-patterson': { photo: '/mps/mark-patterson.jpg', credit: 'US Embassy', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mark%20Patterson%202019.jpg' },
  'chris-penk': { photo: '/mps/chris-penk.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:PENK%2C%20Chris%20-%20Kaipara%20ki%20Mahurangi%20(cropped).png' },
  'winston-peters': { photo: '/mps/winston-peters.jpg', credit: 'Foreign, Commonwealth & Development Office', license: 'CC BY 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Winston%20Peters%20in%202024%20(cropped).jpg' },
  'tama-potaka': { photo: '/mps/tama-potaka.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:POTAKA%2C%20Tama%20-%20Hamilton%20West%20(cropped).png' },
  'willow-jean-prime': { photo: '/mps/willow-jean-prime.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--willowjean-390x2-UNC.jpg' },
  'maureen-pugh': { photo: '/mps/maureen-pugh.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:PUGH%2C%20Maureen%20-%20West%20Coast%20-Tasman%20(cropped).png' },
  'priyanca-radhakrishnan': { photo: '/mps/priyanca-radhakrishnan.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--priyancaradhakrishnan-390x2-UNC.jpg' },
  'shane-reti': { photo: '/mps/shane-reti.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:RETI%2C%20Shane%20-%20Whangarei%20(cropped).png' },
  'dan-rosewarne': { photo: '/mps/dan-rosewarne.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dan%20Rosewarne.jpg' },
  'deborah-russell': { photo: '/mps/deborah-russell.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--deborahrussell-390x2-UNC.jpg' },
  'jenny-salesa': { photo: '/mps/jenny-salesa.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--jennysalesa-390x2-UNC.jpg' },
  'carmel-sepuloni': { photo: '/mps/carmel-sepuloni.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--carmelsepuloni-390x2-UNC.jpg' },
  'david-seymour': { photo: '/mps/david-seymour.png', credit: 'Doug Mountain', license: 'CC0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:David%20Seymour%20at%20Government%20House%2C%20Wellington.png' },
  'penny-simmonds': { photo: '/mps/penny-simmonds.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:SIMMONDS%2C%20Penny%20-%20Invercargill%20(cropped).png' },
  'scott-simpson': { photo: '/mps/scott-simpson.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:SIMPSON%2C%20Scott%20-%20Coromandel%20(cropped).png' },
  'stuart-smith': { photo: '/mps/stuart-smith.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:SMITH%2C%20Stuart%20-%20Kaikoura%20(cropped).png' },
  'erica-stanford': { photo: '/mps/erica-stanford.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:STANFORD%2C%20Erica%20-%20East%20Coast%20Bays%20(cropped).png' },
  'chle-swarbrick': { photo: '/mps/chle-swarbrick.jpg', credit: 'Green Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chl%C3%B6e%20Swarbrick.jpg' },
  'jan-tinetti': { photo: '/mps/jan-tinetti.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--jantinetti-390x2-UNC.jpg' },
  'teanau-tuiono': { photo: '/mps/teanau-tuiono.jpg', credit: 'Naomi Madeiros', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Teanau%20Tuiono%204%20(cropped).jpg' },
  'phil-twyford': { photo: '/mps/phil-twyford.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--philtwyford-2-390x2-UNC.jpg' },
  'sam-uffindell': { photo: '/mps/sam-uffindell.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:UFFINDELL%2C%20Sam%20-%20Tauranga%20(cropped).png' },
  'louise-upston': { photo: '/mps/louise-upston.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:UPSTON%2C%20Louise%20-%20Taupo%20(cropped).png' },
  'tangi-utikere': { photo: '/mps/tangi-utikere.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--tangiutikere-390x2-UNC.jpg' },
  'tim-van-de-molen': { photo: '/mps/tim-van-de-molen.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:VAN%20DE%20MOLEN%2C%20Tim%20-%20Waikato%20(cropped).png' },
  'brooke-van-velden': { photo: '/mps/brooke-van-velden.jpg', credit: 'Health & Safety Association NZ', license: 'CC BY 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Brooke%20van%20Velden%20at%202024%20HASANZ%20Conference%20(cropped).jpg' },
  'ayesha-verrall': { photo: '/mps/ayesha-verrall.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--ayeshaverrall-390x2-UNC.jpg' },
  'rawiri-waititi': { photo: '/mps/rawiri-waititi.jpg', credit: 'Ministry of Foreign Affairs of Japan', license: 'CC BY 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rawiri%20Waititi%20August%202025.jpg' },
  'vanushi-walters': { photo: '/mps/vanushi-walters.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--vanushiwalters-390x2-UNC.jpg' },
  'vanessa-weenink': { photo: '/mps/vanessa-weenink.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:WEENINK,_Vanessa_-_Banks_Peninsula_(cropped).png' },
  'simon-watts': { photo: '/mps/simon-watts.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:WATTS%2C%20Simon%20-%20North%20Shore%20(cropped).png' },
  'duncan-webb': { photo: '/mps/duncan-webb.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--duncanwebb-2-390x2-UNC.jpg' },
  'helen-white': { photo: '/mps/helen-white.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--helenwhite-2-390x2-UNC.jpg' },
  'arena-williams': { photo: '/mps/arena-williams.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--arenawilliams-390x2-UNC.jpg' },
  'nicola-willis': { photo: '/mps/nicola-willis.png', credit: 'New Zealand National Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:WILLIS%2C%20Nicola%20-%20Ohariu%20(cropped).png' },
  'david-wilson': { photo: '/mps/david-wilson.jpg', credit: 'Unknown photographer', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:David%20Wilson%20MLC.jpg' },
  'megan-woods': { photo: '/mps/megan-woods.jpg', credit: 'New Zealand Labour Party', license: 'CC BY-SA 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Profile--meganwoods-390x2-UNC.jpg' },
  'judith-collins': { photo: '/mps/judith-collins.jpg', credit: 'US Embassy New Zealand', license: 'Public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:2025%20Judith%20Collins%20(cropped).jpg' },
}
