// AUTO-GENERATED by scripts/enrich-mp-expenses.mjs. Do not edit by hand.
// Per-MP taxpayer-funded travel + accommodation for 1 January – 31 March 2026, from the official
// quarterly Members' Expense Disclosure (Parliamentary Service / Office of the
// Clerk, parliament.nz). Official source — attributed + dated on the profile.

export interface MPExpenses { total: number; accommodation: number; travel: number; period: string; sourceUrl: string; sourceLabel: string }
export const MP_EXPENSES: Record<string, MPExpenses> = {
  "takuta-ferris": {
    "total": 24752.86,
    "accommodation": 7385.75,
    "travel": 17367.11,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mariameno-kapa-kingi": {
    "total": 30046.52,
    "accommodation": 13681.56,
    "travel": 16364.96,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mark-cameron": {
    "total": 8387.82,
    "accommodation": 8400,
    "travel": -12.18,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "karen-chhour": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "simon-court": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "andrew-hoggard": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "cameron-luxton": {
    "total": 19294.33,
    "accommodation": 5387.62,
    "travel": 13906.71,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "laura-mcclure": {
    "total": 22132.74,
    "accommodation": 9302.98,
    "travel": 12829.76,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nicole-mckee": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "parmjeet-parmar": {
    "total": 20947.44,
    "accommodation": 12488.06,
    "travel": 8459.38,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "david-seymour": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "todd-stephenson": {
    "total": 29660.39,
    "accommodation": 12644.95,
    "travel": 17015.44,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "brooke-van-velden": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "steve-abel": {
    "total": 25577.47,
    "accommodation": 10512.08,
    "travel": 15065.39,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "kahurangi-carter": {
    "total": 25219.09,
    "accommodation": 10148.84,
    "travel": 15070.25,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "marama-davidson": {
    "total": 26775.97,
    "accommodation": 9669.44,
    "travel": 17106.53,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mike-davidson": {
    "total": 18770.56,
    "accommodation": 9450.43,
    "travel": 9320.13,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "julie-anne-genter": {
    "total": 5192.26,
    "accommodation": 1977.98,
    "travel": 3214.28,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "francisco-hernandez": {
    "total": 24582.94,
    "accommodation": 12003.92,
    "travel": 12579.02,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "huhana-lyndon": {
    "total": 26687.54,
    "accommodation": 9181.52,
    "travel": 17506.02,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ricardo-menendez-march": {
    "total": 18254.18,
    "accommodation": 9616.69,
    "travel": 8637.49,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tamatha-paul": {
    "total": 11283.68,
    "accommodation": 1065.3,
    "travel": 10218.38,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "lan-pham": {
    "total": 7140.24,
    "accommodation": 1778.77,
    "travel": 5361.47,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chle-swarbrick": {
    "total": 14668.2,
    "accommodation": 6885.21,
    "travel": 7782.99,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "teanau-tuiono": {
    "total": 24532.85,
    "accommodation": 12893.49,
    "travel": 11639.36,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "celia-wade-brown": {
    "total": 18115.68,
    "accommodation": 10461.02,
    "travel": 7654.66,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "scott-willis": {
    "total": 28936.74,
    "accommodation": 11408.02,
    "travel": 17528.72,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "lawrence-xu-nan": {
    "total": 22120.56,
    "accommodation": 10235.83,
    "travel": 11884.73,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ginny-andersen": {
    "total": 10891.92,
    "accommodation": 2113.27,
    "travel": 8778.65,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "camilla-belich": {
    "total": 14604.87,
    "accommodation": 6989.35,
    "travel": 7615.52,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "glen-bennett": {
    "total": 33404.39,
    "accommodation": 12055.13,
    "travel": 21349.26,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rachel-boyack": {
    "total": 23491.75,
    "accommodation": 8790,
    "travel": 14701.75,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rachel-brooking": {
    "total": 11978.37,
    "accommodation": 2002.9,
    "travel": 9975.47,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "georgie-dansey": {
    "total": 13399.12,
    "accommodation": 190.7,
    "travel": 13208.42,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "reuben-davidson": {
    "total": 19073.2,
    "accommodation": 6784.29,
    "travel": 12288.91,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "barbara-edmonds": {
    "total": 16824.53,
    "accommodation": 2295.84,
    "travel": 14528.69,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "shanan-halbert": {
    "total": 16359.52,
    "accommodation": 4428.43,
    "travel": 11931.09,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chris-hipkins": {
    "total": 13501.83,
    "accommodation": 691.74,
    "travel": 12810.09,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "willie-jackson": {
    "total": 20995.88,
    "accommodation": 10533.78,
    "travel": 10462.1,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ingrid-leary": {
    "total": 32989.28,
    "accommodation": 13110.16,
    "travel": 19879.12,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jo-luxton": {
    "total": 23800.98,
    "accommodation": 9711.1,
    "travel": 14089.88,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tracey-mclellan": {
    "total": 16607,
    "accommodation": 9094.35,
    "travel": 7512.65,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "kieran-mcanulty": {
    "total": 9721.67,
    "accommodation": 8400,
    "travel": 1321.67,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "greg-oconnor": {
    "total": 5989.83,
    "accommodation": 1115.43,
    "travel": 4874.4,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "damien-oconnor": {
    "total": 41285.45,
    "accommodation": 9960,
    "travel": 31325.45,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "willow-jean-prime": {
    "total": 19545.37,
    "accommodation": 10118.35,
    "travel": 9427.02,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "priyanca-radhakrishnan": {
    "total": 6700.79,
    "accommodation": 0,
    "travel": 6700.79,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "dan-rosewarne": {
    "total": 1544.74,
    "accommodation": 0,
    "travel": 1544.74,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "deborah-russell": {
    "total": 17956.01,
    "accommodation": 6161.87,
    "travel": 11794.14,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "carmel-sepuloni": {
    "total": 16252.14,
    "accommodation": 5880,
    "travel": 10372.14,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jenny-salesa": {
    "total": 13346.55,
    "accommodation": 8626.09,
    "travel": 4720.46,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "lemauga-lydia-sosene": {
    "total": 21399.21,
    "accommodation": 9919.62,
    "travel": 11479.59,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "cushla-tangaere-manuel": {
    "total": 22505.49,
    "accommodation": 9988.23,
    "travel": 12517.26,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jan-tinetti": {
    "total": 21807.66,
    "accommodation": 9238.87,
    "travel": 12568.79,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "phil-twyford": {
    "total": 16098.55,
    "accommodation": 8400,
    "travel": 7698.55,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tangi-utikere": {
    "total": 24640.3,
    "accommodation": 12404.16,
    "travel": 12236.14,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ayesha-verrall": {
    "total": 2273.63,
    "accommodation": 630.87,
    "travel": 1642.76,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "vanushi-walters": {
    "total": 22478.77,
    "accommodation": 8562.4,
    "travel": 13916.37,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "duncan-webb": {
    "total": 19401.9,
    "accommodation": 10019.13,
    "travel": 9382.77,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "helen-white": {
    "total": 17966.49,
    "accommodation": 9136.84,
    "travel": 8829.65,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "arena-williams": {
    "total": 23354.96,
    "accommodation": 8634.78,
    "travel": 14720.18,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "megan-woods": {
    "total": 17121.22,
    "accommodation": 9174.35,
    "travel": 7946.87,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "oriini-kaipara": {
    "total": 26313.44,
    "accommodation": 10971.47,
    "travel": 15341.97,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "hana-rawhiti-maipi-clarke": {
    "total": 15976.8,
    "accommodation": 9743.58,
    "travel": 6233.22,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "debbie-ngarewa-packer": {
    "total": 9924.59,
    "accommodation": 9602.2,
    "travel": 322.39,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rawiri-waititi": {
    "total": 28459.75,
    "accommodation": 9652.53,
    "travel": 18807.22,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "miles-anderson": {
    "total": 24123.48,
    "accommodation": 9070.47,
    "travel": 15053.01,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "carl-bates": {
    "total": 19252.45,
    "accommodation": 9466.44,
    "travel": 9786.01,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "andrew-bayly": {
    "total": 19053.24,
    "accommodation": 8825.74,
    "travel": 10227.5,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "dan-bidois": {
    "total": 14061.99,
    "accommodation": 8612.87,
    "travel": 5449.12,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chris-bishop": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "cameron-brewer": {
    "total": 23785.91,
    "accommodation": 8160.87,
    "travel": 15625.04,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "gerry-brownlee": {
    "total": 31876.28,
    "accommodation": 12000,
    "travel": 19876.28,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "simeon-brown": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mike-butterick": {
    "total": 16498,
    "accommodation": 9191.91,
    "travel": 7306.09,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "hamish-campbell": {
    "total": 16473.28,
    "accommodation": 9078.26,
    "travel": 7395.02,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "carlos-cheung": {
    "total": 18341.54,
    "accommodation": 8825.74,
    "travel": 9515.8,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "judith-collins": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tim-costley": {
    "total": 19343.5,
    "accommodation": 8825.74,
    "travel": 10517.76,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "matt-doocey": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "greg-fleming": {
    "total": 26405.86,
    "accommodation": 5474.85,
    "travel": 20931.01,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "paulo-garcia": {
    "total": 20770.25,
    "accommodation": 9425.04,
    "travel": 11345.21,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "paul-goldsmith": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nicola-grigg": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ryan-hamilton": {
    "total": 18370.57,
    "accommodation": 8825.74,
    "travel": 9544.83,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "dana-kirkpatrick": {
    "total": 23743.97,
    "accommodation": 11085.45,
    "travel": 12658.52,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "barbara-kuriger": {
    "total": 34044.8,
    "accommodation": 13356.34,
    "travel": 20688.46,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "melissa-lee": {
    "total": 19743.5,
    "accommodation": 8831.41,
    "travel": 10912.09,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "christopher-luxon": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nancy-lu": {
    "total": 23998.87,
    "accommodation": 3005.15,
    "travel": 20993.72,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "todd-mcclay": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "grant-mccallum": {
    "total": 22464.08,
    "accommodation": 5585.79,
    "travel": 16878.29,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "david-macleod": {
    "total": 22029.12,
    "accommodation": 10892.93,
    "travel": 11136.19,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "james-meager": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mark-mitchell": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "joseph-mooney": {
    "total": 20253.93,
    "accommodation": 3877.2,
    "travel": 16376.73,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rima-nakhle": {
    "total": 19147.91,
    "accommodation": 8612.87,
    "travel": 10535.04,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "katie-nimon": {
    "total": 18965.54,
    "accommodation": 3345.31,
    "travel": 15620.23,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tama-potaka": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "maureen-pugh": {
    "total": 23435.46,
    "accommodation": 10036.11,
    "travel": 13399.35,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chris-penk": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "shane-reti": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "suze-redmayne": {
    "total": 12713.52,
    "accommodation": 4941.06,
    "travel": 7772.46,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tom-rutherford": {
    "total": 19088.92,
    "accommodation": 8707.1,
    "travel": 10381.82,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "penny-simmonds": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "stuart-smith": {
    "total": 26324.17,
    "accommodation": 11407.73,
    "travel": 14916.44,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "scott-simpson": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "erica-stanford": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "sam-uffindell": {
    "total": 23702.04,
    "accommodation": 9690.77,
    "travel": 14011.27,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "louise-upston": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tim-van-de-molen": {
    "total": 21617.03,
    "accommodation": 9097.92,
    "travel": 12519.11,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "simon-watts": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "catherine-wedd": {
    "total": 24454.91,
    "accommodation": 9359.94,
    "travel": 15094.97,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "vanessa-weenink": {
    "total": 17840.06,
    "accommodation": 8597.71,
    "travel": 9242.35,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nicola-willis": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jamie-arbuckle": {
    "total": 37900.51,
    "accommodation": 12805.19,
    "travel": 25095.32,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "casey-costello": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "andy-foster": {
    "total": 17225.42,
    "accommodation": 12481.21,
    "travel": 4744.21,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "shane-jones": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jenny-marcroft": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mark-patterson": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "winston-peters": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "david-wilson": {
    "total": 20046.94,
    "accommodation": 7516.78,
    "travel": 12530.16,
    "period": "1 January – 31 March 2026",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  }
}
