// AUTO-GENERATED by scripts/build-mp-written-questions.mjs. Do not edit by hand.
// Per-MP written parliamentary questions asked in the 54th Parliament term (since the
// 2023 election), from questions.parliament.nz's public search API — the same shared
// platform as bills.parliament.nz's official bills API. Counts, minister breakdown, and
// question/reply text are all real official record; nothing invented or summarised.

export interface WrittenQuestionDetail { minister: string; date: string; question: string; reply: string | null }
export interface MinisterBreakdown { minister: string; count: number }
export interface MPWrittenQuestions { count: number; byMinister: MinisterBreakdown[]; recent: WrittenQuestionDetail[] }
export const WRITTEN_QUESTIONS_META = {
  term: 54,
  sourceUrl: 'https://questions.parliament.nz/',
  sourceLabel: "Written Parliamentary Questions (questions.parliament.nz)",
}
export const MP_WRITTEN_QUESTIONS: Record<string, MPWrittenQuestions> = {}
