// AUTO-GENERATED by scripts/build-mp-expenses-term.mjs. Do not edit by hand.
// Per-MP taxpayer-funded travel + accommodation for EVERY quarter published so far in
// the 54th Parliament term (since the 14 Oct 2023 election) — official quarterly
// Members' Expense Disclosure (Parliamentary Service / Office of the Clerk, via
// data.govt.nz). Nothing invented; MPs who changed party mid-term may be missing
// some earlier quarters (filed under their old party) — a disclosed limitation.
// Covers: 1 October – 31 December 2023 to 1 October – 31 December 2025.

export interface MPExpenseQuarter { period: string; total: number; accommodation: number; travel: number }
export interface MPExpensesTerm { quarters: MPExpenseQuarter[]; termTotal: number; termAccommodation: number; termTravel: number }
export const TERM_EXPENSES_META = {
  asOf: '1 October – 31 December 2025',
  quarterCount: 9,
  sourceUrl: 'https://www.parliament.nz/en/mps-and-electorates/mps-expenses/',
  sourceLabel: "Members' expense disclosure (parliament.nz)",
}
export const MP_EXPENSES_TERM: Record<string, MPExpensesTerm> = {}
