// AUTO-GENERATED by scripts/enrich-mps-wikipedia.mjs. Do not edit by hand.
// Bios = the lead summary of each MP's Wikipedia article (CC BY-SA 4.0), used
// ONLY where no curated parliament.nz bio exists, and attributed on the profile.
// Auto-matched — spot-check for the rare wrong-person match.

export const MP_WIKI: Record<string, { bio: string; wikipediaUrl: string }> = {
  "oriini-kaipara": {
    "bio": "Oriini Ngawai Kaipara is a New Zealand politician, broadcaster, journalist and translator and interpreter of Māori and English. She has served as a Member of Parliament since winning the Tāmaki Makaurau by-election for Te Pāti Māori in September 2025.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Oriini_Kaipara"
  },
  "mike-davidson": {
    "bio": "Michael John Davidson is a New Zealand politician. He has represented the Green Party of Aotearoa New Zealand as a Member of Parliament since 6 October 2025, when he replaced Benjamin Doyle.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Mike_Davidson_(politician)"
  },
  "steve-abel": {
    "bio": "Stephen George Bremner Abel is a New Zealand politician, environmental activist and musician who is involved with Greenpeace. Since 2023 he has served as a list member of parliament for the Green Party of Aotearoa New Zealand.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Steve_Abel"
  },
  "ginny-andersen": {
    "bio": "Virginia Ruby Andersen is a New Zealand politician. She has been a Member of Parliament in the House of Representatives for the Labour Party since the 2017 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ginny_Andersen"
  },
  "miles-anderson": {
    "bio": "Miles John Anderson is a New Zealand farmer and politician. He was elected as a Member of the New Zealand House of Representatives for Waitaki, representing the National Party, in the 2023 New Zealand general election. From a farming background, he was with Federated Farmers, chaired one of their national bodies, and was on their national board.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Miles_Anderson_(politician)"
  },
  "jamie-arbuckle": {
    "bio": "Jamie Arthur Arbuckle is a New Zealand politician. He is currently a Member of Parliament in the New Zealand House of Representatives for the New Zealand First party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Jamie_Arbuckle"
  },
  "carl-bates": {
    "bio": "Carl Michael Bates is a New Zealand politician, representing the New Zealand National Party as a Member of Parliament since the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Carl_Bates"
  },
  "andrew-bayly": {
    "bio": "Andrew Henry Bayly is a New Zealand businessman, adventurer, and politician. He was elected to the New Zealand Parliament at the 2014 general election as the MP for Hunua, representing the New Zealand National Party. He is currently the MP for Port Waikato.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Andrew_Bayly"
  },
  "camilla-belich": {
    "bio": "Camilla Vera Feslier Belich is a New Zealand lawyer, trade unionist and politician. She has been a Member of Parliament, representing the New Zealand Labour Party, since 2020.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Camilla_Belich"
  },
  "glen-bennett": {
    "bio": "Glen Thomas Bennett is a New Zealand politician and a member of the Labour Party. He was elected the Member of the Parliament for New Plymouth at the 2020 New Zealand general election, defeating the National candidate and incumbent Jonathan Young. He lost his seat to David MacLeod in the 2023 general election, but re-entered parliament on the list in March 2024 following the retirement of Grant Robertson. Prior to entering politics, Bennett worked in the community sector for more than 20 years.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Glen_Bennett"
  },
  "dan-bidois": {
    "bio": "Daniel Michael Bidois is a New Zealand politician.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dan_Bidois"
  },
  "chris-bishop": {
    "bio": "Christopher Bishop is a New Zealand politician for the National Party. He was first elected to the New Zealand House of Representatives in 2014 as a list MP. Bishop won the Hutt South electorate in 2017 but lost the seat in 2020. He returned to Parliament as a National list MP and served as National spokesperson for Housing and Infrastructure and was the Shadow Leader of the House.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Chris_Bishop"
  },
  "rachel-boyack": {
    "bio": "Rachel Elizabeth Boyack-Mayer is a New Zealand unionist and politician. Since 2020, she has been a Member of Parliament for the Labour Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rachel_Boyack"
  },
  "cameron-brewer": {
    "bio": "Cameron Eric Brewer is a New Zealand politician and former journalist.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Cameron_Brewer"
  },
  "rachel-brooking": {
    "bio": "Rachel Jane Brooking is a New Zealand lawyer and politician.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rachel_Brooking"
  },
  "simeon-brown": {
    "bio": "Simeon Peter Brown is a New Zealand politician and Member of Parliament in the House of Representatives for the National Party. Following the 2023 New Zealand general election, Brown became Minister of Energy, Minister of Local Government, Minister of Transport, Minister for Auckland, and Deputy leader of the House in the Sixth National Government. In January 2025, he was appointed as Minister of Health and Minister for State Owned Enterprises, while dropping his energy, local government and transport portfolios. In April 2026, Brown regained his energy portfolio and became the National…",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Simeon_Brown"
  },
  "gerry-brownlee": {
    "bio": "Gerard Anthony Brownlee is a New Zealand politician who has served as the 32nd speaker of the New Zealand House of Representatives since 2023. He was first elected as a member of the New Zealand House of Representatives for Ilam in 1996, representing the National Party. He became a list MP in 2020.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Gerry_Brownlee"
  },
  "mike-butterick": {
    "bio": "Michael David Butterick is a New Zealand farmer and politician. He was elected as a Member of the New Zealand House of Representatives for Wairarapa, representing the National Party, in the 2023 New Zealand general election. In April 2026, Butterick became Minister for Land Information and associate Minister of Agriculture.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Mike_Butterick"
  },
  "mark-cameron": {
    "bio": "Mark Stuart Cameron is a New Zealand politician and dairy farmer. He has been a member of Parliament for ACT New Zealand since the 2020 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Mark_Cameron_(politician)"
  },
  "hamish-campbell": {
    "bio": "Hamish George Campbell is a New Zealand politician and Member of Parliament in the House of Representatives for the National Party. He previously worked as a medical researcher and lecturer, and in his family's orchard business.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Hamish_Campbell"
  },
  "kahurangi-carter": {
    "bio": "Kahurangi \"Kahu\" Carter is a New Zealand politician, representing the Green Party of Aotearoa New Zealand as a Member of Parliament since the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Kahurangi_Carter"
  },
  "carlos-cheung": {
    "bio": "Chun Ho Carlos Cheung is a New Zealand politician. He was elected as a Member of the New Zealand House of Representatives for Mount Roskill, representing the National Party, in the 2023 New Zealand general election. Cheung has worked as a medical researcher and owned two property management companies.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Carlos_Cheung"
  },
  "karen-chhour": {
    "bio": "Karen Louise Chhour is a New Zealand politician. She has been a member of parliament for ACT New Zealand since the 2020 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Karen_Chhour"
  },
  "casey-costello": {
    "bio": "Cassandra Jane \"Casey\" Costello is a New Zealand politician, lobbyist and former police officer. She was elected to the New Zealand House of Representatives, representing the New Zealand First party, in the 2023 New Zealand general election. She was appointed Minister of Customs, Minister for Seniors and Associate Minister of Health in the Sixth National Government of New Zealand.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Casey_Costello"
  },
  "tim-costley": {
    "bio": "Timothy John Costley is a New Zealand politician. He was elected as the Member of Parliament in the House of Representatives for Ōtaki, representing the National Party, in the 2023 general election. He was previously a pilot with the Royal New Zealand Air Force (RNZAF).",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tim_Costley"
  },
  "simon-court": {
    "bio": "Simon Thomas Court is a New Zealand politician. He has been a Member of Parliament for ACT New Zealand since the 2020 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Simon_Court"
  },
  "georgie-dansey": {
    "bio": "Georgina Michaela Celestine Dansey is a New Zealand politician and Member of Parliament in the House of Representatives for the Labour Party. She became a list MP following the resignation of Adrian Rurawhe in 2026.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Georgie_Dansey"
  },
  "marama-davidson": {
    "bio": "Marama Mere-Ana Davidson is a New Zealand politician who has served as a co-leader of the Green Party of Aotearoa New Zealand since 2018.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Marama_Davidson"
  },
  "reuben-davidson": {
    "bio": "Reuben John Davidson is a New Zealand television producer and politician. He was on a Christchurch community board from 2019. In the 2023 general election, he was elected to represent the Christchurch East electorate in Parliament.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Reuben_Davidson"
  },
  "matt-doocey": {
    "bio": "Matthew Maurice Doocey is a New Zealand politician who was elected to the New Zealand Parliament at the 2014 general election as a representative of the New Zealand National Party. He was re-elected in 2017 with a majority increase of over 10,000 which was a significant increase from a majority of 2,500 in 2014. It was reported that this was the largest personal vote increase in the country.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Matt_Doocey"
  },
  "barbara-edmonds": {
    "bio": "Barbara Rachael Fati Palepa Edmonds is a New Zealand politician. She was elected as the Member of the New Zealand Parliament for Mana, representing the Labour Party, in 2020. She served as the Minister of Internal Affairs, Minister for Pacific Peoples, Minister of Revenue and Minister for Economic Development in the final year of the Sixth Labour Government.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Barbara_Edmonds"
  },
  "takuta-ferris": {
    "bio": "Tākuta \"Doc\" Ferris is a New Zealand politician, currently representing Te Tai Tonga in the New Zealand House of Representatives as an independent. He was elected at the 2023 general election as a Te Pāti Māori candidate. Ferris was expelled from the party in November 2025.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/T%C4%81kuta_Ferris"
  },
  "greg-fleming": {
    "bio": "Gregory Wray Fleming is a New Zealand politician and Member of Parliament in the House of Representatives for the National Party. First elected in the 2023 election in the Maungakiekie electorate, he beat the incumbent Priyanca Radhakrishnan. He is a co-founder of the conservative think tank Maxim Institute and is involved in a number of Christian-based charities.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Greg_Fleming_(politician)"
  },
  "andy-foster": {
    "bio": "Andrew John Whitfield Foster is a New Zealand politician. He was elected to the New Zealand House of Representatives as a list MP for the New Zealand First party in the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Andy_Foster"
  },
  "paulo-garcia": {
    "bio": "Paulo Reyes Garcia is a New Zealand lawyer and politician. He is a Member of Parliament in the House of Representatives for the New Zealand National Party and the first New Zealand MP of Filipino descent.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Paulo_Garcia_(New_Zealand_politician)"
  },
  "julie-anne-genter": {
    "bio": "Julie Anne Genter is an American-born New Zealand politician who is a member of the House of Representatives representing the Green Party of Aotearoa New Zealand. Genter was elected to each Parliament from 2011 to 2023 on the party lists, before being elected as the Member of Parliament for the Rongotai electorate in the 2023 election. She served as the Minister for Women, Associate Minister for Health and Associate Minister for Transport during the first term of the Sixth Labour Government. She holds dual citizenship of New Zealand and the United States.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Julie_Anne_Genter"
  },
  "paul-goldsmith": {
    "bio": "Paul Jonathan Goldsmith is a New Zealand historian and politician. The biographer of several leading right-wing political and business figures, he was first elected a list member of the New Zealand House of Representatives for the National Party at the 2011 election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Paul_Goldsmith_(politician)"
  },
  "nicola-grigg": {
    "bio": "Nicola Anna Grigg is a New Zealand politician and Member of Parliament in the House of Representatives representing the Selwyn electorate since October 2020, and has served as a Minister of the Crown since 27 November 2023. She is currently the Minister for the Environment, Minister of State for Trade and Investment, Minister for Women, and Associate Minister for ACC in the Sixth National Government. She is a member of the National Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Nicola_Grigg"
  },
  "shanan-halbert": {
    "bio": "Shanan Kiritea Halbert is a New Zealand politician of the Labour Party. From 2020 to 2023, he was the Member of Parliament for Northcote. Having lost the Northcote seat in 2023, he was elected as a list member of parliament after the resignation of Kelvin Davis.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Shanan_Halbert"
  },
  "ryan-hamilton": {
    "bio": "Ryan Alexander Hamilton is a New Zealand politician. He has been the Member of Parliament for Hamilton East representing the National Party since the 2023 general election. He was a Hamilton city councillor from 2018 until resigning following his election to Parliament.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ryan_Hamilton_(New_Zealand_politician)"
  },
  "francisco-hernandez": {
    "bio": "Francisco Bagkus Hernandez is a New Zealand politician, representing the Green Party of Aotearoa New Zealand as a Member of Parliament since 7 May 2024.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Francisco_Hernandez_(politician)"
  },
  "chris-hipkins": {
    "bio": "Christopher John Hipkins is a New Zealand politician who has served as leader of the New Zealand Labour Party since January 2023 and leader of the Opposition since November 2023. He was the 41st prime minister of New Zealand from January to November 2023, previously serving as the minister for the public service and minister for education from 2017 to 2023, and the minister for health and the COVID-19 response from 2020 to 2022. He has been the member of Parliament (MP) for Remutaka since the 2008 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Chris_Hipkins"
  },
  "andrew-hoggard": {
    "bio": "Andrew John Hoggard is a New Zealand dairy farmer and politician.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Andrew_Hoggard"
  },
  "willie-jackson": {
    "bio": "William Wakatere Jackson is a New Zealand politician and former unionist, broadcaster and Urban Māori leader. He was a Member of Parliament for the Alliance from 1999 to 2002 and is currently a Labour Party MP, having been re-elected in 2017.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Willie_Jackson_(politician)"
  },
  "shane-jones": {
    "bio": "Shane Geoffrey Jones is a New Zealand politician. He is deputy leader of New Zealand First and a Member of Parliament (MP) in the New Zealand House of Representatives.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Shane_Jones"
  },
  "mariameno-kapa-kingi": {
    "bio": "Mariameno Kapa-Kingi is a New Zealand politician who represents Te Tai Tokerau in the New Zealand House of Representatives. After several decades in iwi social and health services, she was elected at the 2023 general election representing Te Pāti Māori.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Mariameno_Kapa-Kingi"
  },
  "dana-kirkpatrick": {
    "bio": "Dana Margot Kirkpatrick is a New Zealand politician, representing the New Zealand National Party as a Member of Parliament since the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dana_Kirkpatrick"
  },
  "barbara-kuriger": {
    "bio": "Barbara Joan Kuriger is a New Zealand politician who has served as Deputy Speaker of the New Zealand House of Representatives since December 2023. A member of the National Party, Kuriger was first elected as the Member of Parliament (MP) for Taranaki-King Country since 2014.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Barbara_Kuriger"
  },
  "ingrid-leary": {
    "bio": "Ingrid Marieke Leary is a New Zealand politician. In 2020 she was elected as a Member of Parliament in the House of Representatives for the Labour Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ingrid_Leary"
  },
  "melissa-lee": {
    "bio": "Melissa Ji-Yun Lee is a New Zealand politician. She was elected to the House of Representatives as a list MP for the National Party in the 2008 election. She served as the 11th Minister for Economic Development and 2nd Minister for Ethnic Communities from November 2023 to January 2025. She also served as the 28th Minister for Media and Communications from November 2023 to April 2024.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Melissa_Lee"
  },
  "nancy-lu": {
    "bio": "Nancy Nan Lu is a New Zealand politician and Member of Parliament in the House of Representatives for the National Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Nancy_Lu"
  },
  "cameron-luxton": {
    "bio": "Cameron Gib Luxton is a New Zealand politician. He was elected to the New Zealand House of Representatives in the 2023 general election as an ACT New Zealand list Member of Parliament.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Cameron_Luxton"
  },
  "jo-luxton": {
    "bio": "Jo-Anne Marie Luxton is a New Zealand politician. She has been a Member of Parliament in the House of Representatives for the Labour Party since the 2017 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Jo_Luxton"
  },
  "huhana-lyndon": {
    "bio": "Hūhana Melanie Lyndon is a New Zealand politician who was elected on the Green Party list in the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/H%C5%ABhana_Lyndon"
  },
  "david-macleod": {
    "bio": "David Nigel MacLeod is a New Zealand businessman and politician. Since 2023, he is the Member of Parliament in the House of Representatives for New Plymouth, representing the National Party. He previously served as chair of the Taranaki Regional Council from 2007 to 2022.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/David_MacLeod"
  },
  "hana-rawhiti-maipi-clarke": {
    "bio": "Hana-Rawhiti Kareariki Maipi-Clarke is a New Zealand politician, representing Te Pāti Māori as a Member of Parliament since the 2023 New Zealand general election. She is the youngest MP since James Stuart-Wortley.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Hana-Rawhiti_Maipi-Clarke"
  },
  "jenny-marcroft": {
    "bio": "Jennifer Lyn Marcroft is a New Zealand politician and Member of Parliament in the House of Representatives for the New Zealand First party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Jenny_Marcroft"
  },
  "kieran-mcanulty": {
    "bio": "Kieran Michael McAnulty is a New Zealand politician. He was first elected to the New Zealand House of Representatives in 2017, representing the New Zealand Labour Party. He was the Member of Parliament (MP) for Wairarapa between 2020 and 2023, and is currently a list MP.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Kieran_McAnulty"
  },
  "grant-mccallum": {
    "bio": "Grant Lewis McCallum is a New Zealand politician representing the National Party as a Member of Parliament since the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Grant_McCallum"
  },
  "todd-mcclay": {
    "bio": "Todd Michael McClay is a New Zealand politician and former ambassador. He is the Member of Parliament for Rotorua. He was previously an ambassador for the Cook Islands and Niue to the European Union.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Todd_McClay"
  },
  "laura-mcclure": {
    "bio": "Laura Barbara McClure, previously known as Laura Trask, is a New Zealand politician. She was elected to the New Zealand House of Representatives in the 2023 New Zealand general election, representing ACT New Zealand.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Laura_McClure"
  },
  "nicole-mckee": {
    "bio": "Nicole Raima McKee is a New Zealand politician. She has been a Member of Parliament for ACT New Zealand since the 2020 general election. She currently serves as the 12th Minister for Courts and Associate Minister of Justice (Firearms).",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Nicole_McKee"
  },
  "tracey-mclellan": {
    "bio": "Tracey Lee McLellan is a New Zealand politician. From 2020 to 2023, she was a Member of Parliament in the House of Representatives for the Labour Party. In 2024, she re-entered parliament after the resignation of fellow Labour List MP Rino Tirikatene.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tracey_McLellan"
  },
  "james-meager": {
    "bio": "James Rawiri Meager is a New Zealand politician and Member of Parliament in the House of Representatives for the National Party in the electorate of Rangitata.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/James_Meager"
  },
  "ricardo-menendez-march": {
    "bio": "Ricardo Menéndez March is a Mexican-born New Zealand activist and politician who, since 2020, is a Member of Parliament for the Green Party of Aotearoa New Zealand in the House of Representatives.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ricardo_Men%C3%A9ndez_March"
  },
  "mark-mitchell": {
    "bio": "Mark Patrick Mitchell is a New Zealand politician, former police officer and security contractor, and a member of the New Zealand House of Representatives since 2011. He is a member of the centre-right National Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Mark_Mitchell_(New_Zealand_politician)"
  },
  "joseph-mooney": {
    "bio": "Joseph Mooney is a New Zealand politician. In 2020 he was elected as a Member of Parliament in the House of Representatives for the National Party in the Southland electorate.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Joseph_Mooney_(New_Zealand_politician)"
  },
  "rima-nakhle": {
    "bio": "Rima Jillian Nakhle is an Australian-born New Zealand National Party politician and a member of parliament for the Takanini electorate in the House of Representatives.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rima_Nakhle"
  },
  "debbie-ngarewa-packer": {
    "bio": "Debbie Anne Ngarewa-Packer is a New Zealand politician, iwi leader and activist. She is a Member of Parliament and co-leader of Te Pāti Māori alongside Rawiri Waititi, and is the chief executive of the Ngāti Ruanui iwi.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Debbie_Ngarewa-Packer"
  },
  "katie-nimon": {
    "bio": "Katrina Margaret Nimon is a New Zealand politician and Member of Parliament in the House of Representatives for the National Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Katie_Nimon"
  },
  "parmjeet-parmar": {
    "bio": "Kushmiita Parmjeet Kaur Parmar is a New Zealand politician. She first entered Parliament as a list Member of the New Zealand House of Representatives in the 2014 general election, representing the National Party. After failing to be re-elected in the 2020 general election, Parmar changed allegiance to ACT New Zealand and was elected for that party in the 2023 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Parmjeet_Parmar"
  },
  "mark-patterson": {
    "bio": "Mark William James Patterson is a New Zealand farmer, lobbyist and politician. He is a Member of Parliament in the House of Representatives for the New Zealand First party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Mark_Patterson_(New_Zealand_politician)"
  },
  "tamatha-paul": {
    "bio": "Tamatha-Kaye Erin Paul is a New Zealand activist and politician who is a Member of Parliament for Wellington Central. In 2018 she was the first Māori woman to be elected President of the Victoria University of Wellington Students' Association. Running as an independent Paul was elected to the Wellington City Council in 2019. She joined the Green Party of Aotearoa New Zealand ahead of the 2022 local elections.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tamatha_Paul"
  },
  "chris-penk": {
    "bio": "Christopher Aidan Penk is a New Zealand politician who has been a Member of Parliament in the House of Representatives for the National Party since 2017. Following the 2023 New Zealand general election, he assumed the building and construction, land and information, veterans, associate defence, and associate immigration portfolios, and later the small business and manufacturing portfolio in 2025. In 2026, Penk gained the defence and space portfolios, along with the portfolios for the intelligence agencies New Zealand Security Intelligence Service (NZSIS) and the Government Communications…",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Chris_Penk"
  },
  "winston-peters": {
    "bio": "Winston Raymond Peters is a New Zealand politician. He has led the political party New Zealand First since he founded it in 1993, and since November 2023 has served as the 25th minister of foreign affairs. A long-serving member of Parliament (MP), Peters was re-elected for a fifteenth time at the 2023 general election, having previously been an MP from 1979 to 1981, 1984 to 2008 and 2011 to 2020. He served as the 13th deputy prime minister of New Zealand from November 2023 to May 2025. This was his third time in the role, previously serving from 1996 to 1998 and 2017 to 2020. In addition to…",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Winston_Peters"
  },
  "lan-pham": {
    "bio": "Ngoc-Lan Thi Pham is a New Zealand politician and ecologist. She was a regional councillor for Environment Canterbury for six years and was elected to Parliament as a Green in the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lan_Pham"
  },
  "tama-potaka": {
    "bio": "Tama William Potaka is a New Zealand politician and Member of Parliament in the House of Representatives representing the Hamilton West electorate. He is a member of the National Party and was chief executive of Ngāi Tai ki Tāmaki before entering Parliament.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tama_Potaka"
  },
  "willow-jean-prime": {
    "bio": "Willow-Jean Prime is a New Zealand politician. She was first elected a Member of the New Zealand House of Representatives at the 2017 general election as a list representative of the New Zealand Labour Party. She was elected as the Member of Parliament for Northland at the 2020 general election and was re-elected as a list MP in 2023.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Willow-Jean_Prime"
  },
  "maureen-pugh": {
    "bio": "Maureen Helena Pugh is a New Zealand politician. She was the mayor of Westland from 2004 to 2013. She first became a Member of Parliament for the National Party in 2016, leaving Parliament in 2017 and returning in 2018. She was initially a list MP, before winning the West Coast-Tasman electorate in 2023.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Maureen_Pugh"
  },
  "priyanca-radhakrishnan": {
    "bio": "Priyanca Radhakrishnan is a New Zealand politician who has been elected to the New Zealand parliament since the 2017 general election as a representative of the New Zealand Labour Party and was Minister for the Community and Voluntary Sector from 2020 to 2023.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Priyanca_Radhakrishnan"
  },
  "suze-redmayne": {
    "bio": "Susan Emma Dossor Redmayne is a New Zealand politician and Member of Parliament for Rangitīkei representing the National Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Suze_Redmayne"
  },
  "shane-reti": {
    "bio": "Shane Raymond Reti is a New Zealand politician and a member of the New Zealand House of Representatives, and a Cabinet Minister with the roles of Minister for Pacific Peoples, Minister of Science, Innovation, and Technology, Minister of Universities and Minister of Statistics. He was first elected at the 2014 general election as the Member of Parliament (MP) for the Whangārei electorate. He is a member of the New Zealand National Party and served as its deputy leader from 10 November 2020 to 30 November 2021 including a period of five days as interim leader following the ousting of Judith…",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Shane_Reti"
  },
  "dan-rosewarne": {
    "bio": "Daniel Peter Rosewarne is a New Zealand politician and former military officer. He is a Member of Parliament in the New Zealand House of Representatives for the New Zealand Labour Party, serving between July 2022 until October 2023. Rosewarne was unseated during the 2023 New Zealand general election. Following the resignation of Labour MP Peeni Henare in March 2026, Rosewarne re-entered Parliament on the Labour Party list.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dan_Rosewarne"
  },
  "deborah-russell": {
    "bio": "Deborah Faye Russell is a New Zealand academic and politician. She is a Member of Parliament for the Labour Party and served as Minister of Statistics and Minister Responsible for the Earthquake Commission from February to November 2023.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Deborah_Russell"
  },
  "tom-rutherford": {
    "bio": "Tom Rutherford is a New Zealand politician and communications executive. A member of the National Party, he has served as the Member of Parliament for the Bay of Plenty since October 2023.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tom_Rutherford"
  },
  "jenny-salesa": {
    "bio": "Jennifer Teresia Salesa is a New Zealand politician and member of the Labour Party who has served as a Member of Parliament since 2014. She was first elected as MP for Manukau East, and after its abolition in 2020 won the replacement electorate of Panmure-Ōtāhuhu. She served as a Cabinet Minister in the Sixth Labour Government as Minister for Building and Construction, Minister of Customs and Minister for Ethnic Communities from 2017 until 6 November 2020.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Jenny_Salesa"
  },
  "carmel-sepuloni": {
    "bio": "Carmel Jean Sepuloni is a New Zealand politician who served as the 20th deputy prime minister of New Zealand. A member of the Labour Party, she was first elected to Parliament in 2008 for a three-year term as a list Member of Parliament (MP), and was re-elected as MP for Kelston in 2014. In 2023, she was elected as the deputy leader of the Labour Party, succeeding Kelvin Davis.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Carmel_Sepuloni"
  },
  "david-seymour": {
    "bio": "David Breen Seymour is a New Zealand politician who has served as the 21st deputy prime minister of New Zealand since 2025 and as the 1st minister for regulation since 2023. A member of the ACT Party, he has served as its leader and Member of Parliament (MP) for Epsom since 2014.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/David_Seymour"
  },
  "penny-simmonds": {
    "bio": "Penelope Elsie Simmonds is a New Zealand politician, Member of Parliament and a Minister in the House of Representatives for the National Party. She previously served as the chief executive of the Southern Institute of Technology. Following the 2023 New Zealand general election, Simmonds assumed the disability issues, environmental, tertiary education and skills, and associate social development and employment portfolios in the Sixth National Government. In April 2026, Simmonds joined the New Zealand Cabinet and gained the tertiary education and science, innovation and technology portfolios.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Penny_Simmonds"
  },
  "scott-simpson": {
    "bio": "Scott Anthony Simpson is a New Zealand politician and a member of the New Zealand House of Representatives. He is a member of the National Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Scott_Simpson_(politician)"
  },
  "stuart-smith": {
    "bio": "Stuart Tayler Smith is a New Zealand National Party politician. He was first elected as a Member of the New Zealand House of Representatives for the Kaikōura electorate, representing the National Party, in the 2014 general election. As of 2025, he is Senior Whip of the National Party and Chief Government Whip.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Stuart_Smith_(politician)"
  },
  "lemauga-lydia-sosene": {
    "bio": "Lemauga Lydia Sosene is a New Zealand Labour Party politician. She was a member of the Māngere-Ōtāhuhu local board from the October 2010 local elections until her election to the New Zealand House of Representatives in May 2022. After completing the balance of Louisa Wall's term as a list MP, Sosene was elected as MP for Māngere at the 2023 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lemauga_Lydia_Sosene"
  },
  "erica-stanford": {
    "bio": "Erica Louise Stanford is a New Zealand politician and Member of Parliament in the House of Representatives for the National Party. She currently serves as the 49th Minister of Education and the 60th Minister of Immigration in the Sixth National Government of New Zealand.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Erica_Stanford"
  },
  "todd-stephenson": {
    "bio": "Todd Michael Stephenson is a New Zealand lawyer and politician. He was elected as to the New Zealand House of Representatives as a list MP for ACT New Zealand at the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Todd_Stephenson"
  },
  "chle-swarbrick": {
    "bio": "Chlöe Charlotte Swarbrick is a New Zealand politician who has served as a co-leader of the Green Party of Aotearoa New Zealand since 2024.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Chl%C3%B6e_Swarbrick"
  },
  "cushla-tangaere-manuel": {
    "bio": "Cushla Tangaere-Manuel is a New Zealand politician and Member of Parliament in the House of Representatives for the Labour Party. She represents the Ikaroa-Rāwhiti electorate and was first elected at the 2023 general election. Prior to entering parliament, Tangaere-Manuel worked as a broadcaster for TVNZ and Whakaata Māori, and as a sports administrator.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Cushla_Tangaere-Manuel"
  },
  "jan-tinetti": {
    "bio": "Janette Rose Tinetti is a New Zealand politician and a Member of Parliament in the House of Representatives for the Labour Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Jan_Tinetti"
  },
  "teanau-tuiono": {
    "bio": "Teanau Tuiono is a New Zealand politician. In 2020 he became a Member of Parliament in the House of Representatives as a representative of the Green Party of Aotearoa New Zealand.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Teanau_Tuiono"
  },
  "phil-twyford": {
    "bio": "Philip Stoner Twyford is a politician from New Zealand and a member of the Labour Party. He has been a Member of Parliament since 2008. He is the Labour Party MP for Te Atatū.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Phil_Twyford"
  },
  "sam-uffindell": {
    "bio": "Samuel Julian Uffindell is a New Zealand politician and former international banking executive. He has been a Member of Parliament for Tauranga, representing the National Party, since winning a by-election in June 2022.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Sam_Uffindell"
  },
  "louise-upston": {
    "bio": "Louise Claire Upston is a New Zealand politician. She was elected as a Member of the New Zealand House of Representatives for Taupō, representing the National Party, in the 2008 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Louise_Upston"
  },
  "tangi-utikere": {
    "bio": "Tangi William Edward Utikere is a New Zealand politician, and Member of Parliament for Palmerston North since 2020. He was the deputy mayor of Palmerston North from 2016 to 2020, being the first non-Pākehā to serve in that role.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tangi_Utikere"
  },
  "tim-van-de-molen": {
    "bio": "Timothy John van de Molen is a New Zealand politician. He is a Member of the House of Representatives for the Waikato electorate and a representative of the National Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Tim_van_de_Molen"
  },
  "brooke-van-velden": {
    "bio": "Brooke Olivia van Velden is a New Zealand politician who has served as the deputy leader of ACT New Zealand since June 2020. She has been a member of Parliament (MP) since the 2020 general election, first as a list MP and, since 2023, the MP for Tāmaki. Van Velden currently serves in the National-led government as the 38th minister of internal affairs and 6th minister for workplace relations and safety. She is the second youngest cabinet minister in New Zealand history, being just eight days older than Phil Goff was when he became Minister of Housing after the 1984 election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Brooke_van_Velden"
  },
  "ayesha-verrall": {
    "bio": "Ayesha Jennifer Verrall is a New Zealand politician, infectious-diseases physician and researcher with expertise in tuberculosis and international health. Since 2020, she has been a Member of the New Zealand House of Representatives for the Labour Party.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Ayesha_Verrall"
  },
  "celia-wade-brown": {
    "bio": "Celia Margaret Wade-Brown is a New Zealand politician who has been a Green Party list MP since 19 January 2024. She previously served as the 34th mayor of Wellington, the capital city of New Zealand, from 2010 until 2016.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Celia_Wade-Brown"
  },
  "rawiri-waititi": {
    "bio": "Rawiri Wikuki Waititi is a New Zealand politician and iwi leader. He has been co-leader of Te Pāti Māori since 2020, alongside Debbie Ngarewa-Packer. He has served as the Member of Parliament (MP) for Waiariki since 2020, when his election returned Te Pāti Māori to the New Zealand Parliament following their defeat at the 2017 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Rawiri_Waititi"
  },
  "vanushi-walters": {
    "bio": "Vanushi Sitanjali Walters is a New Zealand lawyer and politician who served as Member of Parliament in the House of Representatives for the Labour Party representing the Upper Harbour electorate from 2020 to 2023. She returned to Parliament as a Labour list MP in May 2025, following the resignation of David Parker.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Vanushi_Walters"
  },
  "simon-watts": {
    "bio": "Simon Glen Watts is a New Zealand politician. He has been the Member of the New Zealand House of Representatives for North Shore, representing the National Party, since the 2020 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Simon_Watts"
  },
  "duncan-webb": {
    "bio": "Duncan Alexander Webb is a New Zealand politician, lawyer and academic. He was a law professor at the University of Canterbury from 2000 to 2008, then became a partner at law firm Lane Neave. He was elected as a member of the New Zealand House of Representatives for Christchurch Central, representing the Labour Party, in the 2017 general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Duncan_Webb"
  },
  "catherine-wedd": {
    "bio": "Catherine Jane Wedd is a New Zealand politician and Member of Parliament for the National Party. Wedd currently serves as the chairperson of the Environment Select Committee. She is also Chair of the New Zealand Population and Development Committee which is a cross-party group focused on championing sexual and reproductive health and rights of women. She is a Parliamentary Private Secretary to Minister Mark Mitchell for Cyclone Recovery and was formerly the Deputy Chair of the Finance and Expenditure Committee and a member of the Primary Production Committee.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Catherine_Wedd"
  },
  "vanessa-weenink": {
    "bio": "Vanessa Joan Weenink is a New Zealand politician. She was elected as a Member of the New Zealand House of Representatives for Banks Peninsula, representing the National Party, in the 2023 New Zealand general election. She is a doctor by training.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Vanessa_Weenink"
  },
  "helen-white": {
    "bio": "Helen Ione White is a New Zealand politician. In 2020 she became a Member of Parliament in the House of Representatives for the Labour Party. In 2023, she was chosen by Labour to contest the Mount Albert electorate, previously held by former Prime Minister Jacinda Ardern. White won the seat, holding it for Labour, but by a significantly reduced margin of 18 votes.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Helen_White_(politician)"
  },
  "arena-williams": {
    "bio": "Arena Hinekura Sherburd Williams is a New Zealand Labour Party politician. She has been a Member of Parliament in the House of Representatives for the Manurewa electorate since 2020.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Arena_Williams"
  },
  "nicola-willis": {
    "bio": "Nicola Valentine Willis is a New Zealand politician who has been deputy leader of the National Party since 2021. She is also the Minister of Finance, the Minister for Social Investment, the Minister for Economic Growth, and was also the Minister for the Public Services in the Sixth National Government.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Nicola_Willis"
  },
  "scott-willis": {
    "bio": "Scott Matthew Willis is a New Zealand energy analyst and politician, representing the Green Party of Aotearoa New Zealand as a Member of Parliament since the 2023 New Zealand general election.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Scott_Willis_(politician)"
  },
  "megan-woods": {
    "bio": "Megan Cherie Woods is a New Zealand Labour Party politician who served as a Cabinet Minister in the Sixth Labour Government and has served as Member of Parliament for Wigram since 2011.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Megan_Woods"
  },
  "lawrence-xu-nan": {
    "bio": "Lawrence Xi Xu-Nan is a New Zealand politician and Green Party member of the New Zealand House of Representatives.",
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Lawrence_Xu-Nan"
  }
}
