/**
 * mps-members-bills.ts — GENERATED by scripts/build-members-bills.mjs. Do not edit by hand.
 *
 * Proposed members' bills by MP slug, from NZ Parliament's official ballot list
 * (bills.parliament.nz/proposed-members-bills), captured 24 June 2026.
 * A members' bill is a bill proposed by a non-Minister MP, awaiting the ballot.
 */

export interface ProposedBill { title: string }

export const MEMBERS_BILLS_META = {
  asOf: '24 June 2026',
  total: 72,
  sourceLabel: "Parliament — Proposed Members' Bills",
  sourceUrl: 'https://bills.parliament.nz/proposed-members-bills',
}

export const MP_MEMBERS_BILLS: Record<string, ProposedBill[]> = {
  "tim-costley": [
    {
      "title": "KiwiSaver (Financial Security in Retirement) Amendment Bill"
    }
  ],
  "david-wilson": [
    {
      "title": "Local Government (Auckland Council) (Disestablishment of Independent Māori Statutory Board) Amendment Bill"
    }
  ],
  "barbara-edmonds": [
    {
      "title": "Parliamentary Budget Officer Bill"
    }
  ],
  "ryan-hamilton": [
    {
      "title": "Rates Rebate (Rate-paying Occupiers) Amendment Bill"
    }
  ],
  "vanessa-weenink": [
    {
      "title": "Crimes (Sexual Violence Consent Reform) Amendment Bill"
    }
  ],
  "andy-foster": [
    {
      "title": "Protection of Freedom of Expression Bill"
    }
  ],
  "celia-wade-brown": [
    {
      "title": "Cat Management Bill"
    }
  ],
  "rima-nakhle": [
    {
      "title": "Lawyers and Conveyancers (Employed Lawyers Providing Free Legal Services) Amendment Bill"
    }
  ],
  "laura-mcclure": [
    {
      "title": "Incorporated Societies (Small Societies) Amendment Bill"
    }
  ],
  "willow-jean-prime": [
    {
      "title": "Education and Training (Upholding Te Tiriti o Waitangi) Amendment Bill"
    }
  ],
  "miles-anderson": [
    {
      "title": "Wilding Conifer Control and Eradication Legislation Bill"
    }
  ],
  "jenny-marcroft": [
    {
      "title": "Cash Transactions Protection Bill"
    }
  ],
  "suze-redmayne": [
    {
      "title": "Oaths and Declarations (Administration of Declaration by Chartered Accountant) Amendment Bill"
    }
  ],
  "hana-rawhiti-maipi-clarke": [
    {
      "title": "Members of Parliament (Duty to uphold Te Tiriti o Waitangi) Legislation Bill"
    }
  ],
  "jamie-arbuckle": [
    {
      "title": "Container Return Scheme Bill"
    }
  ],
  "kahurangi-carter": [
    {
      "title": "Pae Ora (Healthy Futures) (Reproductive Health Strategy) Amendment Bill"
    }
  ],
  "francisco-hernandez": [
    {
      "title": "Social Security (Extension of Winter Energy Payment) Amendment Bill"
    }
  ],
  "barbara-kuriger": [
    {
      "title": "Valued Introduced Species Legislation Amendment Bill"
    }
  ],
  "mark-cameron": [
    {
      "title": "Resource Management (National and Regional Emissions) Amendment Bill"
    }
  ],
  "parmjeet-parmar": [
    {
      "title": "Education and Training (Equal Treatment) Amendment Bill"
    }
  ],
  "cameron-luxton": [
    {
      "title": "Local Government (Restoring Democratic Integrity) Amendment Bill"
    }
  ],
  "julie-anne-genter": [
    {
      "title": "Chromated Copper Arsenate Treated Timber (Restricted Use) Legislation Bill"
    }
  ],
  "greg-fleming": [
    {
      "title": "Policing (Cost Recovery for Special Policing Services) Amendment Bill"
    }
  ],
  "camilla-belich": [
    {
      "title": "Crimes (Corporate Homicide) Amendment Bill"
    }
  ],
  "debbie-ngarewa-packer": [
    {
      "title": "Prohibition of Seabed Mining Legislation Amendment Bill"
    }
  ],
  "tamatha-paul": [
    {
      "title": "Residential Tenancies (Renters' Rights) Amendment"
    }
  ],
  "teanau-tuiono": [
    {
      "title": "Tohorā Oranga Bill"
    }
  ],
  "carl-bates": [
    {
      "title": "Employment Relations (Mediation Services) Amendment Bill"
    }
  ],
  "huhana-lyndon": [
    {
      "title": "Electoral (Enhancing the Māori Electoral Option) Amendment Bill"
    }
  ],
  "melissa-lee": [
    {
      "title": "Harmful Digital Communication (Political Commentary) Amendment Bill"
    }
  ],
  "oriini-kaipara": [
    {
      "title": "Youth Homelessness Prevention Bill"
    }
  ],
  "duncan-webb": [
    {
      "title": "Regulatory Standards Act Repeal Bill"
    }
  ],
  "carmel-sepuloni": [
    {
      "title": "Pay Transparency Bill"
    }
  ],
  "dana-kirkpatrick": [
    {
      "title": "Parental Leave and Employment Protection (Shared Leave) Amendment Bill"
    }
  ],
  "kieran-mcanulty": [
    {
      "title": "Accident Compensation (Extended Cover for FENZ Personnel) Amendment Bill"
    }
  ],
  "carlos-cheung": [
    {
      "title": "Smokefree Environments and Regulated Products (Vaping Products) Amendment Bill"
    }
  ],
  "willie-jackson": [
    {
      "title": "Broadcasting (Commercial Video on-Demand Levy) Amendment Bill"
    }
  ],
  "todd-stephenson": [
    {
      "title": "End of Life Choice Amendment Bill"
    }
  ],
  "andrew-bayly": [
    {
      "title": "Crimes (Offence of Failing to Report Child Harm) Amendment Bill"
    }
  ],
  "arena-williams": [
    {
      "title": "Real Estate Agents (Disclosure of Defects) Amendment Bill"
    }
  ],
  "nancy-lu": [
    {
      "title": "Building (Lapse of Building Consent) Amendment Bill"
    }
  ],
  "reuben-davidson": [
    {
      "title": "Online Safety (Duties for Providers of Internet-Based Services) Bill"
    }
  ],
  "mike-davidson": [
    {
      "title": "Marine Mammals (Enhanced Protection) Legislation Amendment Bill"
    }
  ],
  "rachel-brooking": [
    {
      "title": "Building (Energy Efficient Office Buildings) Amendment Bill"
    }
  ],
  "vanushi-walters": [
    {
      "title": "New Zealand Bill of Rights (Reports on Amendments) Amendment Bill"
    }
  ],
  "jo-luxton": [
    {
      "title": "Consumer Guarantees (Agricultural Equipment Repair Information) Amendment Bill"
    }
  ],
  "dan-bidois": [
    {
      "title": "Commerce (Motor Vehicle Information Scheme) Amendment Bill"
    }
  ],
  "ayesha-verrall": [
    {
      "title": "Smokefree Environments and Regulated Products (Preventing Industry Interference) Amendment Bill"
    }
  ],
  "ingrid-leary": [
    {
      "title": "Retirement Villages (Fairer Repayments) Amendment Bill"
    }
  ],
  "david-macleod": [
    {
      "title": "Human Tissue (Organ Donation) Amendment Bill"
    }
  ],
  "steve-abel": [
    {
      "title": "Animal Products (Closing the Welfare Gap) Amendment Bill"
    }
  ],
  "jan-tinetti": [
    {
      "title": "Parental Leave and Employment Protection (Holiday Pay) Amendment Bill"
    }
  ],
  "tracey-mclellan": [
    {
      "title": "Residential Tenancies (Property Inspections) Amendment Bill"
    }
  ],
  "sam-uffindell": [
    {
      "title": "New Zealand Bill of Rights (Right to Equal Suffrage in Local Elections) Amendment Bill"
    }
  ],
  "katie-nimon": [
    {
      "title": "Unit Titles (Body Corporate Insurance Requirements) Amendment Bill"
    }
  ],
  "mariameno-kapa-kingi": [
    {
      "title": "Oranga Tamariki (Mokopuna Māori Authority) Amendment Bill"
    }
  ],
  "hamish-campbell": [
    {
      "title": "Gang Free Ports Bill"
    }
  ],
  "ginny-andersen": [
    {
      "title": "Consumer Guarantees (Motor Vehicle Repair Information) Amendment Bill"
    }
  ],
  "jenny-salesa": [
    {
      "title": "Justices of the Peace (Regulating Justices) Amendment Bill"
    }
  ],
  "chle-swarbrick": [
    {
      "title": "Unlawful Occupation of Palestine Sanctions Bill"
    }
  ],
  "grant-mccallum": [
    {
      "title": "Policing (Killing a Police Dog) Amendment Bill"
    }
  ],
  "simon-court": [
    {
      "title": "Sale and Supply of Alcohol (Repeal of Licensing Trust Monopolies) Amendment Bill"
    }
  ],
  "glen-bennett": [
    {
      "title": "Residential Tenancies (Unfair Rent Increases) Amendment Bill"
    }
  ],
  "ricardo-menendez-march": [
    {
      "title": "Social Security (Purpose and Principles for the Elimination of Hardship) Amendment Bill"
    }
  ],
  "lawrence-xu-nan": [
    {
      "title": "Immigration (Relationship with Human Rights Act) Amendment Bill"
    }
  ],
  "takuta-ferris": [
    {
      "title": "Treaty of Waitangi (Empowerment of Waitangi Tribunal) Amendment Bill"
    }
  ],
  "scott-willis": [
    {
      "title": "Electricity Industry (Separation of Generation and Retail Businesses) Amendment Bill"
    }
  ],
  "cushla-tangaere-manuel": [
    {
      "title": "Fair Trading (Cancellation of Subscription Contracts) Amendment Bill"
    }
  ],
  "maureen-pugh": [
    {
      "title": "Adverse Weather-affected Timber Recovery on Conservation Lands Bill"
    }
  ],
  "deborah-russell": [
    {
      "title": "Security of Workers' Wages Amendment Bill"
    }
  ],
  "rachel-boyack": [
    {
      "title": "Education and Training (Prioritisation in Enrolment Schemes) Amendment Bill"
    }
  ],
  "phil-twyford": [
    {
      "title": "Community Trusts (Investment Transparency) Amendment Bill"
    }
  ]
}
