/**
 * mps-bill-activity.ts — GENERATED by scripts/build-bills-54.mjs. Do not edit by hand.
 * 54th-Parliament bill activity by MP, from the official bills API. Captured 20 July 2026.
 *  - MP_PASSED_BILLS: members' bills that became law (Royal Assent), by MP slug.
 *  - MP_GOV_BILLS:    government bills the MP is "member in charge" of (Ministers).
 */
export interface BillRef { title: string; status?: string }
export const BILL_ACTIVITY_META = { asOf: '20 July 2026', sourceLabel: 'NZ Parliament — Bills', sourceUrl: 'https://bills.parliament.nz/' }
export const MP_PASSED_BILLS: Record<string, BillRef[]> = {
  "kieran-mcanulty": [
    {
      "title": "Sale and Supply of Alcohol (Sales on Anzac Day Morning, Good Friday, Easter Sunday, and Christmas Day) Amendment Bill"
    }
  ],
  "carl-bates": [
    {
      "title": "Juries (Age of Excusal) Amendment Bill"
    }
  ],
  "deborah-russell": [
    {
      "title": "Companies (Address Information) Amendment Bill"
    }
  ],
  "tracey-mclellan": [
    {
      "title": "Evidence (Giving Family Violence Evidence in Family Court Proceedings) Amendment Bill"
    }
  ],
  "camilla-belich": [
    {
      "title": "Employment Relations (Employee Remuneration Disclosure) Amendment Bill"
    }
  ],
  "rima-nakhle": [
    {
      "title": "Corrections (Victim Protection) Amendment Bill"
    }
  ]
}
export const MP_GOV_BILLS: Record<string, BillRef[]> = {
  "louise-upston": [
    {
      "title": "Secondary Legislation Confirmation Bill (No 4)",
      "status": "First Reading"
    },
    {
      "title": "Regulatory Systems (Social Security) Amendment Bill (No 2)",
      "status": "Select Committee"
    },
    {
      "title": "Social Security (Modernisation) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Disability Support Services Bill",
      "status": "Select Committee"
    },
    {
      "title": "Social Security (Jobseeker Support and Accommodation Supplement) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Social Security (Accident Compensation and Calculation of Weekly Income) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Oversight of Oranga Tamariki System Legislation Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Social Security (Mandatory Reviews) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Social Assistance Legislation (Accommodation Supplement and Income-related Rent) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Social Security Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Social Workers Registration Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Regulatory Systems (Social Security) Amendment Bill",
      "status": "Terminated"
    },
    {
      "title": "Social Security (Benefits Adjustment) and Income Tax (Minimum Family Tax Credit) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "simon-watts": [
    {
      "title": "Climate Change Response Amendment Bill",
      "status": "First Reading"
    },
    {
      "title": "Local Government (System Improvements) Amendment Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Taxation (Budget Measures) Bill (No 3)",
      "status": "Royal Assent"
    },
    {
      "title": "Taxation (Annual Rates for 2025–26, Compliance Simplification, and Remedial Measures) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Climate Change Response (2050 Target and Other Matters) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Local Government (Water Services) (Repeals and Amendments) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Local Government (Water Services) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Rates Rebate Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Taxation (Annual Rates for 2024–25, Emergency Response, and Remedial Measures) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Climate Change Response (Emissions Trading Scheme Agricultural Obligations) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Taxation Principles Reporting Act Repeal Bill",
      "status": "Royal Assent"
    }
  ],
  "chris-bishop": [
    {
      "title": "Antisocial Road Use Legislation Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Land Transport (Revenue) Amendment Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Infrastructure Funding and Financing Amendment Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Te Here ā Nuku (Nelson Tenths) Bill",
      "status": "Select Committee"
    },
    {
      "title": "Local Government (Auckland Council) (Transport Governance) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Resource Management (Auckland Housing) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Secondary Legislation Confirmation Bill (No 3)",
      "status": "Royal Assent"
    },
    {
      "title": "Natural Environment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Planning Bill",
      "status": "Second Reading"
    },
    {
      "title": "Fast-track Approvals Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Resource Management (Duration of Consents) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Land Transport (Clean Vehicle Standard) Amendment Bill (No 2)",
      "status": "Royal Assent"
    },
    {
      "title": "Land Transport Management (Time of Use Charging) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Parliament Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Parliament (Repeals and Amendments) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Resource Management (Consenting and Other System Changes) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "New Zealand Infrastructure Commission/Te Waihanga Amendment Bill",
      "status": "First Reading"
    },
    {
      "title": "Valuers Bill",
      "status": "Second Reading"
    },
    {
      "title": "Land Transport (Drug Driving) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Overseas Investment (Build-to-rent and Similar Rental Developments) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Fast-track Approvals Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Secondary Legislation Confirmation Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Residential Tenancies Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Resource Management (Freshwater and Other Matters) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Resource Management (Natural and Built Environment and Spatial Planning Repeal and Interim Fast-track Consenting) Bill",
      "status": "Royal Assent"
    }
  ],
  "brooke-van-velden": [
    {
      "title": "Health and Safety at Work Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Regulatory Systems (Internal Affairs) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Online Casino Gambling Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Employment Leave Bill",
      "status": "Second Reading"
    },
    {
      "title": "Employment Relations Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Employment Relations (Pay Deductions for Partial Strikes) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Equal Pay Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Gambling (Definition of Remote Interactive Gambling) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Fair Pay Agreements Act Repeal Bill",
      "status": "Royal Assent"
    }
  ],
  "matt-doocey": [
    {
      "title": "Mental Health Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Accident Compensation (Interest on Instalment Plans)\nAmendment Bill\n",
      "status": "Royal Assent"
    }
  ],
  "simeon-brown": [
    {
      "title": "Offshore Renewable Energy Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Healthy Futures (Pae Ora) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Pae Ora (Healthy Futures) (3 Day Postnatal Stay) Amendment Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Gas (Market Transparency) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Health Practitioners Competence Assurance Amendment Bill",
      "status": "First Reading"
    },
    {
      "title": "Local Government (Water Services Preliminary Arrangements) Bill\n",
      "status": "Royal Assent"
    },
    {
      "title": "Local Government (Electoral Legislation and Māori Wards and Māori Constituencies) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Land Transport (Clean Vehicle Standard) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Road User Charges (Light Electric RUC Vehicles) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Land Transport Management (Repeal of Regional Fuel Tax) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Water Services Acts Repeal Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Land Transport (Clean Vehicle Discount Scheme Repeal) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "paul-goldsmith": [
    {
      "title": "Constitution Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Climate Change Response (Tort Liability) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Crimes Amendment Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Public Service Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Summary Offences (Move-on Orders) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Ngāti Rāhiri Tumutumu Claims Settlement Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Ngā Hapū o Te Iwi o Whanganui Claims Settlement Bill",
      "status": "Select Committee"
    },
    {
      "title": "Serious Fraud Office Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Trespass (Specified Retail Premises and Other Matters) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Ngāti Ruapani mai Waikaremoana Claims Settlement Bill",
      "status": "Select Committee"
    },
    {
      "title": "Electoral (District Boundaries) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "English Language Bill",
      "status": "Second Reading"
    },
    {
      "title": "Anzac Day Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Ngāti Hāua Claims Settlement Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Te Pire Whakahoki i a Kororipo Pā/Kororipo Pā Vesting Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Electoral Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Judicature (Timeliness) Legislation Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Legal Services (Distribution of Special Fund) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Crimes (Countering Foreign Interference) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Crimes Legislation (Stalking and Harassment) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Telecommunications and Other Matters Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Telecommunications Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Disputes Tribunal Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Marine and Coastal Area (Takutai Moana) (Customary Marine Title) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Broadcasting (Repeal of Advertising Restrictions) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Summary Offences (Demonstrations Near Residential Premises) Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Budapest Convention and Related Matters Legislation Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Ngā Hapū o Ngāti Ranginui Claims Settlement Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Plain Language Act Repeal Bill",
      "status": "Second Reading"
    },
    {
      "title": "Sentencing (Reform) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Bail (Electronic Monitoring) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "District Court (District Court Judges) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Referendums Framework Bill",
      "status": "Second Reading"
    },
    {
      "title": "Term of Parliament (Enabling 4-year Term) Legislation Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Gangs Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Sentencing Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Gangs Legislation Amendment Bill",
      "status": "Terminated"
    },
    {
      "title": "Public Finance (Fines Collection Costs—Budget Measures) \nAmendment Bill\n",
      "status": "Royal Assent"
    },
    {
      "title": "Tauranga Moana Iwi Collective Redress Bill",
      "status": "Second Reading"
    },
    {
      "title": "Legal Services Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "nicole-mckee": [
    {
      "title": "Regulatory Systems (Occupational Regulation) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Regulatory Systems (Tribunals) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Community Magistrates Legislation Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Regulatory Systems (Courts) Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Courts Remote Participation Bill",
      "status": "First Reading"
    },
    {
      "title": "Anti-Money Laundering and Countering Financing of Terrorism (Supervisor, Levy, and Other Matters) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Anti-Money Laundering and Countering Financing of Terrorism Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Overseas Adoptions Legislation Bill",
      "status": "Select Committee"
    },
    {
      "title": "Sale and Supply of Alcohol (Improving Alcohol Regulation) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Arms Bill",
      "status": "Second Reading"
    },
    {
      "title": "Statutes Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Adoption Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Arms (Shooting Clubs, Shooting Ranges, and Other Matters) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Sentencing (Reinstating Three Strikes) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Firearms Prohibition Orders Legislation Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Courts (Remote Participation) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "chris-penk": [
    {
      "title": "Building (Earthquake-prone Buildings) Amendment Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Building Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Building and Construction Sector (Self-certification by Plumbers and Drainlayers) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Armed Forces Discipline Legislation Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Building and Construction (Small Stand-alone Dwellings) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Public Works (Critical Infrastructure) Amendment Bill ",
      "status": "Royal Assent"
    },
    {
      "title": "Veterans' Recognition Bill",
      "status": "First Reading"
    },
    {
      "title": "Building (Overseas Building Products, Standards, and Certification Schemes) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Building (Earthquake-prone Building Deadlines and Other Matters) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "nicola-grigg": [
    {
      "title": "Environmental Reporting Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Environment (Disestablishment of Ministry for the Environment) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Hazardous Substances and New Organisms Amendment Bill",
      "status": "Select Committee"
    }
  ],
  "mark-mitchell": [
    {
      "title": "Emergency Management Bill (No 2)",
      "status": "Committee of whole House"
    },
    {
      "title": "Corrections (Management of Prisoners, and Prisoners’ Property) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Policing Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Child Protection (Child Sex Offender Government Agency Registration) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Policing (Police Vetting) Amendment Bill",
      "status": "Second Reading"
    }
  ],
  "james-meager": [
    {
      "title": "Game Animal Council (Herds of Special Interest) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Regulatory Systems (Transport) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "erica-stanford": [
    {
      "title": "Redress System for Abuse in Care Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Education and Training (System Reform) Amendment Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Immigration (Enhanced Risk Management) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Immigration (Fiscal Sustainability and System Integrity) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Education and Training Amendment Bill (No 2)",
      "status": "Royal Assent"
    },
    {
      "title": "Responding to Abuse in Care Legislation Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "tama-potaka": [
    {
      "title": "Post-settlement Governance Entities (Exemption from Jurisdiction of Māori Land Court) Bill",
      "status": "First Reading"
    },
    {
      "title": "Conservation Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Wildlife (Authorisations) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Te Pire mō Ō-Rākau, Te Pae o Maumahara/Ō-Rākau Remembrance Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Māori Purposes Bill",
      "status": "Second Reading"
    }
  ],
  "todd-mcclay": [
    {
      "title": "India Free Trade Agreement Legislation Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Climate Change Response (Emissions Trading Scheme—Forestry Conversion) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "United Arab Emirates Comprehensive Economic Partnership Agreement Legislation Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Invest New Zealand Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Dairy Industry Restructuring (Export Licences Allocation) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Forests (Log Traders and Forestry Advisers Repeal) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "European Union Free Trade Agreement Legislation Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "nicola-willis": [
    {
      "title": "Appropriation (2025/26 Supplementary Estimates) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Imprest Supply (First for 2026/27) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Appropriation (2026/27 Estimates) Bill",
      "status": "Committee of whole House"
    },
    {
      "title": "Appropriation (2024/25 Confirmation and Validation) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Public Finance Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Income Tax (FamilyBoost) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Imprest Supply (Second for 2025/26) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Appropriation (2025/26 Estimates) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Appropriation (2024/25 Supplementary Estimates) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Imprest Supply (First for 2025/26) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Taxation (Budget Measures) Bill (No 2)",
      "status": "Royal Assent"
    },
    {
      "title": "Appropriation (2023/24 Confirmation and Validation) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Regulatory Systems (Economic Development) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Regulatory Systems (Immigration and Workforce) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Appropriation (2024/25 Estimates) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Imprest Supply (Second for 2024/25) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Appropriation (2023/24 Supplementary Estimates) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Imprest Supply (First for 2024/25) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Taxation (Budget Measures) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Appropriation (2022/23 Confirmation and Validation) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Reserve Bank of New Zealand (Economic Objective) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "cameron-brewer": [
    {
      "title": "Credit Contracts and Consumer Finance Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Patents Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Financial Service Providers (Registration and Dispute Resolution) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Fair Trading Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Financial Markets Conduct Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Commerce (Commerce Commission Reform) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Commerce (Promoting Competition and Other Matters) Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Retail Payment System (Ban on Merchant Surcharges) Amendment Bill",
      "status": "Second Reading"
    }
  ],
  "andrew-hoggard": [
    {
      "title": "Agricultural Compounds and Veterinary Medicines Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Animal Welfare (Regulations for Management of Pigs) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "mike-butterick": [
    {
      "title": "Crown Land Legislation Amendment Bill",
      "status": "First Reading"
    },
    {
      "title": "Public Works Amendment Bill",
      "status": "Second Reading"
    }
  ],
  "winston-peters": [
    {
      "title": "Racing Industry (Closure of Greyhound Racing Industry) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Racing Industry Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Racing Industry (Unlawful Destruction of Specified Greyhounds) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "shane-jones": [
    {
      "title": "Fisheries Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Crown Minerals Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Resource Management (Extended Duration of Coastal Permits for Marine Farms) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "scott-simpson": [
    {
      "title": "Data and Statistics (Census) Amendment Bill",
      "status": "Select Committee"
    },
    {
      "title": "Customer and Product Data Bill",
      "status": "Royal Assent"
    }
  ],
  "david-seymour": [
    {
      "title": "Overseas Investment (National Interest Test and Other Matters) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Education and Training (Early Childhood Education Reform) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Regulatory Standards Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Medicines Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Principles of the Treaty of Waitangi Bill",
      "status": "Terminated"
    },
    {
      "title": "Education and Training Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Misuse of Drugs (Pseudoephedrine) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "New Zealand Productivity Commission Act Repeal Bill",
      "status": "Royal Assent"
    }
  ],
  "penny-simmonds": [
    {
      "title": "Meteorological Services (Acquisition and Policies) Legislation Amendment Bill",
      "status": "Second Reading"
    },
    {
      "title": "Education and Training (Vocational Education and Training System) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Gene Technology Bill",
      "status": "Second Reading"
    },
    {
      "title": "Waste Minimisation (Waste Disposal Levy) Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "casey-costello": [
    {
      "title": "Customs (Levies and Other Matters) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Smokefree Environments and Regulated Products Amendment Bill (No 2) ",
      "status": "Royal Assent"
    },
    {
      "title": "Therapeutic Products Act Repeal Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Smokefree Environments and Regulated Products Amendment Bill",
      "status": "Royal Assent"
    }
  ],
  "karen-chhour": [
    {
      "title": "Oranga Tamariki (Repeal of Section 7AA) Amendment Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
      "status": "Second Reading"
    }
  ],
  "andrew-bayly": [
    {
      "title": "Contracts of Insurance (Repeals and Amendments) Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Contracts of Insurance Bill",
      "status": "Royal Assent"
    },
    {
      "title": "Business Payment Practices Act Repeal Bill",
      "status": "Royal Assent"
    }
  ],
  "shane-reti": [
    {
      "title": "Pae Ora (Disestablishment of Māori Health Authority) Amendment Bill",
      "status": "Royal Assent"
    }
  ]
}
