// AUTO-GENERATED by scripts/enrich-mp-expenses.mjs. Do not edit by hand.
// Per-MP taxpayer-funded travel + accommodation for 1 October – 31 December 2025, from the official
// quarterly Members' Expense Disclosure (Parliamentary Service / Office of the
// Clerk, via data.govt.nz). Official source — attributed + dated on the profile.

export interface MPExpenses { total: number; accommodation: number; travel: number; period: string; sourceUrl: string; sourceLabel: string }
export const MP_EXPENSES: Record<string, MPExpenses> = {
  "takuta-ferris": {
    "total": 42773.38,
    "accommodation": 8913.27,
    "travel": 33860.11,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mariameno-kapa-kingi": {
    "total": 39933.24,
    "accommodation": 16152.57,
    "travel": 23780.67,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mark-cameron": {
    "total": 12397.81,
    "accommodation": 9800,
    "travel": 2597.81,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "karen-chhour": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "simon-court": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "andrew-hoggard": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "cameron-luxton": {
    "total": 23956.16,
    "accommodation": 10528.76,
    "travel": 13427.4,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "laura-mcclure": {
    "total": 24163.57,
    "accommodation": 11180.21,
    "travel": 12983.36,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nicole-mckee": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "parmjeet-parmar": {
    "total": 1170.25,
    "accommodation": -18832.17,
    "travel": 20002.42,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "david-seymour": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "todd-stephenson": {
    "total": 21533.85,
    "accommodation": 11537.56,
    "travel": 9996.29,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "steve-abel": {
    "total": 23347.04,
    "accommodation": 11016.74,
    "travel": 12330.3,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "kahurangi-carter": {
    "total": 20851.28,
    "accommodation": 10883.9,
    "travel": 9967.38,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mike-davidson": {
    "total": 15229.89,
    "accommodation": 8369.06,
    "travel": 6860.83,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "julie-anne-genter": {
    "total": 4827.43,
    "accommodation": 0,
    "travel": 4827.43,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "francisco-hernandez": {
    "total": 29584.75,
    "accommodation": 14382.11,
    "travel": 15202.64,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "huhana-lyndon": {
    "total": 31899.11,
    "accommodation": 8733.77,
    "travel": 23165.34,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tamatha-paul": {
    "total": 17294.85,
    "accommodation": 6020.16,
    "travel": 11274.69,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "lan-pham": {
    "total": 2173.87,
    "accommodation": 574.35,
    "travel": 1599.52,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chle-swarbrick": {
    "total": 23564.3,
    "accommodation": 7579.65,
    "travel": 15984.65,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "teanau-tuiono": {
    "total": 42606.49,
    "accommodation": 10366.37,
    "travel": 32240.12,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "celia-wade-brown": {
    "total": 18833.87,
    "accommodation": 9998.7,
    "travel": 8835.17,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "scott-willis": {
    "total": 30241.63,
    "accommodation": 11495.52,
    "travel": 18746.11,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "lawrence-xu-nan": {
    "total": 25941.02,
    "accommodation": 12183.67,
    "travel": 13757.35,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ginny-andersen": {
    "total": 15030.32,
    "accommodation": 737.77,
    "travel": 14292.55,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "camilla-belich": {
    "total": 24965.58,
    "accommodation": 7501.74,
    "travel": 17463.84,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "glen-bennett": {
    "total": 28388.24,
    "accommodation": 12301.48,
    "travel": 16086.76,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rachel-boyack": {
    "total": 29712.31,
    "accommodation": 11619.35,
    "travel": 18092.96,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rachel-brooking": {
    "total": 14271.49,
    "accommodation": 3197.34,
    "travel": 11074.15,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "reuben-davidson": {
    "total": 31232.63,
    "accommodation": 13346.76,
    "travel": 17885.87,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "barbara-edmonds": {
    "total": 26732.29,
    "accommodation": 5447.43,
    "travel": 21284.86,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "shanan-halbert": {
    "total": 14271.73,
    "accommodation": 4891.24,
    "travel": 9380.49,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chris-hipkins": {
    "total": 18161.61,
    "accommodation": 1314.33,
    "travel": 16847.28,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "willie-jackson": {
    "total": 21501.84,
    "accommodation": 10134.35,
    "travel": 11367.49,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ingrid-leary": {
    "total": 24967.04,
    "accommodation": 10482.78,
    "travel": 14484.26,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jo-luxton": {
    "total": 35425.86,
    "accommodation": 12738.88,
    "travel": 22686.98,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tracey-mclellan": {
    "total": 19301.04,
    "accommodation": 10426.09,
    "travel": 8874.95,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "kieran-mcanulty": {
    "total": 19821.47,
    "accommodation": 12968.66,
    "travel": 6852.81,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "willow-jean-prime": {
    "total": 30567.09,
    "accommodation": 12274.15,
    "travel": 18292.94,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "priyanca-radhakrishnan": {
    "total": 25895.81,
    "accommodation": 6098.04,
    "travel": 19797.77,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "deborah-russell": {
    "total": 22112.53,
    "accommodation": 6264.98,
    "travel": 15847.55,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "carmel-sepuloni": {
    "total": 23127.17,
    "accommodation": 6860,
    "travel": 16267.17,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jenny-salesa": {
    "total": 21002.16,
    "accommodation": 9800,
    "travel": 11202.16,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "lemauga-lydia-sosene": {
    "total": 20912.43,
    "accommodation": 10150.08,
    "travel": 10762.35,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "cushla-tangaere-manuel": {
    "total": 25612.06,
    "accommodation": 12907.21,
    "travel": 12704.85,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jan-tinetti": {
    "total": 25276.6,
    "accommodation": 11229,
    "travel": 14047.6,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "phil-twyford": {
    "total": 21454.75,
    "accommodation": 9800,
    "travel": 11654.75,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tangi-utikere": {
    "total": 22620.95,
    "accommodation": 12549.33,
    "travel": 10071.62,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ayesha-verrall": {
    "total": 9837.77,
    "accommodation": 1684.48,
    "travel": 8153.29,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "vanushi-walters": {
    "total": 27883.53,
    "accommodation": 9963.48,
    "travel": 17920.05,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "duncan-webb": {
    "total": 19803.95,
    "accommodation": 10802.51,
    "travel": 9001.44,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "helen-white": {
    "total": 21518.93,
    "accommodation": 9939.13,
    "travel": 11579.8,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "arena-williams": {
    "total": 28485.13,
    "accommodation": 10872.42,
    "travel": 17612.71,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "megan-woods": {
    "total": 28253.94,
    "accommodation": 10248.24,
    "travel": 18005.7,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "oriini-kaipara": {
    "total": 12159.24,
    "accommodation": 691.83,
    "travel": 11467.41,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "hana-rawhiti-maipi-clarke": {
    "total": 24469.25,
    "accommodation": 9800,
    "travel": 14669.26,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "debbie-ngarewa-packer": {
    "total": 24123.35,
    "accommodation": 10688.15,
    "travel": 13435.2,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rawiri-waititi": {
    "total": 30700.43,
    "accommodation": 11485.04,
    "travel": 19215.39,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "miles-anderson": {
    "total": 27714.07,
    "accommodation": 12196.63,
    "travel": 15517.44,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "carl-bates": {
    "total": 24507.07,
    "accommodation": 10606.62,
    "travel": 13900.45,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "andrew-bayly": {
    "total": 26094.21,
    "accommodation": 9800,
    "travel": 16294.21,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "dan-bidois": {
    "total": 23371.35,
    "accommodation": 9800,
    "travel": 13571.35,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chris-bishop": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "cameron-brewer": {
    "total": 19938.89,
    "accommodation": 4873.82,
    "travel": 15065.07,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "gerry-brownlee": {
    "total": 28909.59,
    "accommodation": 14000,
    "travel": 14909.59,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "simeon-brown": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mike-butterick": {
    "total": 22723.1,
    "accommodation": 12334.46,
    "travel": 10388.64,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "hamish-campbell": {
    "total": 17831.72,
    "accommodation": 8455.32,
    "travel": 9376.4,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "carlos-cheung": {
    "total": 17561.56,
    "accommodation": 9800,
    "travel": 7761.56,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "judith-collins": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tim-costley": {
    "total": 21178.41,
    "accommodation": 10530.52,
    "travel": 10647.89,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "matt-doocey": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "greg-fleming": {
    "total": 25580.16,
    "accommodation": 7345.79,
    "travel": 18234.37,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "paulo-garcia": {
    "total": 27549.58,
    "accommodation": 10740.03,
    "travel": 16809.55,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "paul-goldsmith": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nicola-grigg": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "ryan-hamilton": {
    "total": 16991.37,
    "accommodation": 10030.61,
    "travel": 6960.76,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "dana-kirkpatrick": {
    "total": 23497.3,
    "accommodation": 11560.41,
    "travel": 11936.89,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "barbara-kuriger": {
    "total": 24971.22,
    "accommodation": 14278.26,
    "travel": 10692.96,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "melissa-lee": {
    "total": 27116.97,
    "accommodation": 10478.83,
    "travel": 16638.14,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "christopher-luxon": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nancy-lu": {
    "total": 22057.87,
    "accommodation": 5489.4,
    "travel": 16568.47,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "todd-mcclay": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "grant-mccallum": {
    "total": 27834.27,
    "accommodation": 7524.88,
    "travel": 20309.39,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "david-macleod": {
    "total": 20505.43,
    "accommodation": 10472.43,
    "travel": 10033,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "james-meager": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mark-mitchell": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "joseph-mooney": {
    "total": 31018,
    "accommodation": 10255.57,
    "travel": 20762.43,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "rima-nakhle": {
    "total": 22967.16,
    "accommodation": 10051.55,
    "travel": 12915.61,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "katie-nimon": {
    "total": 1709.01,
    "accommodation": 0,
    "travel": 1709.01,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tama-potaka": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "maureen-pugh": {
    "total": 27020.58,
    "accommodation": 11860.46,
    "travel": 15160.12,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "chris-penk": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "shane-reti": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "suze-redmayne": {
    "total": 14788.68,
    "accommodation": 7248.46,
    "travel": 7540.22,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "tom-rutherford": {
    "total": 23112.3,
    "accommodation": 10396.9,
    "travel": 12715.4,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "penny-simmonds": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "stuart-smith": {
    "total": 30868.63,
    "accommodation": 11106.43,
    "travel": 19762.2,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "scott-simpson": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "erica-stanford": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "sam-uffindell": {
    "total": 26394.69,
    "accommodation": 9800,
    "travel": 16594.69,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "louise-upston": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "simon-watts": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "catherine-wedd": {
    "total": 28460.46,
    "accommodation": 10027.73,
    "travel": 18432.73,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "vanessa-weenink": {
    "total": 20034.04,
    "accommodation": 9800,
    "travel": 10234.04,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "nicola-willis": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jamie-arbuckle": {
    "total": 39073.22,
    "accommodation": 15069,
    "travel": 24004.22,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "casey-costello": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "andy-foster": {
    "total": 19636.17,
    "accommodation": 11665.66,
    "travel": 7970.51,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "shane-jones": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "jenny-marcroft": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "mark-patterson": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "winston-peters": {
    "total": 0,
    "accommodation": 0,
    "travel": 0,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  },
  "david-wilson": {
    "total": 19462.46,
    "accommodation": 6733.23,
    "travel": 12729.23,
    "period": "1 October – 31 December 2025",
    "sourceUrl": "https://www.parliament.nz/en/mps-and-electorates/mps-expenses/",
    "sourceLabel": "Members' expense disclosure (parliament.nz)"
  }
}
