// AUTO-GENERATED by scripts/build-mp-speeches.mjs. Do not edit by hand.
// Per-MP speeches given in the House during the 54th Parliament (since the 2023
// election), tallied from hansard.parliament.nz — the official report of Parliament.
// Counts "DebateItem" records of subtype "Speech" attributed to the member; oral
// questions are a separate subtype and are deliberately NOT counted here.

export interface SpeechRef { title: string; date: string }
export interface MPSpeeches { count: number; recent: SpeechRef[] }
export const SPEECHES_META = {
  term: 54,
  sourceUrl: 'https://hansard.parliament.nz/',
  sourceLabel: 'Hansard — the official report of Parliament (hansard.parliament.nz)',
}
export const MP_SPEECHES: Record<string, MPSpeeches> = {
  "maureen-pugh": {
    "count": 1347,
    "recent": [
      {
        "title": "Start of Sitting Day — Karakia/Prayers",
        "date": "2026-08-06"
      },
      {
        "title": "Start of Sitting Day — Karakia/Prayers",
        "date": "2026-07-30"
      },
      {
        "title": "Start of Sitting Day — Karakia/Prayers",
        "date": "2026-07-23"
      },
      {
        "title": "Bills — Concealment of Location of Victim Remains Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Criminal Records (Clean Slate) (Additional Eligibility) Amendment Bill",
        "date": "2026-07-22"
      }
    ]
  },
  "louise-upston": {
    "count": 342,
    "recent": [
      {
        "title": "Business of the House — Business Statement",
        "date": "2026-08-06"
      },
      {
        "title": "Sittings of the House — Extended Sitting",
        "date": "2026-07-28"
      },
      {
        "title": "Business of the House — Business Statement",
        "date": "2026-07-23"
      },
      {
        "title": "Business of the House — Business Statement",
        "date": "2026-07-23"
      },
      {
        "title": "Bills — Secondary Legislation Confirmation Bill (No 4)",
        "date": "2026-07-23"
      }
    ]
  },
  "todd-stephenson": {
    "count": 163,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "casey-costello": {
    "count": 237,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-29"
      }
    ]
  },
  "oriini-kaipara": {
    "count": 49,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Motions — New Zealand Commonwealth Games Team—Congratulations",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      }
    ]
  },
  "tamatha-paul": {
    "count": 143,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      }
    ]
  },
  "tom-rutherford": {
    "count": 371,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      }
    ]
  },
  "duncan-webb": {
    "count": 559,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      }
    ]
  },
  "nancy-lu": {
    "count": 129,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "dan-rosewarne": {
    "count": 41,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "hamish-campbell": {
    "count": 150,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      }
    ]
  },
  "arena-williams": {
    "count": 528,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "rima-nakhle": {
    "count": 223,
    "recent": [
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-07-29"
      }
    ]
  },
  "camilla-belich": {
    "count": 432,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "james-meager": {
    "count": 456,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "francisco-hernandez": {
    "count": 153,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      }
    ]
  },
  "stuart-smith": {
    "count": 105,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-07-22"
      }
    ]
  },
  "karen-chhour": {
    "count": 117,
    "recent": [
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      }
    ]
  },
  "willow-jean-prime": {
    "count": 169,
    "recent": [
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      }
    ]
  },
  "mariameno-kapa-kingi": {
    "count": 145,
    "recent": [
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-24"
      },
      {
        "title": "Bills — Redress System for Abuse in Care Bill",
        "date": "2026-06-24"
      }
    ]
  },
  "vanushi-walters": {
    "count": 174,
    "recent": [
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "ricardo-menendez-march": {
    "count": 426,
    "recent": [
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "willie-jackson": {
    "count": 199,
    "recent": [
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-08-06"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      }
    ]
  },
  "chris-hipkins": {
    "count": 98,
    "recent": [
      {
        "title": "Personal Explanations — Correction of Interjection",
        "date": "2026-08-05"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Motions — New Zealand Commonwealth Games Team—Congratulations",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-05-20"
      }
    ]
  },
  "winston-peters": {
    "count": 147,
    "recent": [
      {
        "title": "Personal Explanations — Correction of Interjection",
        "date": "2026-08-05"
      },
      {
        "title": "Motions — New Zealand Commonwealth Games Team—Congratulations",
        "date": "2026-08-04"
      },
      {
        "title": "Points of Order — Speaker’s Ruling—Urgent Debate Declined 28 July",
        "date": "2026-07-29"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Motions — Venezuela—Earthquakes",
        "date": "2026-06-30"
      }
    ]
  },
  "simeon-brown": {
    "count": 445,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "mike-butterick": {
    "count": 135,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "reuben-davidson": {
    "count": 133,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Life Jackets for Children and Young Persons Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Debates — Golden Bay Cement—Government Decision to Provide Grant",
        "date": "2026-07-21"
      }
    ]
  },
  "steve-abel": {
    "count": 301,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "ingrid-leary": {
    "count": 339,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Debates — Petitions",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-21"
      }
    ]
  },
  "takuta-ferris": {
    "count": 95,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-24"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-04-01"
      },
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-02-18"
      },
      {
        "title": "Government Business — Debate on Prime Minister’s Statement",
        "date": "2026-02-10"
      }
    ]
  },
  "georgie-dansey": {
    "count": 31,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Antisocial Road Use Legislation Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "scott-simpson": {
    "count": 154,
    "recent": [
      {
        "title": "Sittings of the House — Extended Sitting",
        "date": "2026-08-05"
      },
      {
        "title": "Business of the House — Business Statement",
        "date": "2026-07-30"
      },
      {
        "title": "Debates — Petitions",
        "date": "2026-07-28"
      },
      {
        "title": "Sittings of the House — Urgency",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Environmental Reporting Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "megan-woods": {
    "count": 308,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "joseph-mooney": {
    "count": 110,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Regulatory Systems (Social Security) Amendment Bill (No 2)",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Constitution Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Redress System for Abuse in Care Bill",
        "date": "2026-06-24"
      }
    ]
  },
  "kahurangi-carter": {
    "count": 115,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      }
    ]
  },
  "laura-mcclure": {
    "count": 93,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Employment Relations (Termination of Employment by Agreement) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Concealment of Location of Victim Remains Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Criminal Records (Clean Slate) (Additional Eligibility) Amendment Bill",
        "date": "2026-07-22"
      }
    ]
  },
  "andy-foster": {
    "count": 227,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "mike-davidson": {
    "count": 45,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Criminal Records (Clean Slate) (Additional Eligibility) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Antisocial Road Use Legislation Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "nicola-grigg": {
    "count": 59,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Environment (Disestablishment of Ministry for the Environment) Amendment Bill",
        "date": "2026-05-27"
      },
      {
        "title": "Bills — Environment (Disestablishment of Ministry for the Environment) Amendment Bill",
        "date": "2026-05-27"
      },
      {
        "title": "Bills — Legislation (Definitions of Woman and Man) Amendment Bill",
        "date": "2026-05-20"
      },
      {
        "title": "Bills — Hazardous Substances and New Organisms Amendment Bill",
        "date": "2026-05-14"
      }
    ]
  },
  "vanessa-weenink": {
    "count": 209,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      }
    ]
  },
  "cushla-tangaere-manuel": {
    "count": 99,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Financial Markets Conduct Amendment Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "tim-van-de-molen": {
    "count": 63,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — India Free Trade Agreement Legislation Amendment Bill",
        "date": "2026-06-25"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-24"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-04-29"
      },
      {
        "title": "Bills — Ngāti Rāhiri Tumutumu Claims Settlement Bill",
        "date": "2026-04-22"
      }
    ]
  },
  "rachel-brooking": {
    "count": 478,
    "recent": [
      {
        "title": "Bills — Ōtautahi Community Housing Trust (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "dana-kirkpatrick": {
    "count": 103,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Social Security) Amendment Bill (No 2)",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-24"
      },
      {
        "title": "Bills — Redress System for Abuse in Care Bill",
        "date": "2026-06-24"
      }
    ]
  },
  "scott-willis": {
    "count": 165,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Concealment of Location of Victim Remains Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Concealment of Location of Victim Remains Bill",
        "date": "2026-07-22"
      }
    ]
  },
  "jamie-arbuckle": {
    "count": 93,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Debates — Public Safety (Public Protection Orders) Act 2014",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Community Magistrates Legislation Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Environmental Reporting Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "tangi-utikere": {
    "count": 404,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      }
    ]
  },
  "jan-tinetti": {
    "count": 146,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "katie-nimon": {
    "count": 119,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-21"
      }
    ]
  },
  "helen-white": {
    "count": 348,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "sam-uffindell": {
    "count": 80,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Life Jackets for Children and Young Persons Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Mental Health Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "rachel-boyack": {
    "count": 201,
    "recent": [
      {
        "title": "Bills — Trust Horizon (Trust Variation) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      }
    ]
  },
  "cameron-luxton": {
    "count": 196,
    "recent": [
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Motions — New Zealand Commonwealth Games Team—Congratulations",
        "date": "2026-08-04"
      }
    ]
  },
  "tim-costley": {
    "count": 170,
    "recent": [
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      }
    ]
  },
  "lemauga-lydia-sosene": {
    "count": 103,
    "recent": [
      {
        "title": "Bills — Local Government (Management of Local Authorities) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Emergency Management Bill (No 2)",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Local Government (System Improvements) Amendment Bill",
        "date": "2026-06-23"
      },
      {
        "title": "Bills — Regulatory Systems (Internal Affairs) Amendment Bill",
        "date": "2026-05-28"
      }
    ]
  },
  "tracey-mclellan": {
    "count": 173,
    "recent": [
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Debates — Public Safety (Public Protection Orders) Act 2014",
        "date": "2026-06-30"
      }
    ]
  },
  "shane-reti": {
    "count": 85,
    "recent": [
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Maritime Transport (Lifejackets on Recreational Craft) Amendment Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "suze-redmayne": {
    "count": 108,
    "recent": [
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      }
    ]
  },
  "tama-potaka": {
    "count": 155,
    "recent": [
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "priyanca-radhakrishnan": {
    "count": 136,
    "recent": [
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      }
    ]
  },
  "damien-oconnor": {
    "count": 183,
    "recent": [
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-22"
      }
    ]
  },
  "paul-goldsmith": {
    "count": 321,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      }
    ]
  },
  "lawrence-xu-nan": {
    "count": 1013,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Crimes Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      }
    ]
  },
  "cameron-brewer": {
    "count": 237,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-05"
      },
      {
        "title": "Bills — Commerce (Promoting Competition and Other Matters) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Commerce (Promoting Competition and Other Matters) Amendment Bill",
        "date": "2026-07-30"
      }
    ]
  },
  "christopher-luxon": {
    "count": 29,
    "recent": [
      {
        "title": "Motions — New Zealand Commonwealth Games Team—Congratulations",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Motions — Middle East—Conflict",
        "date": "2026-03-03"
      },
      {
        "title": "Personal Explanations — Question No. 2 to Minister",
        "date": "2026-03-03"
      },
      {
        "title": "Motions — Mount Maunganui—Landslide",
        "date": "2026-01-27"
      }
    ]
  },
  "marama-davidson": {
    "count": 70,
    "recent": [
      {
        "title": "Motions — New Zealand Commonwealth Games Team—Congratulations",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-23"
      },
      {
        "title": "Appointments — Electoral Commission",
        "date": "2026-05-19"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-05-13"
      },
      {
        "title": "Debates — Report of the Education and Workforce Committee on the Inquiry into the Harm Young New Zealanders Encounter Online, and the Roles That Government, Business, and Society Should Play in Addressing Those Harms",
        "date": "2026-05-13"
      }
    ]
  },
  "chris-bishop": {
    "count": 563,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      }
    ]
  },
  "lan-pham": {
    "count": 157,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Pae Ora (Healthy Futures) (3 Day Postnatal Stay) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Environmental Reporting Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Game Animal Council (Herds of Special Interest) Amendment Bill",
        "date": "2026-06-25"
      },
      {
        "title": "Bills — Patents Amendment Bill",
        "date": "2026-05-28"
      }
    ]
  },
  "simon-court": {
    "count": 143,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "mark-patterson": {
    "count": 110,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "debbie-ngarewa-packer": {
    "count": 167,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "huhana-lyndon": {
    "count": 165,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "catherine-wedd": {
    "count": 165,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "grant-mccallum": {
    "count": 174,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "david-macleod": {
    "count": 94,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "ryan-hamilton": {
    "count": 206,
    "recent": [
      {
        "title": "Bills — Natural Environment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "julie-anne-genter": {
    "count": 235,
    "recent": [
      {
        "title": "Bills — Planning Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Life Jackets for Children and Young Persons Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Antisocial Road Use Legislation Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "hana-rawhiti-maipi-clarke": {
    "count": 122,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-21"
      }
    ]
  },
  "deborah-russell": {
    "count": 505,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Criminal Records (Clean Slate) (Additional Eligibility) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Debates — Golden Bay Cement—Government Decision to Provide Grant",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "paulo-garcia": {
    "count": 120,
    "recent": [
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "david-wilson": {
    "count": 50,
    "recent": [
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Financial Markets Conduct Amendment Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Appropriation (2025/26 Supplementary Estimates) Bill",
        "date": "2026-06-23"
      },
      {
        "title": "Bills — Taxation (Budget Measures) Bill (No 3)",
        "date": "2026-05-28"
      }
    ]
  },
  "dan-bidois": {
    "count": 254,
    "recent": [
      {
        "title": "Bills — Te Here ā Nuku (Nelson Tenths) Bill",
        "date": "2026-08-04"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Debates — Petitions",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Life Jackets for Children and Young Persons Bill",
        "date": "2026-07-22"
      }
    ]
  },
  "jenny-salesa": {
    "count": 129,
    "recent": [
      {
        "title": "Bills — Oranga Tamariki (Responding to Serious Youth Offending) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — India Free Trade Agreement Legislation Amendment Bill",
        "date": "2026-06-25"
      }
    ]
  },
  "carl-bates": {
    "count": 237,
    "recent": [
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Debates — Petitions",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Antisocial Road Use Legislation Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "greg-fleming": {
    "count": 75,
    "recent": [
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Debates — Petitions",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Land Transport (Revenue) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "glen-bennett": {
    "count": 171,
    "recent": [
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Climate Change Response (Tort Liability) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Constitution Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "chris-penk": {
    "count": 269,
    "recent": [
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Building Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Building Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Building (Earthquake-prone Buildings) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "carlos-cheung": {
    "count": 152,
    "recent": [
      {
        "title": "Bills — Building and Construction Sector (Strengthening Occupational Licensing Regimes) Amendment Bill",
        "date": "2026-07-30"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Life Jackets for Children and Young Persons Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Antisocial Road Use Legislation Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "david-seymour": {
    "count": 268,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "nicola-willis": {
    "count": 255,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Debates — Golden Bay Cement—Government Decision to Provide Grant",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-24"
      },
      {
        "title": "Bills — Imprest Supply (First for 2026/27) Bill",
        "date": "2026-06-23"
      },
      {
        "title": "Bills — Appropriation (2025/26 Supplementary Estimates) Bill",
        "date": "2026-06-23"
      }
    ]
  },
  "ayesha-verrall": {
    "count": 130,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "simon-watts": {
    "count": 551,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "melissa-lee": {
    "count": 38,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Concealment of Location of Victim Remains Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Criminal Records (Clean Slate) (Additional Eligibility) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — English Language Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Local Government (System Improvements) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "kieran-mcanulty": {
    "count": 330,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Business of the House — Business Statement",
        "date": "2026-07-23"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-21"
      }
    ]
  },
  "nicole-mckee": {
    "count": 452,
    "recent": [
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-23"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-23"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-23"
      }
    ]
  },
  "miles-anderson": {
    "count": 76,
    "recent": [
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Land Transport (Revenue) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "brooke-van-velden": {
    "count": 330,
    "recent": [
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "phil-twyford": {
    "count": 153,
    "recent": [
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-29"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      }
    ]
  },
  "barbara-kuriger": {
    "count": 2593,
    "recent": [
      {
        "title": "Start of Sitting Day — Karakia/Prayers",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Start of Sitting Day — Karakia/Prayers",
        "date": "2026-07-21"
      },
      {
        "title": "Start of Sitting Day — Karakia/Prayers",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Offshore Renewable Energy Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "celia-wade-brown": {
    "count": 128,
    "recent": [
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Debates — Petitions",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Life Jackets for Children and Young Persons Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Infrastructure Funding and Financing Amendment Bill",
        "date": "2026-07-21"
      }
    ]
  },
  "ginny-andersen": {
    "count": 370,
    "recent": [
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Arms Bill",
        "date": "2026-07-23"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      }
    ]
  },
  "jenny-marcroft": {
    "count": 74,
    "recent": [
      {
        "title": "Debates — Petitions",
        "date": "2026-07-28"
      },
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Pae Ora (Healthy Futures) (3 Day Postnatal Stay) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Mental Health Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Mental Health Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "shane-jones": {
    "count": 170,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      },
      {
        "title": "Debates — Golden Bay Cement—Government Decision to Provide Grant",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-04-22"
      },
      {
        "title": "Bills — Appropriation (2024/25 Confirmation and Validation) Bill",
        "date": "2026-04-22"
      }
    ]
  },
  "todd-mcclay": {
    "count": 111,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "rawiri-waititi": {
    "count": 94,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Motions — Regulatory Standards (Excluded Legislation) Notice 2026—Approval and Regulations Review Committee Report",
        "date": "2026-05-26"
      },
      {
        "title": "Appointments — Electoral Commission",
        "date": "2026-05-19"
      }
    ]
  },
  "shanan-halbert": {
    "count": 142,
    "recent": [
      {
        "title": "Debates — General Debate",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Concealment of Location of Victim Remains Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Employment Leave Bill",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Health and Safety at Work Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Local Government (System Improvements) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "matt-doocey": {
    "count": 173,
    "recent": [
      {
        "title": "Sittings of the House — Extended Sitting",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Pae Ora (Healthy Futures) (3 Day Postnatal Stay) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Tribunals) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Mental Health Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Mental Health Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "carmel-sepuloni": {
    "count": 116,
    "recent": [
      {
        "title": "Bills — Crimes (Virginity Testing Practices) Amendment Bill",
        "date": "2026-07-22"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-23"
      },
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      }
    ]
  },
  "mark-mitchell": {
    "count": 76,
    "recent": [
      {
        "title": "Motions — Ryan Fox—British Golf Open Championship",
        "date": "2026-07-21"
      },
      {
        "title": "Debates — Public Safety (Public Protection Orders) Act 2014",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Emergency Management Bill (No 2)",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Emergency Management Bill (No 2)",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Serious Fraud Office Amendment Bill",
        "date": "2026-04-30"
      }
    ]
  },
  "chle-swarbrick": {
    "count": 129,
    "recent": [
      {
        "title": "Debates — Golden Bay Cement—Government Decision to Provide Grant",
        "date": "2026-07-21"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Debates — Handling of Documents Under Official Information Act—Prime Minister’s Office",
        "date": "2026-05-26"
      },
      {
        "title": "Bills — Legislation (Definitions of Woman and Man) Amendment Bill",
        "date": "2026-05-20"
      },
      {
        "title": "Debates — Report of the Education and Workforce Committee on the Inquiry into the Harm Young New Zealanders Encounter Online, and the Roles That Government, Business, and Society Should Play in Addressing Those Harms",
        "date": "2026-05-13"
      }
    ]
  },
  "andrew-hoggard": {
    "count": 94,
    "recent": [
      {
        "title": "Bills — Antisocial Road Use Legislation Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Appropriation (2026/27 Estimates) Bill",
        "date": "2026-06-23"
      },
      {
        "title": "Bills — Hazardous Substances and New Organisms Amendment Bill",
        "date": "2026-05-14"
      },
      {
        "title": "Bills — Agricultural Compounds and Veterinary Medicines Amendment Bill",
        "date": "2026-05-14"
      },
      {
        "title": "Bills — Agricultural Compounds and Veterinary Medicines Amendment Bill",
        "date": "2026-05-14"
      }
    ]
  },
  "parmjeet-parmar": {
    "count": 106,
    "recent": [
      {
        "title": "Bills — Healthy Futures (Pae Ora) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Social Security) Amendment Bill (No 2)",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — India Free Trade Agreement Legislation Amendment Bill",
        "date": "2026-06-25"
      },
      {
        "title": "Debates — Immigration New Zealand—Withholding of Information",
        "date": "2026-06-23"
      },
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      }
    ]
  },
  "jo-luxton": {
    "count": 87,
    "recent": [
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Primary Industries) Amendment Bill",
        "date": "2026-06-30"
      }
    ]
  },
  "barbara-edmonds": {
    "count": 197,
    "recent": [
      {
        "title": "Bills — Regulatory Systems (Occupational Regulation) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Occupational Regulation) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Occupational Regulation) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Bills — Regulatory Systems (Occupational Regulation) Amendment Bill",
        "date": "2026-06-30"
      },
      {
        "title": "Debates — General Debate",
        "date": "2026-05-27"
      }
    ]
  },
  "erica-stanford": {
    "count": 217,
    "recent": [
      {
        "title": "Personal Explanations — Question No. 2 to Minister",
        "date": "2026-06-25"
      },
      {
        "title": "Oral Questions to Ministers — Question No. 9 to Minister",
        "date": "2026-06-24"
      },
      {
        "title": "Bills — Redress System for Abuse in Care Bill",
        "date": "2026-06-24"
      },
      {
        "title": "Bills — Redress System for Abuse in Care Bill",
        "date": "2026-06-24"
      },
      {
        "title": "Debates — Immigration New Zealand—Withholding of Information",
        "date": "2026-06-23"
      }
    ]
  },
  "penny-simmonds": {
    "count": 180,
    "recent": [
      {
        "title": "Bills — Social Security (Modernisation) Amendment Bill",
        "date": "2026-05-28"
      },
      {
        "title": "Bills — Appropriation (2024/25 Confirmation and Validation) Bill",
        "date": "2026-04-21"
      },
      {
        "title": "Bills — Appropriation (2024/25 Confirmation and Validation) Bill",
        "date": "2026-04-21"
      },
      {
        "title": "Bills — Appropriation (2024/25 Confirmation and Validation) Bill",
        "date": "2026-04-21"
      },
      {
        "title": "Personal Explanations — Question No. 7 to Minister, 26 March",
        "date": "2026-03-31"
      }
    ]
  },
  "judith-collins": {
    "count": 76,
    "recent": [
      {
        "title": "Valedictory Statements — Hon Judith Collins",
        "date": "2026-05-12"
      },
      {
        "title": "Debates — Iranian Attacks—Collective Statement",
        "date": "2026-03-24"
      },
      {
        "title": "Bills — Public Service Amendment Bill",
        "date": "2026-03-10"
      },
      {
        "title": "Bills — Public Service Amendment Bill",
        "date": "2026-03-10"
      },
      {
        "title": "Bills — Public Service Amendment Bill",
        "date": "2026-03-10"
      }
    ]
  },
  "mark-cameron": {
    "count": 57,
    "recent": [
      {
        "title": "General Debate",
        "date": "2025-10-15"
      },
      {
        "title": "Ministerial Statements — Middle East—Palestine",
        "date": "2025-10-07"
      },
      {
        "title": "Bills — Land Transport (Clean Vehicle Standard) Amendment Bill (No 2)",
        "date": "2025-08-21"
      },
      {
        "title": "Bills — Climate Change Response (Emissions Trading Scheme—Forestry Conversion) Amendment Bill",
        "date": "2025-08-19"
      },
      {
        "title": "Bills — Outer Space and High-altitude Activities Amendment Bill",
        "date": "2025-07-22"
      }
    ]
  },
  "andrew-bayly": {
    "count": 78,
    "recent": [
      {
        "title": "Bills — Victims of Sexual Violence (Strengthening Legal Protections) Legislation Bill",
        "date": "2025-06-24"
      },
      {
        "title": "Bills — Juries (Age of Excusal) Amendment Bill",
        "date": "2025-04-09"
      },
      {
        "title": "Bills — Companies (Address Information) Amendment Bill",
        "date": "2025-02-19"
      },
      {
        "title": "Bills — Customer and Product Data Bill",
        "date": "2025-02-18"
      },
      {
        "title": "Appointments — Chief Ombudsman",
        "date": "2025-01-30"
      }
    ]
  }
}

// Every MP checked by this run. The sweep covers the whole term, so an MP listed
// here but absent from the map above genuinely gave no speeches — a real, checked
// zero, not "not looked at yet".
export const SPEECHES_CHECKED: string[] = [
  "andrew-bayly",
  "andrew-hoggard",
  "andy-foster",
  "arena-williams",
  "ayesha-verrall",
  "barbara-edmonds",
  "barbara-kuriger",
  "brooke-van-velden",
  "cameron-brewer",
  "cameron-luxton",
  "camilla-belich",
  "carl-bates",
  "carlos-cheung",
  "carmel-sepuloni",
  "casey-costello",
  "catherine-wedd",
  "celia-wade-brown",
  "chle-swarbrick",
  "chris-bishop",
  "chris-hipkins",
  "chris-penk",
  "christopher-luxon",
  "cushla-tangaere-manuel",
  "damien-oconnor",
  "dan-bidois",
  "dan-rosewarne",
  "dana-kirkpatrick",
  "david-macleod",
  "david-seymour",
  "david-wilson",
  "debbie-ngarewa-packer",
  "deborah-russell",
  "duncan-webb",
  "erica-stanford",
  "francisco-hernandez",
  "georgie-dansey",
  "gerry-brownlee",
  "ginny-andersen",
  "glen-bennett",
  "grant-mccallum",
  "greg-fleming",
  "greg-oconnor",
  "hamish-campbell",
  "hana-rawhiti-maipi-clarke",
  "helen-white",
  "huhana-lyndon",
  "ingrid-leary",
  "james-meager",
  "jamie-arbuckle",
  "jan-tinetti",
  "jenny-marcroft",
  "jenny-salesa",
  "jo-luxton",
  "joseph-mooney",
  "judith-collins",
  "julie-anne-genter",
  "kahurangi-carter",
  "karen-chhour",
  "katie-nimon",
  "kieran-mcanulty",
  "lan-pham",
  "laura-mcclure",
  "lawrence-xu-nan",
  "lemauga-lydia-sosene",
  "louise-upston",
  "marama-davidson",
  "mariameno-kapa-kingi",
  "mark-cameron",
  "mark-mitchell",
  "mark-patterson",
  "matt-doocey",
  "maureen-pugh",
  "megan-woods",
  "melissa-lee",
  "mike-butterick",
  "mike-davidson",
  "mike-davidson",
  "miles-anderson",
  "nancy-lu",
  "nicola-grigg",
  "nicola-willis",
  "nicole-mckee",
  "oriini-kaipara",
  "oriini-kaipara",
  "parmjeet-parmar",
  "paul-goldsmith",
  "paulo-garcia",
  "penny-simmonds",
  "phil-twyford",
  "priyanca-radhakrishnan",
  "rachel-boyack",
  "rachel-brooking",
  "rawiri-waititi",
  "reuben-davidson",
  "ricardo-menendez-march",
  "rima-nakhle",
  "ryan-hamilton",
  "sam-uffindell",
  "scott-simpson",
  "scott-willis",
  "shanan-halbert",
  "shane-jones",
  "shane-reti",
  "simeon-brown",
  "simon-court",
  "simon-watts",
  "steve-abel",
  "stuart-smith",
  "suze-redmayne",
  "takuta-ferris",
  "tama-potaka",
  "tamatha-paul",
  "tangi-utikere",
  "teanau-tuiono",
  "tim-costley",
  "tim-van-de-molen",
  "todd-mcclay",
  "todd-stephenson",
  "tom-rutherford",
  "tracey-mclellan",
  "vanessa-weenink",
  "vanushi-walters",
  "willie-jackson",
  "willow-jean-prime",
  "winston-peters"
]
