// AUTO-GENERATED by scripts/build-mp-written-questions.mjs. Do not edit by hand.
// Per-MP written parliamentary questions asked in the 54th Parliament term (since the
// 2023 election), from questions.parliament.nz's public search API — the same shared
// platform as bills.parliament.nz's official bills API. Counts are exact matches on the
// asking MP's name in the question title, restricted to this term; nothing invented.

export interface WrittenQuestion { title: string; date: string; minister: string }
export interface MPWrittenQuestions { count: number; recent: WrittenQuestion[] }
export const WRITTEN_QUESTIONS_META = {
  term: 54,
  sourceUrl: 'https://questions.parliament.nz/',
  sourceLabel: "Written Parliamentary Questions (questions.parliament.nz)",
}
export const MP_WRITTEN_QUESTIONS: Record<string, MPWrittenQuestions> = {
  "oriini-kaipara": {
    "count": 51,
    "recent": [
      {
        "title": "Oriini Kaipara to the Minister for Social Development and Employment",
        "date": "2026-04-22",
        "minister": "Minister for Social Development and Employment"
      },
      {
        "title": "Oriini Kaipara to the Minister for Social Development and Employment",
        "date": "2026-04-22",
        "minister": "Minister for Social Development and Employment"
      },
      {
        "title": "Oriini Kaipara to the Minister of Housing",
        "date": "2026-04-21",
        "minister": "Minister of Housing"
      },
      {
        "title": "Oriini Kaipara to the Minister of Housing",
        "date": "2026-04-21",
        "minister": "Minister of Housing"
      },
      {
        "title": "Oriini Kaipara to the Minister of Housing",
        "date": "2026-04-21",
        "minister": "Minister of Housing"
      }
    ]
  },
  "mike-davidson": {
    "count": 154,
    "recent": [
      {
        "title": "Mike Davidson to the Minister of Internal Affairs",
        "date": "2026-07-02",
        "minister": "Minister of Internal Affairs"
      },
      {
        "title": "Mike Davidson to the Minister of Internal Affairs",
        "date": "2026-07-02",
        "minister": "Minister of Internal Affairs"
      },
      {
        "title": "Mike Davidson to the Minister of Internal Affairs",
        "date": "2026-07-02",
        "minister": "Minister of Internal Affairs"
      },
      {
        "title": "Mike Davidson to the Minister of Internal Affairs",
        "date": "2026-07-02",
        "minister": "Minister of Internal Affairs"
      },
      {
        "title": "Mike Davidson to the Minister of Internal Affairs",
        "date": "2026-07-02",
        "minister": "Minister of Internal Affairs"
      }
    ]
  },
  "steve-abel": {
    "count": 629,
    "recent": [
      {
        "title": "Steve Abel to the Minister for Resources",
        "date": "2026-07-01",
        "minister": "Minister for Resources"
      },
      {
        "title": "Steve Abel to the Minister for Resources",
        "date": "2026-06-15",
        "minister": "Minister for Resources"
      },
      {
        "title": "Steve Abel to the Minister of Foreign Affairs",
        "date": "2026-06-15",
        "minister": "Minister of Foreign Affairs"
      },
      {
        "title": "Steve Abel to the Minister for Resources",
        "date": "2026-06-15",
        "minister": "Minister for Resources"
      },
      {
        "title": "Steve Abel to the Minister of Foreign Affairs",
        "date": "2026-06-15",
        "minister": "Minister of Foreign Affairs"
      }
    ]
  },
  "ginny-andersen": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Ginny Andersen to the Minister of Police",
        "date": "2026-07-06",
        "minister": "Minister of Police"
      },
      {
        "title": "Hon Ginny Andersen to the Minister of Police",
        "date": "2026-07-06",
        "minister": "Minister of Police"
      },
      {
        "title": "Hon Ginny Andersen to the Minister of Education",
        "date": "2026-07-06",
        "minister": "Minister of Education"
      },
      {
        "title": "Hon Ginny Andersen to the Minister of Police",
        "date": "2026-07-06",
        "minister": "Minister of Police"
      },
      {
        "title": "Hon Ginny Andersen to the Minister of Police",
        "date": "2026-07-06",
        "minister": "Minister of Police"
      }
    ]
  },
  "camilla-belich": {
    "count": 2000,
    "recent": [
      {
        "title": "Camilla Belich to the Associate Minister of Justice",
        "date": "2026-07-06",
        "minister": "Associate Minister of Justice"
      },
      {
        "title": "Camilla Belich to the Minister of Justice",
        "date": "2026-07-06",
        "minister": "Minister of Justice"
      },
      {
        "title": "Camilla Belich to the Minister of Justice",
        "date": "2026-07-06",
        "minister": "Minister of Justice"
      },
      {
        "title": "Camilla Belich to the Associate Minister of Justice",
        "date": "2026-07-06",
        "minister": "Associate Minister of Justice"
      },
      {
        "title": "Camilla Belich to the Associate Minister of Justice",
        "date": "2026-07-06",
        "minister": "Associate Minister of Justice"
      }
    ]
  },
  "glen-bennett": {
    "count": 419,
    "recent": [
      {
        "title": "Glen Bennett to the Minister for Tourism and Hospitality",
        "date": "2026-07-06",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Glen Bennett to the Minister for Tourism and Hospitality",
        "date": "2026-07-06",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Glen Bennett to the Minister for Tourism and Hospitality",
        "date": "2026-06-29",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Glen Bennett to the Minister for Tourism and Hospitality",
        "date": "2026-06-29",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Glen Bennett to the Minister for Tourism and Hospitality",
        "date": "2026-06-22",
        "minister": "Minister for Tourism and Hospitality"
      }
    ]
  },
  "rachel-boyack": {
    "count": 1294,
    "recent": [
      {
        "title": "Rachel Boyack to the Minister for Oceans and Fisheries",
        "date": "2026-07-06",
        "minister": "Minister for Oceans and Fisheries"
      },
      {
        "title": "Rachel Boyack to the Minister for Oceans and Fisheries",
        "date": "2026-07-06",
        "minister": "Minister for Oceans and Fisheries"
      },
      {
        "title": "Rachel Boyack to the Minister for Arts, Culture and Heritage",
        "date": "2026-07-06",
        "minister": "Minister for Arts, Culture and Heritage"
      },
      {
        "title": "Rachel Boyack to the Minister for Arts, Culture and Heritage",
        "date": "2026-07-06",
        "minister": "Minister for Arts, Culture and Heritage"
      },
      {
        "title": "Rachel Boyack to the Minister for Arts, Culture and Heritage",
        "date": "2026-06-29",
        "minister": "Minister for Arts, Culture and Heritage"
      }
    ]
  },
  "rachel-brooking": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Rachel Brooking to the Minister for Space",
        "date": "2026-07-06",
        "minister": "Minister for Space"
      },
      {
        "title": "Hon Rachel Brooking to the Minister for Space",
        "date": "2026-07-06",
        "minister": "Minister for Space"
      },
      {
        "title": "Hon Rachel Brooking to the Minister for the Environment",
        "date": "2026-07-06",
        "minister": "Minister for the Environment"
      },
      {
        "title": "Hon Rachel Brooking to the Minister responsible for RMA Reform",
        "date": "2026-07-06",
        "minister": "Minister responsible for RMA Reform"
      },
      {
        "title": "Hon Rachel Brooking to the Minister for the Environment",
        "date": "2026-07-06",
        "minister": "Minister for the Environment"
      }
    ]
  },
  "kahurangi-carter": {
    "count": 239,
    "recent": [
      {
        "title": "Kahurangi Carter to the Minister for Children",
        "date": "2026-06-29",
        "minister": "Minister for Children"
      },
      {
        "title": "Kahurangi Carter to the Minister for Women",
        "date": "2026-06-23",
        "minister": "Minister for Women"
      },
      {
        "title": "Kahurangi Carter to the Minister for Children",
        "date": "2026-06-23",
        "minister": "Minister for Children"
      },
      {
        "title": "Kahurangi Carter to the Minister for the Environment",
        "date": "2026-06-23",
        "minister": "Minister for the Environment"
      },
      {
        "title": "Kahurangi Carter to the Minister for Women",
        "date": "2026-06-23",
        "minister": "Minister for Women"
      }
    ]
  },
  "georgie-dansey": {
    "count": 49,
    "recent": [
      {
        "title": "Georgie Dansey to the Minister for Regulation",
        "date": "2026-07-06",
        "minister": "Minister for Regulation"
      },
      {
        "title": "Georgie Dansey to the Minister for Regulation",
        "date": "2026-07-06",
        "minister": "Minister for Regulation"
      },
      {
        "title": "Georgie Dansey to the Minister for Regulation",
        "date": "2026-06-29",
        "minister": "Minister for Regulation"
      },
      {
        "title": "Georgie Dansey to the Minister for Regulation",
        "date": "2026-06-29",
        "minister": "Minister for Regulation"
      },
      {
        "title": "Georgie Dansey to the Minister for Regulation",
        "date": "2026-06-22",
        "minister": "Minister for Regulation"
      }
    ]
  },
  "marama-davidson": {
    "count": 256,
    "recent": [
      {
        "title": "Hon Marama Davidson to the Minister of Conservation",
        "date": "2026-07-01",
        "minister": "Minister of Conservation"
      },
      {
        "title": "Hon Marama Davidson to the Minister of Conservation",
        "date": "2026-07-01",
        "minister": "Minister of Conservation"
      },
      {
        "title": "Hon Marama Davidson to the Minister of Conservation",
        "date": "2026-07-01",
        "minister": "Minister of Conservation"
      },
      {
        "title": "Hon Marama Davidson to the Minister for Oceans and Fisheries",
        "date": "2026-07-01",
        "minister": "Minister for Oceans and Fisheries"
      },
      {
        "title": "Hon Marama Davidson to the Minister for Oceans and Fisheries",
        "date": "2026-07-01",
        "minister": "Minister for Oceans and Fisheries"
      }
    ]
  },
  "reuben-davidson": {
    "count": 1258,
    "recent": [
      {
        "title": "Reuben Davidson to the Minister for Economic Growth",
        "date": "2026-07-06",
        "minister": "Minister for Economic Growth"
      },
      {
        "title": "Reuben Davidson to the Minister for Economic Growth",
        "date": "2026-07-06",
        "minister": "Minister for Economic Growth"
      },
      {
        "title": "Reuben Davidson to the Minister for Media and Communications",
        "date": "2026-07-06",
        "minister": "Minister for Media and Communications"
      },
      {
        "title": "Reuben Davidson to the Minister for Science, Innovation and Technology",
        "date": "2026-07-06",
        "minister": "Minister for Science, Innovation and Technology"
      },
      {
        "title": "Reuben Davidson to the Minister for Media and Communications",
        "date": "2026-07-06",
        "minister": "Minister for Media and Communications"
      }
    ]
  },
  "barbara-edmonds": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Barbara Edmonds to the Minister of Finance",
        "date": "2026-07-06",
        "minister": "Minister of Finance"
      },
      {
        "title": "Hon Barbara Edmonds to the Minister of Finance",
        "date": "2026-07-06",
        "minister": "Minister of Finance"
      },
      {
        "title": "Hon Barbara Edmonds to the Associate Minister of Finance",
        "date": "2026-07-06",
        "minister": "Associate Minister of Finance"
      },
      {
        "title": "Hon Barbara Edmonds to the Associate Minister of Finance",
        "date": "2026-07-06",
        "minister": "Associate Minister of Finance"
      },
      {
        "title": "Hon Barbara Edmonds to the Associate Minister of Finance",
        "date": "2026-07-06",
        "minister": "Associate Minister of Finance"
      }
    ]
  },
  "takuta-ferris": {
    "count": 12,
    "recent": [
      {
        "title": "Tākuta Ferris to the Minister of Health",
        "date": "2026-04-13",
        "minister": "Minister of Health"
      },
      {
        "title": "Tākuta Ferris to the Minister of Health",
        "date": "2026-04-10",
        "minister": "Minister of Health"
      },
      {
        "title": "Tākuta Ferris to the Minister of Health",
        "date": "2026-04-10",
        "minister": "Minister of Health"
      },
      {
        "title": "Tākuta Ferris to the Minister of Health",
        "date": "2026-04-10",
        "minister": "Minister of Health"
      },
      {
        "title": "Tākuta Ferris to the Minister of Health",
        "date": "2026-04-10",
        "minister": "Minister of Health"
      }
    ]
  },
  "julie-anne-genter": {
    "count": 461,
    "recent": [
      {
        "title": "Hon Julie Anne Genter to the Minister of Transport",
        "date": "2026-06-16",
        "minister": "Minister of Transport"
      },
      {
        "title": "Hon Julie Anne Genter to the Minister of Transport",
        "date": "2026-06-16",
        "minister": "Minister of Transport"
      },
      {
        "title": "Hon Julie Anne Genter to the Minister of Transport",
        "date": "2026-06-05",
        "minister": "Minister of Transport"
      },
      {
        "title": "Hon Julie Anne Genter to the Minister of Transport",
        "date": "2026-06-05",
        "minister": "Minister of Transport"
      },
      {
        "title": "Hon Julie Anne Genter to the Minister of Transport",
        "date": "2026-06-05",
        "minister": "Minister of Transport"
      }
    ]
  },
  "shanan-halbert": {
    "count": 1448,
    "recent": [
      {
        "title": "Shanan Halbert to the Minister for Whānau Ora",
        "date": "2026-07-06",
        "minister": "Minister for Whānau Ora"
      },
      {
        "title": "Shanan Halbert to the Minister for Whānau Ora",
        "date": "2026-07-06",
        "minister": "Minister for Whānau Ora"
      },
      {
        "title": "Shanan Halbert to the Minister for Tertiary Education",
        "date": "2026-07-06",
        "minister": "Minister for Tertiary Education"
      },
      {
        "title": "Shanan Halbert to the Minister for Tertiary Education",
        "date": "2026-07-06",
        "minister": "Minister for Tertiary Education"
      },
      {
        "title": "Shanan Halbert to the Minister for Tertiary Education",
        "date": "2026-06-29",
        "minister": "Minister for Tertiary Education"
      }
    ]
  },
  "francisco-hernandez": {
    "count": 2000,
    "recent": [
      {
        "title": "Francisco Hernandez to the Minister of Statistics",
        "date": "2026-07-06",
        "minister": "Minister of Statistics"
      },
      {
        "title": "Francisco Hernandez to the Minister of Education",
        "date": "2026-07-06",
        "minister": "Minister of Education"
      },
      {
        "title": "Francisco Hernandez to the Minister of Climate Change",
        "date": "2026-07-06",
        "minister": "Minister of Climate Change"
      },
      {
        "title": "Francisco Hernandez to the Minister for Regulation",
        "date": "2026-07-06",
        "minister": "Minister for Regulation"
      },
      {
        "title": "Francisco Hernandez to the Minister of Customs",
        "date": "2026-07-06",
        "minister": "Minister of Customs"
      }
    ]
  },
  "chris-hipkins": {
    "count": 1997,
    "recent": [
      {
        "title": "Rt Hon Chris Hipkins to the Prime Minister",
        "date": "2026-07-06",
        "minister": "Prime Minister"
      },
      {
        "title": "Rt Hon Chris Hipkins to the Prime Minister",
        "date": "2026-07-06",
        "minister": "Prime Minister"
      },
      {
        "title": "Rt Hon Chris Hipkins to the Prime Minister",
        "date": "2026-07-06",
        "minister": "Prime Minister"
      },
      {
        "title": "Rt Hon Chris Hipkins to the Prime Minister",
        "date": "2026-07-06",
        "minister": "Prime Minister"
      },
      {
        "title": "Rt Hon Chris Hipkins to the Prime Minister",
        "date": "2026-07-06",
        "minister": "Prime Minister"
      }
    ]
  },
  "willie-jackson": {
    "count": 1126,
    "recent": [
      {
        "title": "Hon Willie Jackson to the Minister for Māori Development",
        "date": "2026-07-06",
        "minister": "Minister for Māori Development"
      },
      {
        "title": "Hon Willie Jackson to the Minister for Māori Crown Relations: Te Arawhiti",
        "date": "2026-07-06",
        "minister": "Minister for Māori Crown Relations: Te Arawhiti"
      },
      {
        "title": "Hon Willie Jackson to the Minister for Māori Crown Relations: Te Arawhiti",
        "date": "2026-07-06",
        "minister": "Minister for Māori Crown Relations: Te Arawhiti"
      },
      {
        "title": "Hon Willie Jackson to the Minister for Māori Development",
        "date": "2026-07-06",
        "minister": "Minister for Māori Development"
      },
      {
        "title": "Hon Willie Jackson to the Minister for Māori Development",
        "date": "2026-07-06",
        "minister": "Minister for Māori Development"
      }
    ]
  },
  "mariameno-kapa-kingi": {
    "count": 15,
    "recent": [
      {
        "title": "Mariameno Kapa-Kingi to the Minister for Social Development and Employment",
        "date": "2025-05-23",
        "minister": "Minister for Social Development and Employment"
      },
      {
        "title": "Mariameno Kapa-Kingi to the Minister for Social Development and Employment",
        "date": "2025-05-23",
        "minister": "Minister for Social Development and Employment"
      },
      {
        "title": "Mariameno Kapa-Kingi to the Minister for Social Development and Employment",
        "date": "2025-05-23",
        "minister": "Minister for Social Development and Employment"
      },
      {
        "title": "Mariameno Kapa-Kingi to the Minister for Social Development and Employment",
        "date": "2025-05-23",
        "minister": "Minister for Social Development and Employment"
      },
      {
        "title": "Mariameno Kapa-Kingi to the Minister for Social Development and Employment",
        "date": "2025-05-23",
        "minister": "Minister for Social Development and Employment"
      }
    ]
  },
  "ingrid-leary": {
    "count": 2000,
    "recent": [
      {
        "title": "Ingrid Leary to the Minister for Seniors",
        "date": "2026-07-06",
        "minister": "Minister for Seniors"
      },
      {
        "title": "Ingrid Leary to the Minister for Mental Health",
        "date": "2026-07-06",
        "minister": "Minister for Mental Health"
      },
      {
        "title": "Ingrid Leary to the Minister for Mental Health",
        "date": "2026-07-06",
        "minister": "Minister for Mental Health"
      },
      {
        "title": "Ingrid Leary to the Minister for Seniors",
        "date": "2026-07-06",
        "minister": "Minister for Seniors"
      },
      {
        "title": "Ingrid Leary to the Minister for Mental Health",
        "date": "2026-07-01",
        "minister": "Minister for Mental Health"
      }
    ]
  },
  "jo-luxton": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Jo Luxton to the Minister of Customs",
        "date": "2026-07-06",
        "minister": "Minister of Customs"
      },
      {
        "title": "Hon Jo Luxton to the Minister of Agriculture",
        "date": "2026-07-06",
        "minister": "Minister of Agriculture"
      },
      {
        "title": "Hon Jo Luxton to the Minister of Customs",
        "date": "2026-07-06",
        "minister": "Minister of Customs"
      },
      {
        "title": "Hon Jo Luxton to the Minister of Agriculture",
        "date": "2026-07-06",
        "minister": "Minister of Agriculture"
      },
      {
        "title": "Hon Jo Luxton to the Minister for Biosecurity",
        "date": "2026-07-06",
        "minister": "Minister for Biosecurity"
      }
    ]
  },
  "huhana-lyndon": {
    "count": 335,
    "recent": [
      {
        "title": "Hūhana Lyndon to the Minister of Local Government",
        "date": "2026-06-11",
        "minister": "Minister of Local Government"
      },
      {
        "title": "Hūhana Lyndon to the Minister of Health",
        "date": "2026-06-11",
        "minister": "Minister of Health"
      },
      {
        "title": "Hūhana Lyndon to the Minister of Health",
        "date": "2026-06-11",
        "minister": "Minister of Health"
      },
      {
        "title": "Hūhana Lyndon to the Minister of Health",
        "date": "2026-06-11",
        "minister": "Minister of Health"
      },
      {
        "title": "Hūhana Lyndon to the Minister of Health",
        "date": "2026-06-11",
        "minister": "Minister of Health"
      }
    ]
  },
  "kieran-mcanulty": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Kieran McAnulty to the Minister for Infrastructure",
        "date": "2026-07-06",
        "minister": "Minister for Infrastructure"
      },
      {
        "title": "Hon Kieran McAnulty to the Minister of Housing",
        "date": "2026-07-06",
        "minister": "Minister of Housing"
      },
      {
        "title": "Hon Kieran McAnulty to the Minister of Housing",
        "date": "2026-07-06",
        "minister": "Minister of Housing"
      },
      {
        "title": "Hon Kieran McAnulty to the Minister for Infrastructure",
        "date": "2026-07-06",
        "minister": "Minister for Infrastructure"
      },
      {
        "title": "Hon Kieran McAnulty to the Associate Minister of Housing",
        "date": "2026-07-06",
        "minister": "Associate Minister of Housing"
      }
    ]
  },
  "ricardo-menendez-march": {
    "count": 1245,
    "recent": [
      {
        "title": "Ricardo Menéndez March to the Minister for Child Poverty Reduction",
        "date": "2026-07-03",
        "minister": "Minister for Child Poverty Reduction"
      },
      {
        "title": "Ricardo Menéndez March to the Minister for Child Poverty Reduction",
        "date": "2026-07-03",
        "minister": "Minister for Child Poverty Reduction"
      },
      {
        "title": "Ricardo Menéndez March to the Associate Minister of Education",
        "date": "2026-07-02",
        "minister": "Associate Minister of Education"
      },
      {
        "title": "Ricardo Menéndez March to the Associate Minister of Education",
        "date": "2026-07-02",
        "minister": "Associate Minister of Education"
      },
      {
        "title": "Ricardo Menéndez March to the Minister for Social Development and Employment",
        "date": "2026-07-01",
        "minister": "Minister for Social Development and Employment"
      }
    ]
  },
  "debbie-ngarewa-packer": {
    "count": 1053,
    "recent": [
      {
        "title": "Debbie Ngarewa-Packer to the Minister of Transport",
        "date": "2026-06-23",
        "minister": "Minister of Transport"
      },
      {
        "title": "Debbie Ngarewa-Packer to the Minister for Energy",
        "date": "2026-06-23",
        "minister": "Minister for Energy"
      },
      {
        "title": "Debbie Ngarewa-Packer to the Minister of Transport",
        "date": "2026-06-23",
        "minister": "Minister of Transport"
      },
      {
        "title": "Debbie Ngarewa-Packer to the Minister of Transport",
        "date": "2026-06-23",
        "minister": "Minister of Transport"
      },
      {
        "title": "Debbie Ngarewa-Packer to the Minister of Transport",
        "date": "2026-06-23",
        "minister": "Minister of Transport"
      }
    ]
  },
  "tamatha-paul": {
    "count": 1030,
    "recent": [
      {
        "title": "Tamatha Paul to the Minister for Tourism and Hospitality",
        "date": "2026-06-05",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Tamatha Paul to the Minister for Tourism and Hospitality",
        "date": "2026-06-05",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Tamatha Paul to the Minister for Tourism and Hospitality",
        "date": "2026-06-05",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Tamatha Paul to the Minister for Tourism and Hospitality",
        "date": "2026-06-04",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Tamatha Paul to the Minister for Tourism and Hospitality",
        "date": "2026-06-02",
        "minister": "Minister for Tourism and Hospitality"
      }
    ]
  },
  "lan-pham": {
    "count": 1643,
    "recent": [
      {
        "title": "Lan Pham to the Minister of Education",
        "date": "2026-06-26",
        "minister": "Minister of Education"
      },
      {
        "title": "Lan Pham to the Minister of Education",
        "date": "2026-06-26",
        "minister": "Minister of Education"
      },
      {
        "title": "Lan Pham to the Associate Minister for the Environment",
        "date": "2026-06-26",
        "minister": "Associate Minister for the Environment"
      },
      {
        "title": "Lan Pham to the Associate Minister for the Environment",
        "date": "2026-06-26",
        "minister": "Associate Minister for the Environment"
      },
      {
        "title": "Lan Pham to the Associate Minister for the Environment",
        "date": "2026-06-26",
        "minister": "Associate Minister for the Environment"
      }
    ]
  },
  "willow-jean-prime": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Willow-Jean Prime to the Associate Minister for Social Development and Employment",
        "date": "2026-07-06",
        "minister": "Associate Minister for Social Development and Employment"
      },
      {
        "title": "Hon Willow-Jean Prime to the Associate Minister for Social Development and Employment",
        "date": "2026-07-06",
        "minister": "Associate Minister for Social Development and Employment"
      },
      {
        "title": "Hon Willow-Jean Prime to the Minister for Children",
        "date": "2026-07-06",
        "minister": "Minister for Children"
      },
      {
        "title": "Hon Willow-Jean Prime to the Minister for Children",
        "date": "2026-07-06",
        "minister": "Minister for Children"
      },
      {
        "title": "Hon Willow-Jean Prime to the Minister for Social Development and Employment",
        "date": "2026-07-06",
        "minister": "Minister for Social Development and Employment"
      }
    ]
  },
  "priyanca-radhakrishnan": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Priyanca Radhakrishnan to the Minister of Conservation",
        "date": "2026-07-06",
        "minister": "Minister of Conservation"
      },
      {
        "title": "Hon Priyanca Radhakrishnan to the Minister for ACC",
        "date": "2026-07-06",
        "minister": "Minister for ACC"
      },
      {
        "title": "Hon Priyanca Radhakrishnan to the Minister of Conservation",
        "date": "2026-07-06",
        "minister": "Minister of Conservation"
      },
      {
        "title": "Hon Priyanca Radhakrishnan to the Minister for ACC",
        "date": "2026-07-06",
        "minister": "Minister for ACC"
      },
      {
        "title": "Hon Priyanca Radhakrishnan to the Minister for Disability Issues",
        "date": "2026-07-06",
        "minister": "Minister for Disability Issues"
      }
    ]
  },
  "dan-rosewarne": {
    "count": 144,
    "recent": [
      {
        "title": "Dan Rosewarne to the Minister for Rural Communities",
        "date": "2026-07-06",
        "minister": "Minister for Rural Communities"
      },
      {
        "title": "Dan Rosewarne to the Minister for Rural Communities",
        "date": "2026-07-06",
        "minister": "Minister for Rural Communities"
      },
      {
        "title": "Dan Rosewarne to the Minister for the South Island",
        "date": "2026-07-06",
        "minister": "Minister for the South Island"
      },
      {
        "title": "Dan Rosewarne to the Minister for Small Business and Manufacturing",
        "date": "2026-07-06",
        "minister": "Minister for Small Business and Manufacturing"
      },
      {
        "title": "Dan Rosewarne to the Minister for the South Island",
        "date": "2026-07-06",
        "minister": "Minister for the South Island"
      }
    ]
  },
  "jenny-salesa": {
    "count": 977,
    "recent": [
      {
        "title": "Hon Jenny Salesa to the Minister for Ethnic Communities",
        "date": "2026-07-06",
        "minister": "Minister for Ethnic Communities"
      },
      {
        "title": "Hon Jenny Salesa to the Minister for Ethnic Communities",
        "date": "2026-07-06",
        "minister": "Minister for Ethnic Communities"
      },
      {
        "title": "Hon Jenny Salesa to the Minister for Ethnic Communities",
        "date": "2026-06-29",
        "minister": "Minister for Ethnic Communities"
      },
      {
        "title": "Hon Jenny Salesa to the Minister for Ethnic Communities",
        "date": "2026-06-29",
        "minister": "Minister for Ethnic Communities"
      },
      {
        "title": "Hon Jenny Salesa to the Minister for Ethnic Communities",
        "date": "2026-06-22",
        "minister": "Minister for Ethnic Communities"
      }
    ]
  },
  "carmel-sepuloni": {
    "count": 1999,
    "recent": [
      {
        "title": "Hon Carmel Sepuloni to the Minister for Auckland",
        "date": "2026-07-06",
        "minister": "Minister for Auckland"
      },
      {
        "title": "Hon Carmel Sepuloni to the Minister for Auckland",
        "date": "2026-07-06",
        "minister": "Minister for Auckland"
      },
      {
        "title": "Hon Carmel Sepuloni to the Minister for Women",
        "date": "2026-07-06",
        "minister": "Minister for Women"
      },
      {
        "title": "Hon Carmel Sepuloni to the Minister for Women",
        "date": "2026-07-06",
        "minister": "Minister for Women"
      },
      {
        "title": "Hon Carmel Sepuloni to the Minister for Pacific Peoples",
        "date": "2026-07-06",
        "minister": "Minister for Pacific Peoples"
      }
    ]
  },
  "lemauga-lydia-sosene": {
    "count": 1647,
    "recent": [
      {
        "title": "Lemauga Lydia Sosene to the Minister of Statistics",
        "date": "2026-07-06",
        "minister": "Minister of Statistics"
      },
      {
        "title": "Lemauga Lydia Sosene to the Minister of Statistics",
        "date": "2026-07-06",
        "minister": "Minister of Statistics"
      },
      {
        "title": "Lemauga Lydia Sosene to the Minister of Internal Affairs",
        "date": "2026-07-06",
        "minister": "Minister of Internal Affairs"
      },
      {
        "title": "Lemauga Lydia Sosene to the Minister of Internal Affairs",
        "date": "2026-07-06",
        "minister": "Minister of Internal Affairs"
      },
      {
        "title": "Lemauga Lydia Sosene to the Minister of Statistics",
        "date": "2026-06-29",
        "minister": "Minister of Statistics"
      }
    ]
  },
  "chle-swarbrick": {
    "count": 1325,
    "recent": [
      {
        "title": "Chlöe Swarbrick to the Minister of Conservation",
        "date": "2026-06-25",
        "minister": "Minister of Conservation"
      },
      {
        "title": "Chlöe Swarbrick to the Minister of Conservation",
        "date": "2026-06-25",
        "minister": "Minister of Conservation"
      },
      {
        "title": "Chlöe Swarbrick to the Prime Minister",
        "date": "2026-06-03",
        "minister": "Prime Minister"
      },
      {
        "title": "Chlöe Swarbrick to the Prime Minister",
        "date": "2026-06-03",
        "minister": "Prime Minister"
      },
      {
        "title": "Chlöe Swarbrick to the Prime Minister",
        "date": "2026-06-03",
        "minister": "Prime Minister"
      }
    ]
  },
  "cushla-tangaere-manuel": {
    "count": 1106,
    "recent": [
      {
        "title": "Cushla Tangaere-Manuel to the Minister of Forestry",
        "date": "2026-07-06",
        "minister": "Minister of Forestry"
      },
      {
        "title": "Cushla Tangaere-Manuel to the Minister of Forestry",
        "date": "2026-07-06",
        "minister": "Minister of Forestry"
      },
      {
        "title": "Cushla Tangaere-Manuel to the Minister for Emergency Management and Recovery",
        "date": "2026-07-06",
        "minister": "Minister for Emergency Management and Recovery"
      },
      {
        "title": "Cushla Tangaere-Manuel to the Associate Minister for Emergency Management and Recovery",
        "date": "2026-07-06",
        "minister": "Associate Minister for Emergency Management and Recovery"
      },
      {
        "title": "Cushla Tangaere-Manuel to the Minister for Sport and Recreation",
        "date": "2026-07-06",
        "minister": "Minister for Sport and Recreation"
      }
    ]
  },
  "jan-tinetti": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Jan Tinetti to the Minister for Workplace Relations and Safety",
        "date": "2026-07-06",
        "minister": "Minister for Workplace Relations and Safety"
      },
      {
        "title": "Hon Jan Tinetti to the Minister for Child Poverty Reduction",
        "date": "2026-07-06",
        "minister": "Minister for Child Poverty Reduction"
      },
      {
        "title": "Hon Jan Tinetti to the Minister for Social Investment",
        "date": "2026-07-06",
        "minister": "Minister for Social Investment"
      },
      {
        "title": "Hon Jan Tinetti to the Minister for Social Investment",
        "date": "2026-07-06",
        "minister": "Minister for Social Investment"
      },
      {
        "title": "Hon Jan Tinetti to the Minister for Workplace Relations and Safety",
        "date": "2026-07-06",
        "minister": "Minister for Workplace Relations and Safety"
      }
    ]
  },
  "teanau-tuiono": {
    "count": 2000,
    "recent": [
      {
        "title": "Teanau Tuiono to the Minister of Immigration",
        "date": "2026-07-06",
        "minister": "Minister of Immigration"
      },
      {
        "title": "Teanau Tuiono to the Minister of Internal Affairs",
        "date": "2026-07-06",
        "minister": "Minister of Internal Affairs"
      },
      {
        "title": "Teanau Tuiono to the Minister for Pacific Peoples",
        "date": "2026-07-06",
        "minister": "Minister for Pacific Peoples"
      },
      {
        "title": "Teanau Tuiono to the Minister of Defence",
        "date": "2026-07-03",
        "minister": "Minister of Defence"
      },
      {
        "title": "Teanau Tuiono to the Minister of Defence",
        "date": "2026-07-03",
        "minister": "Minister of Defence"
      }
    ]
  },
  "phil-twyford": {
    "count": 2000,
    "recent": [
      {
        "title": "Hon Phil Twyford to the Minister of Immigration",
        "date": "2026-07-06",
        "minister": "Minister of Immigration"
      },
      {
        "title": "Hon Phil Twyford to the Minister of Immigration",
        "date": "2026-07-06",
        "minister": "Minister of Immigration"
      },
      {
        "title": "Hon Phil Twyford to the Associate Minister of Immigration",
        "date": "2026-07-06",
        "minister": "Associate Minister of Immigration"
      },
      {
        "title": "Hon Phil Twyford to the Associate Minister of Immigration",
        "date": "2026-07-06",
        "minister": "Associate Minister of Immigration"
      },
      {
        "title": "Hon Phil Twyford to the Associate Minister of Immigration",
        "date": "2026-07-06",
        "minister": "Associate Minister of Immigration"
      }
    ]
  },
  "tangi-utikere": {
    "count": 2000,
    "recent": [
      {
        "title": "Tangi Utikere to the Associate Minister of Transport",
        "date": "2026-07-06",
        "minister": "Associate Minister of Transport"
      },
      {
        "title": "Tangi Utikere to the Associate Minister of Transport",
        "date": "2026-07-06",
        "minister": "Associate Minister of Transport"
      },
      {
        "title": "Tangi Utikere to the Minister for Rail",
        "date": "2026-07-06",
        "minister": "Minister for Rail"
      },
      {
        "title": "Tangi Utikere to the Minister of Local Government",
        "date": "2026-07-06",
        "minister": "Minister of Local Government"
      },
      {
        "title": "Tangi Utikere to the Minister of Local Government",
        "date": "2026-07-06",
        "minister": "Minister of Local Government"
      }
    ]
  },
  "celia-wade-brown": {
    "count": 214,
    "recent": [
      {
        "title": "Celia Wade-Brown to the Minister for Tourism and Hospitality",
        "date": "2026-07-03",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Celia Wade-Brown to the Minister for Tourism and Hospitality",
        "date": "2026-07-03",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Celia Wade-Brown to the Minister for Tourism and Hospitality",
        "date": "2026-07-02",
        "minister": "Minister for Tourism and Hospitality"
      },
      {
        "title": "Celia Wade-Brown to the Minister of Justice",
        "date": "2026-06-23",
        "minister": "Minister of Justice"
      },
      {
        "title": "Celia Wade-Brown to the Minister of Justice",
        "date": "2026-06-23",
        "minister": "Minister of Justice"
      }
    ]
  },
  "rawiri-waititi": {
    "count": 68,
    "recent": [
      {
        "title": "Rawiri Waititi to the Minister of Corrections",
        "date": "2026-06-04",
        "minister": "Minister of Corrections"
      },
      {
        "title": "Rawiri Waititi to the Minister of Corrections",
        "date": "2026-06-04",
        "minister": "Minister of Corrections"
      },
      {
        "title": "Rawiri Waititi to the Minister of Corrections",
        "date": "2026-06-03",
        "minister": "Minister of Corrections"
      },
      {
        "title": "Rawiri Waititi to the Minister of Corrections",
        "date": "2026-06-03",
        "minister": "Minister of Corrections"
      },
      {
        "title": "Rawiri Waititi to the Minister of Corrections",
        "date": "2026-06-03",
        "minister": "Minister of Corrections"
      }
    ]
  },
  "helen-white": {
    "count": 772,
    "recent": [
      {
        "title": "Helen White to the Minister for the Community and Voluntary Sector",
        "date": "2026-07-06",
        "minister": "Minister for the Community and Voluntary Sector"
      },
      {
        "title": "Helen White to the Minister for the Prevention of Family and Sexual Violence",
        "date": "2026-07-06",
        "minister": "Minister for the Prevention of Family and Sexual Violence"
      },
      {
        "title": "Helen White to the Minister for the Prevention of Family and Sexual Violence",
        "date": "2026-07-06",
        "minister": "Minister for the Prevention of Family and Sexual Violence"
      },
      {
        "title": "Helen White to the Minister for the Community and Voluntary Sector",
        "date": "2026-07-06",
        "minister": "Minister for the Community and Voluntary Sector"
      },
      {
        "title": "Helen White to the Minister for the Prevention of Family and Sexual Violence",
        "date": "2026-06-29",
        "minister": "Minister for the Prevention of Family and Sexual Violence"
      }
    ]
  },
  "arena-williams": {
    "count": 2000,
    "recent": [
      {
        "title": "Arena Williams to the Minister for Youth",
        "date": "2026-07-06",
        "minister": "Minister for Youth"
      },
      {
        "title": "Arena Williams to the Minister for Youth",
        "date": "2026-07-06",
        "minister": "Minister for Youth"
      },
      {
        "title": "Arena Williams to the Minister of Commerce and Consumer Affairs",
        "date": "2026-07-06",
        "minister": "Minister of Commerce and Consumer Affairs"
      },
      {
        "title": "Arena Williams to the Minister of Commerce and Consumer Affairs",
        "date": "2026-07-06",
        "minister": "Minister of Commerce and Consumer Affairs"
      },
      {
        "title": "Arena Williams to the Minister for Building and Construction",
        "date": "2026-07-06",
        "minister": "Minister for Building and Construction"
      }
    ]
  },
  "scott-willis": {
    "count": 493,
    "recent": [
      {
        "title": "Scott Willis to the Minister for Energy",
        "date": "2026-07-03",
        "minister": "Minister for Energy"
      },
      {
        "title": "Scott Willis to the Minister for Energy",
        "date": "2026-07-03",
        "minister": "Minister for Energy"
      },
      {
        "title": "Scott Willis to the Minister for Energy",
        "date": "2026-07-03",
        "minister": "Minister for Energy"
      },
      {
        "title": "Scott Willis to the Minister for Energy",
        "date": "2026-07-03",
        "minister": "Minister for Energy"
      },
      {
        "title": "Scott Willis to the Minister for Energy",
        "date": "2026-07-03",
        "minister": "Minister for Energy"
      }
    ]
  }
}
