// AUTO-GENERATED by scripts/build-poll-history.mjs. Do not edit by hand.
// The full published poll series for the 2026 term, from the same aggregate the
// site already cites as POLLS_SOURCE. DISPLAY-ONLY: the headline poll-of-polls
// still comes from getPolls() (one poll per pollster) and is unaffected by this.

import type { PartySlug } from '@/types'

export interface HistoricalPoll {
  date: string          // ISO date of the last fieldwork day
  fieldwork: string     // human-readable fieldwork range
  pollster: string
  sample?: number
  parties: Partial<Record<PartySlug, number>>
}

export const POLL_HISTORY_META = {
  sourceUrl: 'https://en.wikipedia.org/wiki/Opinion_polling_for_the_2026_New_Zealand_general_election',
  sourceLabel: 'Published poll aggregate for the 2026 general election',
  count: 112,
  from: '2023-11-06',
  to: '2026-08-04',
}

/** Newest first. */
export const POLL_HISTORY: HistoricalPoll[] = [
  {
    "date": "2026-08-04",
    "fieldwork": "1–4 Aug 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 31,
      "labour": 27.8,
      "green": 10.1,
      "act": 7.3,
      "nzfirst": 9.1,
      "tpm": 1.5,
      "top": 6.1
    }
  },
  {
    "date": "2026-07-26",
    "fieldwork": "29 Jun – 26 Jul 2026",
    "pollster": "Roy Morgan",
    "sample": 881,
    "parties": {
      "national": 32,
      "labour": 25.5,
      "green": 13.5,
      "act": 8.5,
      "nzfirst": 8.5,
      "tpm": 2,
      "top": 8
    }
  },
  {
    "date": "2026-07-19",
    "fieldwork": "10–19 Jul 2026",
    "pollster": "Talbot Mills",
    "parties": {
      "national": 31,
      "labour": 33,
      "green": 9,
      "act": 7,
      "nzfirst": 12,
      "tpm": 3,
      "top": 4.7
    }
  },
  {
    "date": "2026-07-09",
    "fieldwork": "2–9 Jul 2026",
    "pollster": "RNZ–Reid Research",
    "sample": 1000,
    "parties": {
      "national": 28.7,
      "labour": 34,
      "green": 10.3,
      "act": 7.8,
      "nzfirst": 11.5,
      "tpm": 2.3,
      "top": 4.7
    }
  },
  {
    "date": "2026-07-05",
    "fieldwork": "1–5 Jul 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 30.5,
      "labour": 31.5,
      "green": 10.4,
      "act": 6.9,
      "nzfirst": 10.8,
      "tpm": 3.4,
      "top": 3.3
    }
  },
  {
    "date": "2026-06-21",
    "fieldwork": "25 May – 21 Jun 2026",
    "pollster": "Roy Morgan",
    "sample": 891,
    "parties": {
      "national": 31,
      "labour": 25.5,
      "green": 13.5,
      "act": 9.5,
      "nzfirst": 10.5,
      "tpm": 3,
      "top": 6.5
    }
  },
  {
    "date": "2026-06-17",
    "fieldwork": "13–17 Jun 2026",
    "pollster": "1News–Verian",
    "sample": 1001,
    "parties": {
      "national": 29,
      "labour": 32,
      "green": 13,
      "act": 6,
      "nzfirst": 11,
      "tpm": 1.8,
      "top": 4.6
    }
  },
  {
    "date": "2026-06-11",
    "fieldwork": "5–11 Jun 2026",
    "pollster": "The Post–Freshwater",
    "sample": 1038,
    "parties": {
      "national": 29,
      "labour": 35,
      "green": 10,
      "act": 8,
      "nzfirst": 12,
      "tpm": 2
    }
  },
  {
    "date": "2026-06-10",
    "fieldwork": "1–10 Jun 2026",
    "pollster": "Talbot Mills",
    "sample": 1021,
    "parties": {
      "national": 29,
      "labour": 34,
      "green": 13,
      "act": 6,
      "nzfirst": 12,
      "tpm": 2.6,
      "top": 3.3
    }
  },
  {
    "date": "2026-06-08",
    "fieldwork": "4–8 Jun 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 30.1,
      "labour": 32.2,
      "green": 11.5,
      "act": 7.8,
      "nzfirst": 11.4,
      "tpm": 3.1,
      "top": 3.2
    }
  },
  {
    "date": "2026-05-24",
    "fieldwork": "27 Apr – 24 May 2026",
    "pollster": "Roy Morgan",
    "sample": 870,
    "parties": {
      "national": 30.5,
      "labour": 26.5,
      "green": 12.5,
      "act": 10,
      "nzfirst": 11,
      "tpm": 2.5,
      "top": 6
    }
  },
  {
    "date": "2026-05-10",
    "fieldwork": "1–10 May 2026",
    "pollster": "Talbot Mills",
    "parties": {
      "national": 29,
      "labour": 36,
      "green": 9,
      "act": 7,
      "nzfirst": 14,
      "tpm": 2
    }
  },
  {
    "date": "2026-05-07",
    "fieldwork": "3–7 May 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 30,
      "labour": 31.9,
      "green": 9.7,
      "act": 6.5,
      "nzfirst": 11.7,
      "tpm": 4.1,
      "top": 2.8
    }
  },
  {
    "date": "2026-04-26",
    "fieldwork": "30 Mar – 26 Apr 2026",
    "pollster": "Roy Morgan",
    "sample": 887,
    "parties": {
      "national": 25.5,
      "labour": 34,
      "green": 11,
      "act": 10.5,
      "nzfirst": 11.5,
      "tpm": 3,
      "top": 4
    }
  },
  {
    "date": "2026-04-16",
    "fieldwork": "16 Apr 2026",
    "pollster": "Talbot Mills",
    "sample": 1082,
    "parties": {
      "national": 29,
      "labour": 36,
      "green": 7,
      "act": 8,
      "nzfirst": 15,
      "tpm": 1.9,
      "top": 2.3
    }
  },
  {
    "date": "2026-04-15",
    "fieldwork": "11–15 Apr 2026",
    "pollster": "1News–Verian",
    "sample": 1010,
    "parties": {
      "national": 30,
      "labour": 37,
      "green": 11,
      "act": 7,
      "nzfirst": 10,
      "tpm": 1.5,
      "top": 3.3
    }
  },
  {
    "date": "2026-04-02",
    "fieldwork": "1–2 Apr 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 29.8,
      "labour": 33.4,
      "green": 7.8,
      "act": 9,
      "nzfirst": 13.6,
      "tpm": 2.6,
      "top": 2.6
    }
  },
  {
    "date": "2026-03-22",
    "fieldwork": "23 Feb – 22 Mar 2026",
    "pollster": "Roy Morgan",
    "sample": 872,
    "parties": {
      "national": 26.5,
      "labour": 34,
      "green": 11,
      "act": 10,
      "nzfirst": 11,
      "tpm": 3,
      "top": 4
    }
  },
  {
    "date": "2026-03-20",
    "fieldwork": "12–20 Mar 2026",
    "pollster": "RNZ–Reid Research",
    "sample": 1000,
    "parties": {
      "national": 30.8,
      "labour": 35.6,
      "green": 10.1,
      "act": 7,
      "nzfirst": 10.6,
      "tpm": 3.2,
      "top": 2
    }
  },
  {
    "date": "2026-03-12",
    "fieldwork": "2–12 Mar 2026",
    "pollster": "Talbot Mills",
    "sample": 1059,
    "parties": {
      "national": 32,
      "labour": 35,
      "green": 11,
      "act": 7,
      "nzfirst": 11,
      "tpm": 1.7,
      "top": 2.4
    }
  },
  {
    "date": "2026-03-03",
    "fieldwork": "1–3 Mar 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 28.4,
      "labour": 34.4,
      "green": 10.5,
      "act": 7.5,
      "nzfirst": 9.7,
      "tpm": 3.2,
      "top": 1.9
    }
  },
  {
    "date": "2026-02-22",
    "fieldwork": "27 Jan – 22 Feb 2026",
    "pollster": "Roy Morgan",
    "sample": 870,
    "parties": {
      "national": 31,
      "labour": 30,
      "green": 14.5,
      "act": 8,
      "nzfirst": 9.5,
      "tpm": 2.5,
      "top": 4
    }
  },
  {
    "date": "2026-02-12",
    "fieldwork": "6–12 Feb 2026",
    "pollster": "The Post–Freshwater",
    "sample": 1039,
    "parties": {
      "national": 30,
      "labour": 37,
      "green": 10,
      "act": 6,
      "nzfirst": 11,
      "tpm": 2
    }
  },
  {
    "date": "2026-02-11",
    "fieldwork": "7–11 Feb 2026",
    "pollster": "1News–Verian",
    "sample": 1003,
    "parties": {
      "national": 34,
      "labour": 32,
      "green": 11,
      "act": 9,
      "nzfirst": 10,
      "tpm": 2,
      "top": 1
    }
  },
  {
    "date": "2026-02-03",
    "fieldwork": "1–3 Feb 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 31.3,
      "labour": 34.1,
      "green": 10.3,
      "act": 6.7,
      "nzfirst": 10.5,
      "tpm": 2.9,
      "top": 1.4
    }
  },
  {
    "date": "2026-01-26",
    "fieldwork": "6–26 Jan 2026",
    "pollster": "Roy Morgan",
    "sample": 881,
    "parties": {
      "national": 34.5,
      "labour": 30.5,
      "green": 10.5,
      "act": 8.5,
      "nzfirst": 9,
      "tpm": 3,
      "top": 2.5
    }
  },
  {
    "date": "2026-01-26",
    "fieldwork": "16–26 Jan 2026",
    "pollster": "Talbot Mills",
    "sample": 1087,
    "parties": {
      "national": 31,
      "labour": 35,
      "green": 10,
      "act": 8,
      "nzfirst": 9,
      "tpm": 3
    }
  },
  {
    "date": "2026-01-22",
    "fieldwork": "15–22 Jan 2026",
    "pollster": "RNZ–Reid Research",
    "sample": 1000,
    "parties": {
      "national": 31.9,
      "labour": 35,
      "green": 9.6,
      "act": 7.6,
      "nzfirst": 9.8,
      "tpm": 3,
      "top": 2.3
    }
  },
  {
    "date": "2026-01-18",
    "fieldwork": "14–18 Jan 2026",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 31.5,
      "labour": 34.4,
      "green": 7.7,
      "act": 7,
      "nzfirst": 11.9,
      "tpm": 3,
      "top": 0.7
    }
  },
  {
    "date": "2025-12-21",
    "fieldwork": "25 Nov – 21 Dec 2025",
    "pollster": "Roy Morgan",
    "sample": 859,
    "parties": {
      "national": 33,
      "labour": 32.5,
      "green": 12,
      "act": 7.5,
      "nzfirst": 10,
      "tpm": 2.5,
      "top": 2.5
    }
  },
  {
    "date": "2025-12-10",
    "fieldwork": "5–10 Dec 2025",
    "pollster": "The Post–Freshwater",
    "sample": 1031,
    "parties": {
      "national": 30,
      "labour": 38,
      "green": 8,
      "act": 8,
      "nzfirst": 9,
      "tpm": 2
    }
  },
  {
    "date": "2025-12-07",
    "fieldwork": "3–7 Dec 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 30,
      "labour": 31.6,
      "green": 10.8,
      "act": 8.9,
      "nzfirst": 8.1,
      "tpm": 3.1,
      "top": 1.6
    }
  },
  {
    "date": "2025-12-03",
    "fieldwork": "29 Nov – 3 Dec 2025",
    "pollster": "1News–Verian",
    "sample": 1007,
    "parties": {
      "national": 36,
      "labour": 35,
      "green": 7,
      "act": 10,
      "nzfirst": 9,
      "tpm": 0.6,
      "top": 0.4
    }
  },
  {
    "date": "2025-11-23",
    "fieldwork": "27 Oct – 23 Nov 2025",
    "pollster": "Roy Morgan",
    "sample": 829,
    "parties": {
      "national": 33,
      "labour": 28,
      "green": 14.5,
      "act": 8,
      "nzfirst": 9,
      "tpm": 2,
      "top": 2.5
    }
  },
  {
    "date": "2025-11-10",
    "fieldwork": "1–10 Nov 2025",
    "pollster": "Talbot Mills",
    "sample": 1000,
    "parties": {
      "national": 33,
      "labour": 38,
      "green": 9,
      "act": 7,
      "nzfirst": 8,
      "tpm": 2.4
    }
  },
  {
    "date": "2025-11-06",
    "fieldwork": "2–6 Nov 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 30.2,
      "labour": 33.3,
      "green": 9.2,
      "act": 8.6,
      "nzfirst": 9.1,
      "tpm": 3.3,
      "top": 1.2
    }
  },
  {
    "date": "2025-10-26",
    "fieldwork": "29 Sep – 26 Oct 2025",
    "pollster": "Roy Morgan",
    "sample": 857,
    "parties": {
      "national": 32,
      "labour": 30.5,
      "green": 12,
      "act": 8,
      "nzfirst": 9.5,
      "tpm": 2.5,
      "top": 2.5
    }
  },
  {
    "date": "2025-10-10",
    "fieldwork": "1–10 Oct 2025",
    "pollster": "Talbot Mills",
    "sample": 1097,
    "parties": {
      "national": 29,
      "labour": 35,
      "green": 10,
      "act": 8,
      "nzfirst": 12,
      "tpm": 4
    }
  },
  {
    "date": "2025-10-08",
    "fieldwork": "4–8 Oct 2025",
    "pollster": "1News–Verian",
    "sample": 1014,
    "parties": {
      "national": 34,
      "labour": 32,
      "green": 11,
      "act": 8,
      "nzfirst": 9,
      "tpm": 2.8,
      "top": 0.8
    }
  },
  {
    "date": "2025-10-08",
    "fieldwork": "3–8 Oct 2025",
    "pollster": "The Post–Freshwater",
    "sample": 1050,
    "parties": {
      "national": 31,
      "labour": 34,
      "green": 9,
      "act": 9,
      "nzfirst": 11,
      "tpm": 3
    }
  },
  {
    "date": "2025-10-05",
    "fieldwork": "1–5 Oct 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 29.6,
      "labour": 31.2,
      "green": 12,
      "act": 6.6,
      "nzfirst": 10.6,
      "tpm": 4.4,
      "top": 1.6
    }
  },
  {
    "date": "2025-09-21",
    "fieldwork": "25 Aug – 21 Sep 2025",
    "pollster": "Roy Morgan",
    "sample": 870,
    "parties": {
      "national": 31.5,
      "labour": 28.5,
      "green": 13.5,
      "act": 9,
      "nzfirst": 8,
      "tpm": 5.5,
      "top": 2.5
    }
  },
  {
    "date": "2025-09-12",
    "fieldwork": "4–12 Sep 2025",
    "pollster": "RNZ–Reid Research",
    "sample": 1000,
    "parties": {
      "national": 32.5,
      "labour": 34.3,
      "green": 10.9,
      "act": 7.2,
      "nzfirst": 8.7,
      "tpm": 4.1,
      "top": 1.4
    }
  },
  {
    "date": "2025-09-10",
    "fieldwork": "1–10 Sep 2025",
    "pollster": "Talbot Mills",
    "sample": 1000,
    "parties": {
      "national": 31,
      "labour": 35,
      "green": 10,
      "act": 7,
      "nzfirst": 10,
      "tpm": 4
    }
  },
  {
    "date": "2025-09-02",
    "fieldwork": "31 Aug – 2 Sep 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 33.1,
      "labour": 33.8,
      "green": 10.7,
      "act": 6.7,
      "nzfirst": 8.1,
      "tpm": 4.3,
      "top": 1.1
    }
  },
  {
    "date": "2025-08-24",
    "fieldwork": "28 Jul – 24 Aug 2025",
    "pollster": "Roy Morgan",
    "sample": 873,
    "parties": {
      "national": 29,
      "labour": 34,
      "green": 13.5,
      "act": 10.5,
      "nzfirst": 7,
      "tpm": 2.5,
      "top": 3
    }
  },
  {
    "date": "2025-08-10",
    "fieldwork": "1–10 Aug 2025",
    "pollster": "Talbot Mills",
    "sample": 1000,
    "parties": {
      "national": 32,
      "labour": 34,
      "green": 11,
      "act": 8,
      "nzfirst": 9.3,
      "tpm": 4.4,
      "top": 2.8
    }
  },
  {
    "date": "2025-08-06",
    "fieldwork": "2–6 Aug 2025",
    "pollster": "1News–Verian",
    "sample": 1002,
    "parties": {
      "national": 34,
      "labour": 33,
      "green": 10,
      "act": 8,
      "nzfirst": 9,
      "tpm": 3.7,
      "top": 1.3
    }
  },
  {
    "date": "2025-08-05",
    "fieldwork": "3–5 Aug 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 31.8,
      "labour": 33.6,
      "green": 9.8,
      "act": 8.6,
      "nzfirst": 7.8,
      "tpm": 3.2,
      "top": 2.6
    }
  },
  {
    "date": "2025-07-27",
    "fieldwork": "30 Jun – 27 Jul 2025",
    "pollster": "Roy Morgan",
    "sample": 832,
    "parties": {
      "national": 31,
      "labour": 31,
      "green": 11.5,
      "act": 10.5,
      "nzfirst": 9.5,
      "tpm": 3.5,
      "top": 1
    }
  },
  {
    "date": "2025-07-10",
    "fieldwork": "1–10 Jul 2025",
    "pollster": "Talbot Mills",
    "sample": 1090,
    "parties": {
      "national": 32,
      "labour": 35,
      "green": 12,
      "act": 8,
      "nzfirst": 7,
      "tpm": 3.8
    }
  },
  {
    "date": "2025-07-06",
    "fieldwork": "2–6 Jul 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 33.9,
      "labour": 31.6,
      "green": 9.4,
      "act": 9.1,
      "nzfirst": 9.8,
      "tpm": 3.5,
      "top": 1.2
    }
  },
  {
    "date": "2025-06-22",
    "fieldwork": "26 May – 22 Jun 2025",
    "pollster": "Roy Morgan",
    "sample": 812,
    "parties": {
      "national": 32,
      "labour": 28.5,
      "green": 11,
      "act": 11.5,
      "nzfirst": 8,
      "tpm": 5,
      "top": 3
    }
  },
  {
    "date": "2025-06-15",
    "fieldwork": "12–15 Jun 2025",
    "pollster": "The Post–Freshwater",
    "sample": 1150,
    "parties": {
      "national": 32,
      "labour": 34,
      "green": 11,
      "act": 8,
      "nzfirst": 8,
      "tpm": 2
    }
  },
  {
    "date": "2025-06-09",
    "fieldwork": "7–9 Jun 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 33.5,
      "labour": 34.8,
      "green": 8.2,
      "act": 9.1,
      "nzfirst": 6.1,
      "tpm": 3.3,
      "top": 1.8
    }
  },
  {
    "date": "2025-05-30",
    "fieldwork": "23–30 May 2025",
    "pollster": "RNZ–Reid Research",
    "sample": 1008,
    "parties": {
      "national": 30.7,
      "labour": 33.2,
      "green": 11.6,
      "act": 6.6,
      "nzfirst": 9.1,
      "tpm": 5.5,
      "top": 2.2
    }
  },
  {
    "date": "2025-05-28",
    "fieldwork": "24–28 May 2025",
    "pollster": "1News–Verian",
    "sample": 1002,
    "parties": {
      "national": 34,
      "labour": 29,
      "green": 12,
      "act": 8,
      "nzfirst": 8,
      "tpm": 3.7,
      "top": 1.3
    }
  },
  {
    "date": "2025-05-25",
    "fieldwork": "28 Apr – 25 May 2025",
    "pollster": "Roy Morgan",
    "sample": 799,
    "parties": {
      "national": 31.5,
      "labour": 29,
      "green": 11.5,
      "act": 12,
      "nzfirst": 6.5,
      "tpm": 4.5,
      "top": 3
    }
  },
  {
    "date": "2025-05-04",
    "fieldwork": "30 Apr – 4 May 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 34.6,
      "labour": 33.2,
      "green": 9.1,
      "act": 9.5,
      "nzfirst": 7.4,
      "tpm": 3.9,
      "top": 0.5
    }
  },
  {
    "date": "2025-04-20",
    "fieldwork": "24 Mar – 20 Apr 2025",
    "pollster": "Roy Morgan",
    "sample": 829,
    "parties": {
      "national": 31,
      "labour": 28.5,
      "green": 14,
      "act": 9,
      "nzfirst": 9,
      "tpm": 4.5,
      "top": 2.5
    }
  },
  {
    "date": "2025-04-02",
    "fieldwork": "29 Mar – 2 Apr 2025",
    "pollster": "1News–Verian",
    "sample": 1000,
    "parties": {
      "national": 36,
      "labour": 32,
      "green": 10,
      "act": 9,
      "nzfirst": 7,
      "tpm": 3.4,
      "top": 2.1
    }
  },
  {
    "date": "2025-04-01",
    "fieldwork": "29 Mar – 1 Apr 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 33.5,
      "labour": 29.8,
      "green": 11,
      "act": 10,
      "nzfirst": 7.4,
      "tpm": 4.3,
      "top": 1.5
    }
  },
  {
    "date": "2025-03-27",
    "fieldwork": "21–27 Mar 2025",
    "pollster": "RNZ–Reid Research",
    "sample": 1000,
    "parties": {
      "national": 32.9,
      "labour": 32.3,
      "green": 10,
      "act": 9.4,
      "nzfirst": 7.2,
      "tpm": 5,
      "top": 1.8
    }
  },
  {
    "date": "2025-03-23",
    "fieldwork": "24 Feb – 23 Mar 2025",
    "pollster": "Roy Morgan",
    "sample": 888,
    "parties": {
      "national": 32.5,
      "labour": 27.5,
      "green": 14.5,
      "act": 7.5,
      "nzfirst": 7,
      "tpm": 5.5,
      "top": 4
    }
  },
  {
    "date": "2025-03-10",
    "fieldwork": "1–10 Mar 2025",
    "pollster": "Talbot Mills",
    "sample": 1003,
    "parties": {
      "national": 31,
      "labour": 34,
      "green": 10,
      "act": 10,
      "nzfirst": 6.1,
      "tpm": 4.4
    }
  },
  {
    "date": "2025-03-04",
    "fieldwork": "2–4 Mar 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 33.6,
      "labour": 34.1,
      "green": 10,
      "act": 7.7,
      "nzfirst": 5.1,
      "tpm": 6.5,
      "top": 0.5
    }
  },
  {
    "date": "2025-02-23",
    "fieldwork": "27 Jan – 23 Feb 2025",
    "pollster": "Roy Morgan",
    "sample": 888,
    "parties": {
      "national": 30.5,
      "labour": 29,
      "green": 15.5,
      "act": 11,
      "nzfirst": 6,
      "tpm": 3,
      "top": 2.5
    }
  },
  {
    "date": "2025-02-07",
    "fieldwork": "3–7 Feb 2025",
    "pollster": "1News–Verian",
    "sample": 1002,
    "parties": {
      "national": 34,
      "labour": 33,
      "green": 10,
      "act": 9,
      "nzfirst": 5,
      "tpm": 3.7,
      "top": 1.9
    }
  },
  {
    "date": "2025-02-04",
    "fieldwork": "2–4 Feb 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 31.9,
      "labour": 31.3,
      "green": 13.2,
      "act": 10,
      "nzfirst": 6.4,
      "tpm": 4.4,
      "top": 0.5
    }
  },
  {
    "date": "2025-01-27",
    "fieldwork": "7–27 Jan 2025",
    "pollster": "Talbot Mills",
    "sample": 1049,
    "parties": {
      "national": 33,
      "labour": 34,
      "green": 12,
      "act": 9,
      "nzfirst": 5.2,
      "tpm": 4.6
    }
  },
  {
    "date": "2025-01-26",
    "fieldwork": "2–26 Jan 2025",
    "pollster": "Roy Morgan",
    "sample": 885,
    "parties": {
      "national": 32.5,
      "labour": 28.5,
      "green": 11.5,
      "act": 9,
      "nzfirst": 8.5,
      "tpm": 6.5,
      "top": 1.5
    }
  },
  {
    "date": "2025-01-13",
    "fieldwork": "9–13 Jan 2025",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 29.6,
      "labour": 30.9,
      "green": 9.5,
      "act": 10.8,
      "nzfirst": 8.1,
      "tpm": 5.3,
      "top": 2.1
    }
  },
  {
    "date": "2024-12-15",
    "fieldwork": "25 Nov – 15 Dec 2024",
    "pollster": "Roy Morgan",
    "sample": 885,
    "parties": {
      "national": 31,
      "labour": 26,
      "green": 13.5,
      "act": 13,
      "nzfirst": 7.5,
      "tpm": 5.5,
      "top": 1
    }
  },
  {
    "date": "2024-12-04",
    "fieldwork": "30 Nov – 4 Dec 2024",
    "pollster": "1News–Verian",
    "sample": 1006,
    "parties": {
      "national": 37,
      "labour": 29,
      "green": 10,
      "act": 8,
      "nzfirst": 6,
      "tpm": 7,
      "top": 1.5
    }
  },
  {
    "date": "2024-12-03",
    "fieldwork": "1–3 Dec 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 34.2,
      "labour": 26.9,
      "green": 8.3,
      "act": 13,
      "nzfirst": 5.4,
      "tpm": 5.5,
      "top": 1.1
    }
  },
  {
    "date": "2024-11-28",
    "fieldwork": "22–28 Nov 2024",
    "pollster": "Talbot Mills (Labour-commissioned)",
    "parties": {
      "national": 31,
      "labour": 32,
      "green": 10,
      "act": 10,
      "nzfirst": 6,
      "tpm": 7
    }
  },
  {
    "date": "2024-11-27",
    "fieldwork": "26–27 Nov 2024",
    "pollster": "The Post–Freshwater",
    "sample": 1150,
    "parties": {
      "national": 34,
      "labour": 31,
      "green": 13,
      "act": 8,
      "nzfirst": 6,
      "tpm": 4
    }
  },
  {
    "date": "2024-11-24",
    "fieldwork": "28 Oct – 24 Nov 2024",
    "pollster": "Roy Morgan",
    "sample": 866,
    "parties": {
      "national": 28.5,
      "labour": 28,
      "green": 13.5,
      "act": 9,
      "nzfirst": 6.5,
      "tpm": 9,
      "top": 3.5
    }
  },
  {
    "date": "2024-11-10",
    "fieldwork": "6–10 Nov 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 38.8,
      "labour": 31.5,
      "green": 9.3,
      "act": 8.5,
      "nzfirst": 6.5,
      "tpm": 2.5,
      "top": 0.9
    }
  },
  {
    "date": "2024-11-10",
    "fieldwork": "1–10 Nov 2024",
    "pollster": "Talbot Mills",
    "parties": {
      "national": 34,
      "labour": 33,
      "green": 10,
      "act": 10,
      "nzfirst": 7,
      "tpm": 3.3
    }
  },
  {
    "date": "2024-10-20",
    "fieldwork": "23 Sep – 20 Oct 2024",
    "pollster": "Roy Morgan",
    "sample": 883,
    "parties": {
      "national": 31,
      "labour": 29,
      "green": 14,
      "act": 9,
      "nzfirst": 7,
      "tpm": 5,
      "top": 2
    }
  },
  {
    "date": "2024-10-09",
    "fieldwork": "5–9 Oct 2024",
    "pollster": "1News–Verian",
    "sample": 1000,
    "parties": {
      "national": 37,
      "labour": 29,
      "green": 12,
      "act": 8,
      "nzfirst": 5,
      "tpm": 3.8,
      "top": 2.6
    }
  },
  {
    "date": "2024-10-07",
    "fieldwork": "3–7 Oct 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 34.9,
      "labour": 30.3,
      "green": 10.4,
      "act": 9.7,
      "nzfirst": 7.6,
      "tpm": 3,
      "top": 2.5
    }
  },
  {
    "date": "2024-09-22",
    "fieldwork": "26 Aug – 22 Sep 2024",
    "pollster": "Roy Morgan",
    "sample": 902,
    "parties": {
      "national": 37.5,
      "labour": 23,
      "green": 14,
      "act": 10,
      "nzfirst": 7.5,
      "tpm": 4,
      "top": 2.5
    }
  },
  {
    "date": "2024-09-10",
    "fieldwork": "8–10 Sep 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 39,
      "labour": 26.7,
      "green": 11,
      "act": 8.8,
      "nzfirst": 6.8,
      "tpm": 5,
      "top": 1.1
    }
  },
  {
    "date": "2024-09-10",
    "fieldwork": "1–10 Sep 2024",
    "pollster": "Talbot Mills",
    "parties": {
      "national": 37,
      "labour": 32,
      "green": 10,
      "act": 8,
      "nzfirst": 6.1,
      "tpm": 3.9
    }
  },
  {
    "date": "2024-08-25",
    "fieldwork": "29 Jul – 25 Aug 2024",
    "pollster": "Roy Morgan",
    "sample": 898,
    "parties": {
      "national": 36,
      "labour": 26.5,
      "green": 13,
      "act": 9.5,
      "nzfirst": 7.5,
      "tpm": 3.5,
      "top": 2.5
    }
  },
  {
    "date": "2024-08-14",
    "fieldwork": "10–14 Aug 2024",
    "pollster": "1News–Verian",
    "sample": 1001,
    "parties": {
      "national": 38,
      "labour": 30,
      "green": 11,
      "act": 7,
      "nzfirst": 6,
      "tpm": 4.2,
      "top": 1.1
    }
  },
  {
    "date": "2024-07-21",
    "fieldwork": "24 Jun – 21 Jul 2024",
    "pollster": "Roy Morgan",
    "sample": 930,
    "parties": {
      "national": 32.5,
      "labour": 24,
      "green": 14,
      "act": 11,
      "nzfirst": 6.5,
      "tpm": 6,
      "top": 4.5
    }
  },
  {
    "date": "2024-07-08",
    "fieldwork": "4–8 Jul 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 37.6,
      "labour": 25.9,
      "green": 12.5,
      "act": 9.1,
      "nzfirst": 7.3,
      "tpm": 3.5,
      "top": 2.4
    }
  },
  {
    "date": "2024-06-23",
    "fieldwork": "27 May – 23 Jun 2024",
    "pollster": "Roy Morgan",
    "sample": 930,
    "parties": {
      "national": 35,
      "labour": 27.5,
      "green": 14.5,
      "act": 9,
      "nzfirst": 5.5,
      "tpm": 3.5,
      "top": 2.5
    }
  },
  {
    "date": "2024-06-19",
    "fieldwork": "15–19 Jun 2024",
    "pollster": "1News–Verian",
    "sample": 1002,
    "parties": {
      "national": 38,
      "labour": 29,
      "green": 13,
      "act": 7,
      "nzfirst": 6,
      "tpm": 3.3,
      "top": 1.5
    }
  },
  {
    "date": "2024-06-06",
    "fieldwork": "4–6 Jun 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 35.4,
      "labour": 29.4,
      "green": 12.7,
      "act": 9.7,
      "nzfirst": 5.6,
      "tpm": 4,
      "top": 0.8
    }
  },
  {
    "date": "2024-05-19",
    "fieldwork": "22 Apr – 19 May 2024",
    "pollster": "Roy Morgan",
    "sample": 925,
    "parties": {
      "national": 33.5,
      "labour": 30,
      "green": 14,
      "act": 9.5,
      "nzfirst": 5.5,
      "tpm": 3,
      "top": 3
    }
  },
  {
    "date": "2024-05-07",
    "fieldwork": "5–7 May 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 37.3,
      "labour": 30,
      "green": 10.2,
      "act": 9.4,
      "nzfirst": 5.5,
      "tpm": 3.1,
      "top": 1.4
    }
  },
  {
    "date": "2024-04-30",
    "fieldwork": "30 Apr 2024",
    "pollster": "Talbot Mills (Labour-commissioned)",
    "parties": {
      "national": 34,
      "labour": 33,
      "green": 12,
      "act": 7,
      "nzfirst": 6,
      "tpm": 4
    }
  },
  {
    "date": "2024-04-24",
    "fieldwork": "20–24 Apr 2024",
    "pollster": "1News–Verian",
    "sample": 1000,
    "parties": {
      "national": 36,
      "labour": 30,
      "green": 14,
      "act": 7,
      "nzfirst": 4.2,
      "tpm": 3.7,
      "top": 1.2
    }
  },
  {
    "date": "2024-04-21",
    "fieldwork": "25 Mar – 21 Apr 2024",
    "pollster": "Roy Morgan",
    "sample": 934,
    "parties": {
      "national": 36.5,
      "labour": 24.5,
      "green": 13,
      "act": 11,
      "nzfirst": 5.5,
      "tpm": 5.5,
      "top": 2
    }
  },
  {
    "date": "2024-04-04",
    "fieldwork": "2–4 Apr 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 37.1,
      "labour": 25.7,
      "green": 14.6,
      "act": 7.2,
      "nzfirst": 6.3,
      "tpm": 4.6,
      "top": 1.6
    }
  },
  {
    "date": "2024-03-24",
    "fieldwork": "26 Feb – 24 Mar 2024",
    "pollster": "Roy Morgan",
    "sample": 931,
    "parties": {
      "national": 38,
      "labour": 23,
      "green": 13.5,
      "act": 11.5,
      "nzfirst": 6.5,
      "tpm": 3.5,
      "top": 2.5
    }
  },
  {
    "date": "2024-03-10",
    "fieldwork": "1–10 Mar 2024",
    "pollster": "Talbot Mills",
    "sample": 1000,
    "parties": {
      "national": 38,
      "labour": 28,
      "green": 14,
      "act": 8,
      "nzfirst": 6
    }
  },
  {
    "date": "2024-03-05",
    "fieldwork": "3–5 Mar 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 37.4,
      "labour": 25.3,
      "green": 11.3,
      "act": 10,
      "nzfirst": 7.4,
      "tpm": 2.5,
      "top": 2.1
    }
  },
  {
    "date": "2024-02-25",
    "fieldwork": "29 Jan – 25 Feb 2024",
    "pollster": "Roy Morgan",
    "sample": 935,
    "parties": {
      "national": 35.5,
      "labour": 21.5,
      "green": 15.5,
      "act": 12,
      "nzfirst": 7.5,
      "tpm": 4,
      "top": 2.5
    }
  },
  {
    "date": "2024-02-14",
    "fieldwork": "10–14 Feb 2024",
    "pollster": "1News–Verian",
    "sample": 1002,
    "parties": {
      "national": 38,
      "labour": 28,
      "green": 12,
      "act": 8,
      "nzfirst": 6,
      "tpm": 3.7,
      "top": 1.9
    }
  },
  {
    "date": "2024-02-10",
    "fieldwork": "1–10 Feb 2024",
    "pollster": "Talbot Mills",
    "parties": {
      "national": 38,
      "labour": 29,
      "green": 12,
      "act": 7,
      "nzfirst": 6.2,
      "tpm": 4.9,
      "top": 1.4
    }
  },
  {
    "date": "2024-02-07",
    "fieldwork": "1–7 Feb 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 39.6,
      "labour": 27.9,
      "green": 9,
      "act": 13.7,
      "nzfirst": 5,
      "tpm": 2.3
    }
  },
  {
    "date": "2024-01-31",
    "fieldwork": "8–28 Jan 2024",
    "pollster": "Roy Morgan",
    "sample": 947,
    "parties": {
      "national": 38,
      "labour": 22,
      "green": 15.5,
      "act": 7.5,
      "nzfirst": 6,
      "tpm": 4.5,
      "top": 4.5
    }
  },
  {
    "date": "2024-01-10",
    "fieldwork": "8–10 Jan 2024",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 41,
      "labour": 28.4,
      "green": 9.5,
      "act": 7.8,
      "nzfirst": 5.6,
      "tpm": 3.6
    }
  },
  {
    "date": "2023-12-31",
    "fieldwork": "27 Nov – 17 Dec 2023",
    "pollster": "Roy Morgan",
    "sample": 947,
    "parties": {
      "national": 36,
      "labour": 22,
      "green": 15.5,
      "act": 9.5,
      "nzfirst": 6,
      "tpm": 5,
      "top": 4
    }
  },
  {
    "date": "2023-12-05",
    "fieldwork": "3–5 Dec 2023",
    "pollster": "Taxpayers' Union–Curia",
    "parties": {
      "national": 36.5,
      "labour": 28.8,
      "green": 10.8,
      "act": 6.2,
      "nzfirst": 8.1,
      "tpm": 5
    }
  },
  {
    "date": "2023-11-30",
    "fieldwork": "30 Oct – 26 Nov 2023",
    "pollster": "Roy Morgan",
    "sample": 920,
    "parties": {
      "national": 37.5,
      "labour": 21,
      "green": 12.5,
      "act": 12.5,
      "nzfirst": 8,
      "tpm": 2.5,
      "top": 3.5
    }
  },
  {
    "date": "2023-11-06",
    "fieldwork": "1–6 Nov 2023",
    "pollster": "Taxpayers' Union–Curia",
    "sample": 1000,
    "parties": {
      "national": 37,
      "labour": 28.3,
      "green": 13.8,
      "act": 8.1,
      "nzfirst": 6,
      "tpm": 3.4,
      "top": 2.9
    }
  }
]

/** Average party support across polls whose fieldwork ended in [from, to].
 *  Returns null for a party with no readings in the window — never 0, which
 *  would read as "polled at zero" rather than "not polled". */
export function averageIn(from: string, to: string, slug: PartySlug): number | null {
  const vals = POLL_HISTORY
    .filter((p) => p.date >= from && p.date <= to)
    .map((p) => p.parties[slug])
    .filter((v): v is number => typeof v === 'number' && isFinite(v))
  if (!vals.length) return null
  return Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 10) / 10
}
