/**
 * record-national.ts — data for the PRIVATE National accountability view.
 *
 * ⚠ Credibility rules (do not relax):
 *  - Every item is drawn from the public record (coalition agreements, the
 *    government's 100-day plan, enacted Acts on legislation.govt.nz, official
 *    statistics). Nothing here is invented.
 *  - Statuses are assessed to a JANUARY 2026 knowledge cutoff. Anything later
 *    must be re-verified against the linked primary source (see `asOf`).
 *  - Economic indicators are CONTEXT only — directional trends with links to the
 *    official live series. We do NOT assert that any one policy caused an
 *    outcome, and we deliberately store no precise figures we cannot verify.
 *
 * The 54th Parliament: National-led coalition government formed 27 Nov 2023
 * (National + ACT + NZ First), PM Christopher Luxon.
 */

export type PromiseStatus = 'delivered' | 'in_progress' | 'changed' | 'not_done'

export interface RecordSource {
  label: string
  url: string
}

export interface PromiseItem {
  id: string
  /** The commitment, as made (manifesto / 100-day plan / coalition agreement). */
  text: string
  category: string
  status: PromiseStatus
  /** What actually happened — neutral, factual. */
  evidence: string
  source?: RecordSource
  /** Verification note (e.g. "Enacted 2024" or "Status to Jan 2026 — verify"). */
  asOf?: string
}

export interface RecordBill {
  title: string
  /** Neutral one-line description of what it does. */
  does: string
  status: 'enacted' | 'in_progress' | 'defeated' | 'withdrawn'
  when?: string
  source?: RecordSource
}

export interface Priority {
  theme: string
  detail: string
}

// Economic indicators now come from live data — see src/constants/economic-data.ts
// (generated by scripts/fetch-economic-data.mjs).

// ─── Sources (link to the official source area; confirm the specific record there) ──
const S = {
  beehive: { label: 'beehive.govt.nz — Government 100-day plan', url: 'https://www.beehive.govt.nz/' },
  coalition: { label: 'DPMC — Coalition agreements', url: 'https://www.dpmc.govt.nz/' },
  legislation: { label: 'legislation.govt.nz', url: 'https://www.legislation.govt.nz/' },
  parliament: { label: 'Parliament — Bills & laws', url: 'https://www.parliament.nz/en/pb/bills-and-laws/' },
  national: { label: 'National Party — published plan', url: 'https://www.national.org.nz/' },
  budget: { label: 'Budget 2024 — Treasury', url: 'https://www.treasury.govt.nz/' },
} as const

export const GOVERNMENT = {
  party: 'National',
  formed: '27 November 2023',
  parliament: '54th Parliament',
  pm: 'Christopher Luxon',
  partners: ['ACT', 'NZ First'],
}

// ─── Promises / commitments ─────────────────────────────────────────────────────
// Drawn from National's published plan, the 100-day action plan and the coalition
// agreements. Statuses to Jan 2026 — verify anything dated later.
export const PROMISES: PromiseItem[] = [
  // Tax & cost of living
  { id: 'tax-relief', category: 'Tax & cost of living', status: 'delivered',
    text: 'Deliver income tax relief by adjusting the personal tax thresholds.',
    evidence: 'Tax thresholds adjusted in Budget 2024; changes took effect 31 July 2024.',
    source: S.budget, asOf: 'Effective 31 Jul 2024' },
  { id: 'fuel-tax', category: 'Tax & cost of living', status: 'delivered',
    text: 'Scrap the Auckland Regional Fuel Tax.',
    evidence: 'Regional fuel tax removed; ended 30 June 2024.', source: S.beehive, asOf: 'Ended 30 Jun 2024' },
  { id: 'interest-deduct', category: 'Tax & cost of living', status: 'delivered',
    text: 'Restore interest deductibility for residential rental property.',
    evidence: 'Deductibility phased back in (80% for 2024/25, 100% from 2025/26).', source: S.beehive, asOf: 'Phased 2024–2026' },
  { id: 'familyboost', category: 'Tax & cost of living', status: 'delivered',
    text: 'Introduce the FamilyBoost childcare tax rebate.',
    evidence: 'FamilyBoost rebate available to eligible families from 1 July 2024.', source: S.beehive, asOf: 'From 1 Jul 2024' },
  { id: 'clean-car', category: 'Tax & cost of living', status: 'delivered',
    text: 'End the Clean Car Discount (EV rebate / higher-emissions fee).',
    evidence: 'Clean Car Discount scheme ended 31 December 2023.', source: S.beehive, asOf: 'Ended 31 Dec 2023' },

  // Law & order
  { id: 'three-strikes', category: 'Law & order', status: 'delivered',
    text: 'Reinstate a Three Strikes sentencing regime.',
    evidence: 'Three Strikes legislation reintroduced and passed (2025).', source: S.legislation, asOf: '2025 — verify' },
  { id: 'gang-patches', category: 'Law & order', status: 'delivered',
    text: 'Ban gang patches and insignia in public places.',
    evidence: 'Gangs legislation passed 2024; public patch ban in force from Nov 2024.', source: S.legislation, asOf: 'In force Nov 2024' },
  { id: 'boot-camps', category: 'Law & order', status: 'in_progress',
    text: 'Establish military-style academies for serious young offenders.',
    evidence: 'Youth "boot camp" pilot launched in 2024; programme ongoing.', source: S.beehive, asOf: 'Pilot from 2024 — verify outcomes' },
  { id: 'phones-schools', category: 'Law & order / Education', status: 'delivered',
    text: 'Ban cellphone use in schools.',
    evidence: 'School cellphone ban applied from the start of the 2024 school year.', source: S.beehive, asOf: 'From Term 1, 2024' },

  // Health & social
  { id: 'maori-health', category: 'Health', status: 'delivered',
    text: 'Disestablish the Māori Health Authority (Te Aka Whai Ora).',
    evidence: 'Te Aka Whai Ora disestablished via Pae Ora amendment legislation (2024).', source: S.legislation, asOf: '2024' },
  { id: 'smokefree', category: 'Health', status: 'delivered',
    text: 'Repeal the previous government’s smokefree (denicotinisation / generation ban) amendments.',
    evidence: 'Smokefree amendment measures repealed in early 2024.', source: S.legislation, asOf: 'Feb 2024' },

  // Resource management, water & infrastructure
  { id: 'three-waters', category: 'Water & infrastructure', status: 'delivered',
    text: 'Repeal Three Waters (Affordable Water Reforms).',
    evidence: 'Three Waters repealed; replaced by the "Local Water Done Well" framework.', source: S.legislation, asOf: '2024' },
  { id: 'rma-repeal', category: 'Water & infrastructure', status: 'delivered',
    text: 'Repeal the Natural and Built Environment Act and Spatial Planning Act.',
    evidence: 'Both RMA-reform Acts repealed in December 2023; full RMA replacement under way.', source: S.legislation, asOf: 'Repealed Dec 2023' },
  { id: 'fast-track', category: 'Water & infrastructure', status: 'delivered',
    text: 'Create a one-stop fast-track consenting regime for significant projects.',
    evidence: 'Fast-track Approvals Act 2024 enacted.', source: S.legislation, asOf: 'Enacted 2024' },

  // Treaty / co-governance
  { id: 'treaty-principles', category: 'Treaty & governance', status: 'changed',
    text: 'Coalition commitment (ACT) to introduce a Treaty Principles Bill and support it to select committee.',
    evidence: 'Bill introduced Nov 2024 and went to select committee; defeated at second reading in April 2025 — National did not support it further.', source: S.parliament, asOf: 'Defeated 2nd reading, Apr 2025 — verify' },
  { id: '7aa', category: 'Treaty & governance', status: 'delivered',
    text: 'Remove section 7AA from the Oranga Tamariki Act.',
    evidence: 'Section 7AA repealed via Oranga Tamariki amendment legislation (2024).', source: S.legislation, asOf: '2024' },

  // Economy & public sector
  { id: 'rbnz-mandate', category: 'Economy', status: 'delivered',
    text: 'Return the Reserve Bank to a single mandate focused on price stability.',
    evidence: 'RBNZ remit changed to a single price-stability focus (Dec 2023).', source: S.beehive, asOf: 'Dec 2023' },
  { id: 'public-spend', category: 'Economy', status: 'in_progress',
    text: 'Reduce government back-office spending and the size of the public service.',
    evidence: 'Agency savings targets set; public-service reductions through 2024–25.', source: S.budget, asOf: 'Ongoing — verify latest' },
  { id: 'bright-line', category: 'Tax & cost of living', status: 'delivered',
    text: 'Return the bright-line test on property to two years.',
    evidence: 'Bright-line period reduced to two years from 1 July 2024.', source: S.beehive, asOf: 'From 1 Jul 2024' },
  { id: 'income-insurance', category: 'Economy', status: 'delivered',
    text: 'Do not proceed with the previous government’s Income Insurance Scheme.',
    evidence: 'The social unemployment / income insurance scheme was scrapped.', source: S.coalition, asOf: '2023–24' },
  { id: 'benefit-cpi', category: 'Welfare', status: 'delivered',
    text: 'Index main benefits to inflation (CPI) rather than average wage growth.',
    evidence: 'Benefit indexation changed to CPI via legislation (2024).', source: S.legislation, asOf: '2024' },
  { id: 'welfare-sanctions', category: 'Welfare', status: 'in_progress',
    text: 'Reintroduce work obligations and sanctions for job seekers.',
    evidence: 'Welfare "traffic light" obligations and sanctions introduced (2024); rollout ongoing.', source: S.beehive, asOf: 'From 2024 — verify' },
  { id: 'productivity-commission', category: 'Public sector', status: 'delivered',
    text: 'Disestablish the Productivity Commission.',
    evidence: 'The New Zealand Productivity Commission closed in early 2024.', source: S.beehive, asOf: 'Feb 2024' },
  { id: 'govt-targets', category: 'Public sector', status: 'delivered',
    text: 'Set clear government targets with public reporting.',
    evidence: 'Nine government target areas announced with regular public reporting (2024).', source: S.beehive, asOf: 'From 2024' },
  { id: 'light-rail', category: 'Water & infrastructure', status: 'delivered',
    text: 'Stop central-government work on Auckland Light Rail.',
    evidence: 'Government ended its work on the Auckland Light Rail project.', source: S.beehive, asOf: '2023–24' },
  { id: 'nz-battery', category: 'Water & infrastructure', status: 'delivered',
    text: 'Cancel the Lake Onslow / NZ Battery pumped-hydro project.',
    evidence: 'The NZ Battery (Lake Onslow) project was cancelled.', source: S.beehive, asOf: '2024' },
  { id: 'therapeutic-products', category: 'Health', status: 'delivered',
    text: 'Repeal the Therapeutic Products Act.',
    evidence: 'The Therapeutic Products Act was repealed (2024).', source: S.legislation, asOf: '2024' },
  { id: 'pseudoephedrine', category: 'Health', status: 'delivered',
    text: 'Allow the sale of cold-and-flu medicines containing pseudoephedrine.',
    evidence: 'Pseudoephedrine products permitted for sale again (2024).', source: S.legislation, asOf: '2024' },
  { id: 'charter-schools', category: 'Education', status: 'delivered',
    text: 'Reintroduce charter schools.',
    evidence: 'Charter school model reinstated via legislation (2024); first schools from 2025.', source: S.legislation, asOf: 'Legislated 2024; schools 2025 — verify' },
  { id: 'structured-literacy', category: 'Education', status: 'delivered',
    text: 'Require an hour each of reading, writing and maths, with structured literacy.',
    evidence: 'Structured literacy and the daily reading/writing/maths requirement introduced in primary schools (2024).', source: S.beehive, asOf: 'From 2024' },
  { id: 'maori-wards', category: 'Treaty & governance', status: 'delivered',
    text: 'Restore the right to local referendums on Māori wards.',
    evidence: 'Legislation (2024) requires councils to hold referendums to keep Māori wards.', source: S.legislation, asOf: '2024' },
  { id: 'rma-replace', category: 'Water & infrastructure', status: 'in_progress',
    text: 'Replace the Resource Management Act with new, simpler legislation.',
    evidence: 'Replacement resource-management bills introduced; full replacement under way.', source: S.parliament, asOf: 'Ongoing 2025 — verify' },
  { id: 'he-puapua', category: 'Treaty & governance', status: 'delivered',
    text: 'Stop work on He Puapua.',
    evidence: 'Government confirmed it would not progress the He Puapua report.', source: S.coalition, asOf: '2023–24' },
  { id: 'speed-limits', category: 'Water & infrastructure', status: 'delivered',
    text: 'Reverse blanket speed-limit reductions.',
    evidence: 'A new Land Transport speed-limit rule reversed many blanket reductions (2024).', source: S.beehive, asOf: '2024' },
]

// ─── Key bills / Acts under this government ──────────────────────────────────────
export const BILLS: RecordBill[] = [
  { title: 'Fast-track Approvals Act 2024', does: 'Creates a one-stop approval pathway for nationally/regionally significant infrastructure and development projects.', status: 'enacted', when: '2024', source: S.legislation },
  { title: 'Gangs Act 2024', does: 'Bans gang insignia in public places and gives police expanded dispersal and consorting powers.', status: 'enacted', when: '2024', source: S.legislation },
  { title: 'Water Services Acts repeal ("Three Waters")', does: 'Repeals the Affordable Water Reforms; replaced by the "Local Water Done Well" model.', status: 'enacted', when: '2024', source: S.legislation },
  { title: 'Natural and Built Environment / Spatial Planning Act repeal', does: 'Repeals the previous government’s RMA-reform Acts, reinstating the RMA pending replacement.', status: 'enacted', when: 'Dec 2023', source: S.legislation },
  { title: 'Pae Ora (Māori Health Authority) amendment', does: 'Disestablishes Te Aka Whai Ora, the Māori Health Authority.', status: 'enacted', when: '2024', source: S.legislation },
  { title: 'Oranga Tamariki (section 7AA) amendment', does: 'Removes section 7AA, the Treaty-of-Waitangi practice provision in child-protection law.', status: 'enacted', when: '2024', source: S.legislation },
  { title: 'Three Strikes sentencing legislation', does: 'Reinstates a "three strikes" regime of escalating penalties for serious repeat offending.', status: 'enacted', when: '2025', source: S.legislation },
  { title: 'Treaty Principles Bill (ACT member’s/coalition bill)', does: 'Proposed to define the principles of the Treaty of Waitangi in statute.', status: 'defeated', when: 'Defeated 2nd reading, Apr 2025', source: S.parliament },
]

// ─── Priorities / themes through the term ────────────────────────────────────────
export const PRIORITIES: Priority[] = [
  { theme: 'Restoring fiscal discipline', detail: 'Tax-bracket relief, spending reductions, a single Reserve Bank mandate, and a return-to-surplus track.' },
  { theme: 'Cost of living', detail: 'Targeted tax relief, FamilyBoost, removing the fuel tax and the Clean Car Discount.' },
  { theme: 'Law and order', detail: 'Gang crackdown, Three Strikes, youth-offender academies, sentencing changes.' },
  { theme: 'Infrastructure & growth', detail: 'Fast-track consenting, RMA replacement, Roads of National Significance.' },
  { theme: 'Unwinding the prior government’s programme', detail: 'Three Waters, RMA reforms, Māori Health Authority, smokefree amendments, co-governance arrangements.' },
]

// Tally for the scorecard.
export function promiseTally() {
  const t = { delivered: 0, in_progress: 0, changed: 0, not_done: 0 }
  for (const p of PROMISES) t[p.status]++
  return { ...t, total: PROMISES.length }
}
