/**
 * AUTO-GENERATED by scripts/gen-political-terms.mjs — do not edit by hand.
 * Shared party + political term lists for ingest-news.mjs and ingest-videos.mjs.
 * 290 party terms across 14 parties (every current MP by full name)
 * plus 28 general political signal terms, and per-MP name
 * tags for 122 MPs (slug → full-name variants) for individual-MP tagging.
 */

export const PARTY_TERMS = {
  "national": [
    "andrew bayly",
    "barbara kuriger",
    "cameron brewer",
    "carl bates",
    "carlos cheung",
    "catherine wedd",
    "chris bishop",
    "chris penk",
    "christopher luxon",
    "dan bidois",
    "dana kirkpatrick",
    "david macleod",
    "erica stanford",
    "gerry brownlee",
    "grant mccallum",
    "greg fleming",
    "hamish campbell",
    "james meager",
    "joseph mooney",
    "katie nimon",
    "louise upston",
    "luxon",
    "mark mitchell",
    "matt doocey",
    "maureen pugh",
    "melissa lee",
    "mike butterick",
    "miles anderson",
    "nancy lu",
    "national announces",
    "national backs",
    "national commits to",
    "national confirms",
    "national defends",
    "national government",
    "national hits out",
    "national minister",
    "national mp",
    "national party",
    "national plans to",
    "national pledges",
    "national promises",
    "national proposes",
    "national reveals",
    "national rules out",
    "national says",
    "national slams",
    "national unveils",
    "national vows",
    "national wants",
    "national's",
    "national-led",
    "nicola grigg",
    "nicola willis",
    "paul goldsmith",
    "paulo garcia",
    "penny simmonds",
    "rima nakhle",
    "ryan hamilton",
    "sam uffindell",
    "scott simpson",
    "shane reti",
    "simeon brown",
    "simon watts",
    "stuart smith",
    "suze redmayne",
    "tama potaka",
    "tim costley",
    "tim van de molen",
    "todd mcclay",
    "tom rutherford",
    "vanessa weenink"
  ],
  "labour": [
    "arena williams",
    "ayesha verrall",
    "barbara edmonds",
    "camilla belich",
    "carmel sepuloni",
    "chris hipkins",
    "cushla tangaere-manuel",
    "damien o\\",
    "dan rosewarne",
    "deborah russell",
    "duncan webb",
    "georgie dansey",
    "ginny andersen",
    "glen bennett",
    "greg o\\",
    "helen white",
    "hipkins",
    "ingrid leary",
    "jan tinetti",
    "jenny salesa",
    "jo luxton",
    "kieran mcanulty",
    "labour announces",
    "labour backs",
    "labour commits to",
    "labour confirms",
    "labour defends",
    "labour government",
    "labour hits out",
    "labour mp",
    "labour party",
    "labour plans to",
    "labour pledges",
    "labour promises",
    "labour proposes",
    "labour reveals",
    "labour rules out",
    "labour says",
    "labour slams",
    "labour unveils",
    "labour vows",
    "labour wants",
    "labour's",
    "labour-led",
    "lemauga lydia sosene",
    "megan woods",
    "phil twyford",
    "priyanca radhakrishnan",
    "rachel boyack",
    "rachel brooking",
    "reuben davidson",
    "shanan halbert",
    "tangi utikere",
    "tracey mclellan",
    "vanushi walters",
    "willie jackson",
    "willow-jean prime"
  ],
  "green": [
    "celia wade-brown",
    "chloe swarbrick",
    "chlöe swarbrick",
    "francisco hernandez",
    "green mp",
    "green party",
    "greens announce",
    "greens back",
    "greens defend",
    "greens hit out",
    "greens pledge",
    "greens promise",
    "greens propose",
    "greens reveal",
    "greens rule out",
    "greens say",
    "greens slam",
    "greens unveil",
    "greens want",
    "greens'",
    "hūhana lyndon",
    "julie anne genter",
    "kahurangi carter",
    "lan pham",
    "lawrence xu-nan",
    "marama davidson",
    "mike davidson",
    "ricardo menéndez march",
    "scott willis",
    "steve abel",
    "swarbrick",
    "tamatha paul",
    "teanau tuiono",
    "the greens",
    "the greens announce",
    "the greens back",
    "the greens defend",
    "the greens hit out",
    "the greens pledge",
    "the greens promise",
    "the greens propose",
    "the greens reveal",
    "the greens rule out",
    "the greens say",
    "the greens slam",
    "the greens unveil",
    "the greens want"
  ],
  "act": [
    "act mp",
    "act new zealand",
    "act party",
    "act's",
    "andrew hoggard",
    "brooke van velden",
    "cameron luxton",
    "david seymour",
    "karen chhour",
    "laura mcclure",
    "mark cameron",
    "nicole mckee",
    "parmjeet parmar",
    "seymour",
    "simon court",
    "todd stephenson"
  ],
  "nzfirst": [
    "andy foster",
    "casey costello",
    "david wilson",
    "jamie arbuckle",
    "jenny marcroft",
    "mark patterson",
    "new zealand first",
    "nz first",
    "nz first announces",
    "nz first backs",
    "nz first commits to",
    "nz first confirms",
    "nz first defends",
    "nz first hits out",
    "nz first plans to",
    "nz first pledges",
    "nz first promises",
    "nz first proposes",
    "nz first reveals",
    "nz first rules out",
    "nz first says",
    "nz first slams",
    "nz first unveils",
    "nz first vows",
    "nz first wants",
    "shane jones",
    "winston peters"
  ],
  "tpm": [
    "debbie ngarewa-packer",
    "hana-rawhiti maipi-clarke",
    "maori party",
    "māori party",
    "māori party announces",
    "māori party backs",
    "māori party commits to",
    "māori party confirms",
    "māori party defends",
    "māori party hits out",
    "māori party plans to",
    "māori party pledges",
    "māori party promises",
    "māori party proposes",
    "māori party reveals",
    "māori party rules out",
    "māori party says",
    "māori party slams",
    "māori party unveils",
    "māori party vows",
    "māori party wants",
    "ngarewa-packer",
    "oriini kaipara",
    "rawiri waititi",
    "te pati maori",
    "te pāti māori",
    "te pāti māori announces",
    "te pāti māori backs",
    "te pāti māori commits to",
    "te pāti māori confirms",
    "te pāti māori defends",
    "te pāti māori hits out",
    "te pāti māori plans to",
    "te pāti māori pledges",
    "te pāti māori promises",
    "te pāti māori proposes",
    "te pāti māori reveals",
    "te pāti māori rules out",
    "te pāti māori says",
    "te pāti māori slams",
    "te pāti māori unveils",
    "te pāti māori vows",
    "te pāti māori wants",
    "waititi"
  ],
  "top": [
    "opportunity party",
    "qiulae wong",
    "top party"
  ],
  "independent": [
    "mariameno kapa-kingi",
    "tākuta ferris"
  ],
  "alcp": [
    "alcp",
    "aotearoa legalise cannabis",
    "legalise cannabis party",
    "maki herbert",
    "michael appleby"
  ],
  "animal-justice": [
    "animal justice",
    "animal justice party",
    "danette wereta",
    "rob mcneil"
  ],
  "conservative": [
    "conservative party",
    "conservative party nz",
    "helen houghton"
  ],
  "nz-outdoors": [
    "nz outdoors",
    "outdoors & freedom",
    "outdoors and freedom",
    "sue grey"
  ],
  "vision-nz": [
    "hannah tamaki",
    "vision new zealand",
    "vision nz"
  ],
  "womens-rights": [
    "jill ovens",
    "women's rights party",
    "womens rights party"
  ]
}

export const POLITICAL_TERMS = [
  "prime minister",
  "deputy prime minister",
  "cabinet minister",
  "associate minister",
  "minister",
  "cabinet",
  "parliament",
  "select committee",
  "the beehive",
  "coalition government",
  "coalition deal",
  "opposition leader",
  "question time",
  "by-election",
  "referendum",
  "legislation",
  "law change",
  "government's",
  "the government announced",
  "government policy",
  "roads of national significance",
  "fast-track",
  "three strikes",
  "treaty principles",
  "te tiriti",
  "waitangi tribunal",
  "electorate mp",
  "list mp"
]

export const MP_TERMS = {
  "andrew-bayly": [
    "andrew bayly"
  ],
  "andrew-hoggard": [
    "andrew hoggard"
  ],
  "andy-foster": [
    "andy foster"
  ],
  "arena-williams": [
    "arena williams"
  ],
  "ayesha-verrall": [
    "ayesha verrall"
  ],
  "barbara-edmonds": [
    "barbara edmonds"
  ],
  "barbara-kuriger": [
    "barbara kuriger"
  ],
  "brooke-van-velden": [
    "brooke van velden"
  ],
  "cameron-brewer": [
    "cameron brewer"
  ],
  "cameron-luxton": [
    "cameron luxton"
  ],
  "camilla-belich": [
    "camilla belich"
  ],
  "carl-bates": [
    "carl bates"
  ],
  "carlos-cheung": [
    "carlos cheung"
  ],
  "carmel-sepuloni": [
    "carmel sepuloni"
  ],
  "casey-costello": [
    "casey costello"
  ],
  "catherine-wedd": [
    "catherine wedd"
  ],
  "celia-wade-brown": [
    "celia wade-brown"
  ],
  "chle-swarbrick": [
    "chlöe swarbrick"
  ],
  "chris-bishop": [
    "chris bishop"
  ],
  "chris-hipkins": [
    "chris hipkins"
  ],
  "chris-penk": [
    "chris penk"
  ],
  "christopher-luxon": [
    "christopher luxon"
  ],
  "cushla-tangaere-manuel": [
    "cushla tangaere-manuel"
  ],
  "damien-oconnor": [
    "damien o\\"
  ],
  "dan-bidois": [
    "dan bidois"
  ],
  "dan-rosewarne": [
    "dan rosewarne"
  ],
  "dana-kirkpatrick": [
    "dana kirkpatrick"
  ],
  "david-macleod": [
    "david macleod"
  ],
  "david-seymour": [
    "david seymour"
  ],
  "david-wilson": [
    "david wilson"
  ],
  "debbie-ngarewa-packer": [
    "debbie ngarewa-packer"
  ],
  "deborah-russell": [
    "deborah russell"
  ],
  "duncan-webb": [
    "duncan webb"
  ],
  "erica-stanford": [
    "erica stanford"
  ],
  "francisco-hernandez": [
    "francisco hernandez"
  ],
  "georgie-dansey": [
    "georgie dansey"
  ],
  "gerry-brownlee": [
    "gerry brownlee"
  ],
  "ginny-andersen": [
    "ginny andersen"
  ],
  "glen-bennett": [
    "glen bennett"
  ],
  "grant-mccallum": [
    "grant mccallum"
  ],
  "greg-fleming": [
    "greg fleming"
  ],
  "greg-oconnor": [
    "greg o\\"
  ],
  "hamish-campbell": [
    "hamish campbell"
  ],
  "hana-rawhiti-maipi-clarke": [
    "hana-rawhiti maipi-clarke"
  ],
  "helen-white": [
    "helen white"
  ],
  "huhana-lyndon": [
    "hūhana lyndon"
  ],
  "ingrid-leary": [
    "ingrid leary"
  ],
  "james-meager": [
    "james meager"
  ],
  "jamie-arbuckle": [
    "jamie arbuckle"
  ],
  "jan-tinetti": [
    "jan tinetti"
  ],
  "jenny-marcroft": [
    "jenny marcroft"
  ],
  "jenny-salesa": [
    "jenny salesa"
  ],
  "jo-luxton": [
    "jo luxton"
  ],
  "joseph-mooney": [
    "joseph mooney"
  ],
  "julie-anne-genter": [
    "julie anne genter"
  ],
  "kahurangi-carter": [
    "kahurangi carter"
  ],
  "karen-chhour": [
    "karen chhour"
  ],
  "katie-nimon": [
    "katie nimon"
  ],
  "kieran-mcanulty": [
    "kieran mcanulty"
  ],
  "lan-pham": [
    "lan pham"
  ],
  "laura-mcclure": [
    "laura mcclure"
  ],
  "lawrence-xu-nan": [
    "lawrence xu-nan"
  ],
  "lemauga-lydia-sosene": [
    "lemauga lydia sosene"
  ],
  "louise-upston": [
    "louise upston"
  ],
  "marama-davidson": [
    "marama davidson"
  ],
  "mariameno-kapa-kingi": [
    "mariameno kapa-kingi"
  ],
  "mark-cameron": [
    "mark cameron"
  ],
  "mark-mitchell": [
    "mark mitchell"
  ],
  "mark-patterson": [
    "mark patterson"
  ],
  "matt-doocey": [
    "matt doocey"
  ],
  "maureen-pugh": [
    "maureen pugh"
  ],
  "megan-woods": [
    "megan woods"
  ],
  "melissa-lee": [
    "melissa lee"
  ],
  "mike-butterick": [
    "mike butterick"
  ],
  "mike-davidson": [
    "mike davidson"
  ],
  "miles-anderson": [
    "miles anderson"
  ],
  "nancy-lu": [
    "nancy lu"
  ],
  "nicola-grigg": [
    "nicola grigg"
  ],
  "nicola-willis": [
    "nicola willis"
  ],
  "nicole-mckee": [
    "nicole mckee"
  ],
  "oriini-kaipara": [
    "oriini kaipara"
  ],
  "parmjeet-parmar": [
    "parmjeet parmar"
  ],
  "paul-goldsmith": [
    "paul goldsmith"
  ],
  "paulo-garcia": [
    "paulo garcia"
  ],
  "penny-simmonds": [
    "penny simmonds"
  ],
  "phil-twyford": [
    "phil twyford"
  ],
  "priyanca-radhakrishnan": [
    "priyanca radhakrishnan"
  ],
  "rachel-boyack": [
    "rachel boyack"
  ],
  "rachel-brooking": [
    "rachel brooking"
  ],
  "rawiri-waititi": [
    "rawiri waititi"
  ],
  "reuben-davidson": [
    "reuben davidson"
  ],
  "ricardo-menendez-march": [
    "ricardo menéndez march"
  ],
  "rima-nakhle": [
    "rima nakhle"
  ],
  "ryan-hamilton": [
    "ryan hamilton"
  ],
  "sam-uffindell": [
    "sam uffindell"
  ],
  "scott-simpson": [
    "scott simpson"
  ],
  "scott-willis": [
    "scott willis"
  ],
  "shanan-halbert": [
    "shanan halbert"
  ],
  "shane-jones": [
    "shane jones"
  ],
  "shane-reti": [
    "shane reti"
  ],
  "simeon-brown": [
    "simeon brown"
  ],
  "simon-court": [
    "simon court"
  ],
  "simon-watts": [
    "simon watts"
  ],
  "steve-abel": [
    "steve abel"
  ],
  "stuart-smith": [
    "stuart smith"
  ],
  "suze-redmayne": [
    "suze redmayne"
  ],
  "takuta-ferris": [
    "tākuta ferris"
  ],
  "tama-potaka": [
    "tama potaka"
  ],
  "tamatha-paul": [
    "tamatha paul"
  ],
  "tangi-utikere": [
    "tangi utikere"
  ],
  "teanau-tuiono": [
    "teanau tuiono"
  ],
  "tim-costley": [
    "tim costley"
  ],
  "tim-van-de-molen": [
    "tim van de molen"
  ],
  "todd-mcclay": [
    "todd mcclay"
  ],
  "todd-stephenson": [
    "todd stephenson"
  ],
  "tom-rutherford": [
    "tom rutherford"
  ],
  "tracey-mclellan": [
    "tracey mclellan"
  ],
  "vanessa-weenink": [
    "vanessa weenink"
  ],
  "vanushi-walters": [
    "vanushi walters"
  ],
  "willie-jackson": [
    "willie jackson"
  ],
  "willow-jean-prime": [
    "willow-jean prime"
  ],
  "winston-peters": [
    "winston peters"
  ]
}

/** Party slugs mentioned in the text (matched case-insensitively). */
export function tagParties(text) {
  const t = text.toLowerCase()
  return Object.keys(PARTY_TERMS).filter((p) => PARTY_TERMS[p].some((term) => t.includes(term)))
}

/** MP slugs named in the text (case-insensitive, multi-word full name = high precision). */
export function tagMPs(text) {
  const t = text.toLowerCase()
  return Object.keys(MP_TERMS).filter((slug) => MP_TERMS[slug].some((term) => t.includes(term)))
}

/** True if the text is politically relevant — mentions a party or a political signal term. */
export function isPolitical(text, parties) {
  if (parties && parties.length > 0) return true
  const t = text.toLowerCase()
  return POLITICAL_TERMS.some((term) => t.includes(term))
}
